### PR TITLE
Removes fuzzy cuffs, makes straitjackets adminspawn only for now.

### PR DESCRIPTION
**Pull request by Roland410**
🆑Roland410
:rscdel:Fuzzy cuffs have been removed.
:rscdel:Straitjackets are adminspawn only until they are made escapeable.
:tweak:Gift wrapping people only needs to have them cuffed now, make sure to send your coworkers away!
:maptweak:Halved the amount of blindfolds and muzzles medical spawns with.
/🆑
Fuzzy cuffs fall under fetish gear, and have no use other than that, and straight-jackets are only used to cuck antags, as you can't escape them. I don't feel like putting in the effort to implement a way to do so, and as such I'm removing them. While I was there, I halved the blindfolds and muzzles medical starts with. Six is insane, and three is going to be more than enough.

While some could argue that blindfolds and muzzles are kind of fetish gear, these have actual uses outside of that especially for kidnapping.

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
A little eh on removing straight jackets, but your point on it is fair. Everything else is great.

**Comment by Roland410** [comment]
I mean, if someone wants to go and implement it in a way where it doesn't act like a supercuff, sure, but seeing as you can't take it off without outside help, it's awful right now.

**Comment by Allfd** [comment]
Edge case for straight-jackets would be that it is impossible to handcuff a one-handed antag.  I have only ever seen that on BoH as a gimmick once.  But figured it could be worth mentioning.

**Comment by Jeff-Dome** [comment]
Straight Jackets are straight up unresistable to get out of, once your in them. you physically can't get out of them, I'd suggest making them able to get out of, might be lengthy to get out of but still gameplay over realism

**Comment by Roland410** [comment]
Basically what Jeff said, but I honestly don't have the effort to make it so. Restraining people as security is already quite easy considering the amount of tools they have at their disposal, and at worst can just use Soporific or Chloral to put someone to sleep, although that may be often overkill just like straightjackets.

**Comment by Andromeda-K22** [comment]
That's a lot of sopo to keep someone asleep and *pretty shitty*.

Fuzzy cuffs aren't fetish gear. Gimmicky, but not fetish gear.

**Comment by Roland410** [comment]
I'd argue about the fuzzy cuffs not being fetish gear, considering collars were deemed so as well, and the only place I think those cuffs would be used is in the dorms etc. for ERP.

Also yes, it'd be a lot of soporific, but I'd consider it a last resort anyways. Currently straightjackets are not escapeable and as such only used to cuck antags.

**Comment by Sparrowbird611** [comment]
Yeah, I'd be fine with seeing straight jackets removed.

Honestly, how tf are fuzzy cuffs not fetish gear? The only time those are used is if you're comrade stutternov, or if you're doing some kind of ERP. At best, you could say they're legal handcuffs for recreational purposes as their gimmick, but can we really argue they aren't fetish gear?

**Comment by Andromeda-K22** [comment]
I really, really don't think they're any kind of fetish gear. Even Southy
plays it up for a gimmick.

**Comment by Roland410** [comment]
That means nothing. I could easily "play up" collars as a fashion item, but it was deemed a fetish item, and I have never used it, but it was a neat accessory.

**Comment by Andromeda-K22** [comment]
I mean Collars were explicitly used as a fetish accessory and were pushed
through by now-removed administrators.

If they were reintroduced as chokers, then it'd literally not be a problem.

**Comment by Roland410** [comment]
I mean, fair point, but I always imagined them to be more like chokers and chokers with tags etc. however, with the fuzzy cuffs I can't really do that. They're not like the breast cancer or w/e they are called IRL cuffs, nor are they tricky/magic cuffs.
They're literal bedroom fetish content, and while you could use normal cuffs, those have a proper use as well, unlike fuzzy ones.

**Comment by Torque4607** [comment]
I think that fuzzy cuffs should be left as is since they're more just a gimmick to be funny at this point, but straitjackets need to be addressed. There should either be a way to resist out of them, or they should be removed.

**Comment by Sparrowbird611** [comment]
I'm.... honestly confused what the gimmick on the fuzzy cuffs is right now. Is it legal hand cuffs or something? I missed the memo.

**Comment by BurgerLUA** [comment]
I'm conflicted about this PR honestly. I rather not have an outright removal of straight jackets as they'd be good for a traitor item.

I suggest remaking the PR and just removing straightjackets from the map, as well as blindfolds. They can be added to the traitor uplink in another PR.

**Comment by Roland410** [comment]
Straight jackets are still unescapeable, even if it's a traitor item, and they are to put it simply, quite fucking bullshit when used against you.

**Comment by BurgerLUA** [comment]
> Straight jackets are still unescapeable, even if it's a traitor item, and they are to put it simply, quite fucking bullshit when used against you.

I strongly suggest not outright removing it. I will probably make a PR that makes it so that they're actually escapable like on most servers. For now I rather not have it removed via code but rather unobtainable.

**Comment by Roland410** [comment]
> > Straight jackets are still unescapeable, even if it's a traitor item, and they are to put it simply, quite fucking bullshit when used against you.
> 
> I strongly suggest not outright removing it. I will probably make a PR that makes it so that they're actually escapable like on most servers. For now I rather not have it removed via code but rather unobtainable.

I'd suggest putting this up for voting then, while considering it's current state (not that you may or may not make it escapeable in the future) or reimplementing them later in your PR where they will be escapeable then.

**Comment by BurgerLUA** [comment]
Making a poll for this. PR will pass based on the results of this poll.

**Comment by OolongCow** [comment]
Straightjackets are literally the only recourse besides ahelps to people acting LRP, and that's the only time I've ever seen them used, either.

**Comment by Roland410** [comment]
@BurgerLUA Seeing how the poll is going so far, would it be alright if we went with your suggestion and remove it until you make them escapeable?

**Comment by Roland410** [comment]
@BurgerLUA As per Discord conversation, I've made it so straitjackets are adminspawn only now, also forgot to include that gift wrappers only need handcuffs now, so I updated that in the PR.

**Comment by Sparrowbird611** [comment]
Just gonna point out that the vox ship @crackparrot made has like three straight jackets, so if you're against them existing at all, you may want to talk to him.

**Comment by Roland410** [comment]
@BurgerLUA Resolved the conflicts yesterday.

**Comment by chaoko99** [comment]
image
controversial was a way to put it.

**Comment by Roland410** [comment]
That vote is outdated anyways, as the PR has been changed since.

**Pull request merged**
