### PR TITLE
Adds Brand New Marksman Rifle (Z2 Hornet)

### PR DESCRIPTION
**Pull request by Dark1Star3s**
* Added New Ammo Type, MILITARY_RIFLE_LARGE (12mm)
* Added New Sprite, Z2 Hornet https://i.gyazo.com/03e862c14f96763934d0819d2e52f783.png
* Added New Gunshot, Hornet.ogg
* Added Hornet to Cargo List, Can only be ordered on Code Red along with the Ammo.
* Added Hornet to Uplink, 72 Points.
* Added Hornet Ammo to Uplink, 5 points.

"Ugggh another weapon PR, baaaad." is probably what you're thinking. But I spent way too long on this for me to NOT try and PR it.
"Why?"
Well, the Energy Marksman Rifle is actually quite terrible, so much so in fact that, it's NEVER used. It would be also nice for antags to be able to have a sniper rifle that's not a OHK sniper rifle, which this is not. It costs 72 points, has 45 damage and 30 AP.

Also this is my largest PR yet go me!

### CODE REVIEW

**Comment by Roland410** [comment]
Wouldn't be a bad PR, but as I said, downvoting because gun bloat.

**Comment by Glitterhoof** [comment]
Upvoting because more ballistic guns

**Comment by OolongCow** [comment]
If it's locked to cargo on red, it will literally never be ordered by security. Command and the CoS can hardly tie their shoelaces once things go bellyup, and Supply is literally the last department on their mind. Even Science can print new AI upload boards and gadgets. Not to mention that we have all of two people who actually play the department, one of whom IS the antag in 60% of rounds.

If you want it to be a powerful weapon that still sees use, replace the CoS's AMR with it and limit the ammo to being printed on red.

**Comment by Roland410** [comment]
This is an antag gun, not for security.

**Comment by Dark1Star3s** [comment]
> If it's locked to cargo on red, it will literally never be ordered by security. Command and the CoS can hardly tie their shoelaces once things go bellyup, and Supply is literally the last department on their mind. Even Science can print new AI upload boards and gadgets. Not to mention that we have all of two people who actually play the department, one of whom IS the antag in 60% of rounds.
> 
> If you want it to be a powerful weapon that still sees use, replace the CoS's AMR with it and limit the ammo to being printed on red.

You'd be suprised, weapons on red actually get ordered a decent amount, it's usually by other sec officers, and if someone really wanted it they can just send an E-Mail to a BO to authorise the order and send the shuttle. It's very situational, and yes it could replace the AMR in the Sec Office too.

**Comment by DriedCrust** [comment]
Needs another one to gather ammo that isn't supply (lathe is a good option) plus a place it can be acquired regurlarly (CoS office is a good choice), this is too make sure it isn't an antag only gimmick gun, we already have million of those.

**Comment by Sparrowbird611** [comment]
I disagree tbh. It's a sniper rifle, you shouldn't be able to acquire half a million bullets to camp a hallway forever.

**Pull request merged**
