### PR TITLE
Fixes the commented out darkrp baton (NOT FOR APRIL FOOLS!)

### PR DESCRIPTION
**Pull request by anconfuzedrock**
## About The Pull Request
Fixes the broken darkrp baton. this version causes no errors.
## Why It's Good for the game
fixes broken code. It threw errors because it needed areas in the torch, it's in the torch now so it has those areas.
## Did You Test It?srsjs
Yes!
## Authorship
Rock
## Changelog

:cl:
/:cl:

### CODE REVIEW

**Comment by Kaksisilma** [comment]
contributors aren't supposed to suck dicks

**Comment by ProbablyCarl** [comment]
Area needs to be defined in the file, otherwise it won't work. Look at how we used to have it.

**Comment by anconfuzedrock** [comment]
> Area needs to be defined in the file, otherwise it won't work. Look at how we used to have it.

for any people who aren't omniscient who are reading this, I talked to carl and we found out the code I have works as it is now.

**Comment by anconfuzedrock** [comment]
I'm going to see if I can fix these code errors and make it into a good christian pr...

**Comment by anconfuzedrock** [comment]
It works!

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
