### PR TITLE
Let's remove all the hardstuns in the game

### PR DESCRIPTION
**Pull request by Rayfod**
## About The Pull Request
Let's get the ranged stun combat removed, so it no longer cheaps the overall combat experience of the server
Also, voxslug fix for the armalis targeting
Details of what exactly was changed
The laser sniper rifle was changed to have its stun removed, and the weakness changed to 2
The large energy crossbow (which can only really be bought from the merchant) got reduced to 3 weakness (it still are able to shoot 3 times)
The same with the ninja gun, but I changed it to have 3 ammo instead of 2
The sniper had its hard stun removed. It still does weakness.
The neurotoxin for the xenomorph game mode got changed to 3 weaknesses as well
The skrell meme gun got its 1 sec stun removed (it's able to wallbang, has 75% penetration, and very good damage)
## Why It's Good For The Game
Everyone hates getting stunned at range, and having no ability to fight back as they die.
## Did You Test It?
I tested if the voxslugs targeted the voxes or the armalis
Weakness test
https://youtu.be/czeycw08QIs
## Authorship
Aye
## Changelog

:cl:
Stun removal and nerfed the weaken effect to not be longer than 3 secs, for a few guns.
Armalis are no longer targeted by the voxslugs
/:cl:

### CODE REVIEW

**Comment by Kaksisilma** [comment]
Overall very unkeen on seeing the balance part of this merged (The Slug one would go through fine. This is why it's important to do different changes in separate PRs), but I'll wait for other opinions regarding it.

**Comment by Rayfod** [comment]
One weakness is around 3 secs
so anything that has five weaknesses means that they are soft stunned for approximately 15 secs
If you want to reference the new balance changes, then do watch the video.

**Comment by BurpleBineapple** [comment]
You may as well remove the mini energy crossbow entirely at this point. Its only real use is the one shot hardstun for a few seconds.

Overall, meh. I don't really see the problem with low capacity guns that can floor people. 

If you're going to remove hardstuns, go ahead and remove the Ascent seizure guns as well.

**Comment by ProbablyCarl** [comment]
Not a fan of this PR.
There's a select few weapons (Ascent Defence Lance, for example) that rely specifically on non-lethal takedowns with stuns.
They wouldn't function otherwise, and are specifically made to facilitate capture / RP in a very, _very_ short period.

**Comment by Rayfod** [comment]
Gonna remove the stun on the skrell gun and the voxslugs in two other PR's
Instead of one big one

**Pull request closed without merging**
