### PR TITLE
Removes Paramedic from Diona

### PR DESCRIPTION
**Pull request by Sparrowbird611**
No diona player has ever played paramedic as far as I know, but I'm doing this any way. Have you seen the speed Diona move at? They run at a mile per ten hours, and they can't even run, so they go even slower than that. This is one of the few roles where speed is absolutely necessary, something Diona can't offer. So here we are.

### CODE REVIEW

**Comment by Roland410** [comment]
This doesn't remove Paramedic. This removes medtech, corpsman AND paramedic from dionaea.

**Comment by Sparrowbird611** [comment]
………..Aren't those all the same role....?

**Comment by Sparrowbird611** [comment]
I know paramedic and corpsman were both alt titles for medtech, but I assumed med tech had the same responsibilities.

**Comment by Roland410** [comment]
Paramedic and corpsman are medtech alt-titles, and I don't think disallowing them from those roles are a good change. Dionaea may be slow, but they are totally viable to play medical with.

**Comment by Sparrowbird611** [comment]
Yeah, I didn't disallow the rest of the roles, I just removed access to med tech because I assumed it wwas just another name for paramedic. If it's not, I'll close this.

**Comment by Roland410** [comment]
Medtech is the "regular" name, paramedic is the alt-title along with corpsman. Same as counselor having the mentalist alt-title (although different mechanics apply for that).
http://prntscr.com/r96hj4

**Comment by Sparrowbird611** [comment]
So med techs are just doctors then? In that case, I'll close this.

**Pull request closed without merging**
