### PR TITLE
Adds Steward

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
Mirrors this except for the utensil changes https://github.com/Baystation12/Baystation12/pull/31502
Removes E5 from chef because ????

## Why It's Good For The Game
Just one of many bloat roles still present on the ship for no reason.

## Did You Test It?
Yes

## Authorship
Spookerton
Me

## Changelog

:cl:
rscdel: Bartender
tweak: Chef into Steward
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
you should probably increase the total positions for steward, then. Doesn't look like you did, and there's 4 lockers total for all of them.

**Comment by Lamasmaster** [comment]
They really don't need 4 slots for at best 2 man job

**Comment by Anton-Kr** [comment]
Honestly don't really like this that much. Currently both barkeep and chef (to the best of my knowledge) have kitchen AND bar access, with a way for them to differentiate and focus on one thing but optionally man both jobs. Just not really sure as to what this solves or adds. I'll let other maintainers weigh in however.

**Comment by anconfuzedrock** [comment]
> They really don't need 4 slots for at best 2 man job

imagine wanting to play chef and there's 2 bartenders.

**Comment by Lamasmaster** [comment]
You realize you can be BOTH at once as the one slot, besides it sucks as is if there is another person alongside you in kitchen and especially in bar since everyone has their own way of setting up things.

**Comment by Anton-Kr** [comment]
After reading feedback from fellow maintainers and from Carl, the overall view of this change was negative. I thank you for the PR nonetheless.

**Pull request closed without merging**
