### PR TITLE
Round time is based on REAL time instead of time adjusted for lag.

### PR DESCRIPTION
**Pull request by BurgerLUA**
Draft PR.
Title is self-explanatory.

Need to test this so it's a draft.

### CODE REVIEW

**Comment by Difrit** [comment]
May present minor non-code issues with things based on in-game timers, like the nuke, brig timers or jump/evac taking longer than the real-time timer. Worth checking how this impacts those.

**Comment by GrayRachnid** [comment]
> May present minor non-code issues with things based on in-game timers, like the nuke, brig timers or jump/evac taking longer than the real-time timer. Worth checking how this impacts those.

This only impacts the vote.

**Comment by BurgerLUA** [comment]
It actually impacts a few other things that I need to list here once I start testing the PR and looking at the code.

**Comment by BurgerLUA** [comment]
Works fine here. The change only affects round time now.

**Pull request merged**
