### PR TITLE
Quality of Life Colony Update

### PR DESCRIPTION
**Pull request by OfficialTerminaStation**
So I've played a lot of colony rounds lately, and I thought it was missing something. These improvements should fix/add to the colony experience.

-Added a new airlock type. (This new airlock has a keypad you can set a custom code to.)
-Added a new pistol (XM24)
-Improved colony
-Fixed vermin rifle on colony

Hopefully these improvements to colony will just make it slightly more fun.

### CODE REVIEW

**Comment by Roland410** [comment]
You didn't properly mapmerge this, and I'm not a fan of keypad airlocks being a thing where you can lock others out of places, especially if someone goes SSD/cryos with the code. Every part of the colony is meant to be accessible by everyone.

**Comment by OfficialTerminaStation** [comment]
> You didn't properly mapmerge this, and I'm not a fan of keypad airlocks being a thing where you can lock others out of places, especially if someone goes SSD/cryos with the code. Every part of the colony is meant to be accessible by everyone.

I think it's absurd that the colony have a brig but the prisoners can just walk out. And if someone do grief or logs out, you can just rewire the keypad.

**Comment by Roland410** [comment]
Colony doors should have the colony access on them, so if you take their ID, they can't open it anymore, but it may have got fucked by the area access PR and never got updated since then.

How do you rewire it? Regular hacking?

Mapmerge issue still stands though.

**Comment by BurgerLUA** [comment]
Will be closing this PR in 9 days if the map file isn't converted to tgm.

**Comment by BurgerLUA** [comment]
Closing this PR as there are no recent changes and it's on the second page.

**Pull request closed without merging**
