### PR TITLE
Infantry Rebalance - Plasmacutter Buff

### PR DESCRIPTION
**Pull request by ProbablyCarl**
- - -
Balance:
 - Infantry equipment kits moved to a secure armory, connected to their prep area.
 - Infantry rifleman slots reduced by two. This restricts the entire team to four members instead of six, as prior.
 - Non-SLs get light carriers, instead of the medium as prior.
 - RIGs moved into the armory area. Softsuits removed.
 - ~~Armory is bolted by default, but unlockable via a button on the bridge, sitting north of the Command area and with E-Arm access.~~ The button now sits next to the shutters, and SL access is required to use it.
 - ~~Infantry restricted from: Changeling, Traitor and Renegade.~~ Removed. Will be corrected in a later PR.
 - TVP-3 is no longer receivable by default. It's an admin spawn only.
 - Sec Voidsuits given an incredibly large buff to their armor values, so it's not akin to walking around naked while wearing one.
 - Infantry firearms can now only be authed by the XO/CO, same as the Pathfinder's shotgun.
 - Armory for Infantry given a bit more room, items and security.
 - Infantry kit is returned, in line with the change above.
 - Infantry RIGs given a change to their dynamic. They're now good against ballistics, rather than lasers.
 - Security given two alternative versions of the Bullpup rifle in their prep, to make up for the loss of the Tectonic.
 - Infantry Z9 can no longer load standard Bullpup mags. Start illegally loading your own.
 - Inf Prep made much larger. Given some QoL features, atop that.
- - -
Other:
 - Plasmacutter has been buffed. It's not very likely to hit, but it's got an incredible amount of pen, enough damage to get reliable delimbs, and has full beam passflags. It travels one less tile, however.

### CODE REVIEW

**Comment by nodcommando** [comment]
Questions, since I distinctly recall you complaining about people bothering you on Discord for things related to Git.

1: Why is renegade being removed from infantry? It's soft-core antag at worst, and with all of the infantry gear being moved behind secure storage, it's no different than security traitor or renegade. In fact, it's not quite as bad?

2: Why is infantry being given even worse armor than before?

**Comment by Sparrowbird611** [comment]
All good stuff.

Renegade is literally "Designated valid hunt antag." It's a terrible thing in general, but especially for muhreens and security, since it basically just gives them an extra lethal and more of an excuse to kill people.

**Comment by wisezombiekiller** [comment]
You have to think about what's good for infantry as well. Really all this does is shit on the people who actively enjoy playing infantry, myself included.

**Comment by ProbablyCarl** [comment]
Their armor is changed, plate carrier wise, to represent that they're not an on-ship security role unless absolutely required. Atop that, all that was done was move their equipment into a more secure location and area for storage.

Also, Renegade is garbage. It promotes valid hunting and isn't fun.

**Comment by wisezombiekiller** [comment]
> Their armor is changed, plate carrier wise, to represent that they're not an on-ship security role unless absolutely required. Atop that, all that was done was move their equipment into a more secure location and area for storage. - Aside the slot decrease and TVP-3 removal. Not that it was too good, anyhow.
> 
> I'd like to go in the opposite direction of this, but the Community has spoken, and, if we were to put it up to a vote, I bet you they'd want it _gone_ entirely. This is the best way to achieve a balance. Not that it'll make everyone happy.
> 
> Also, Renegade is garbage. It promotes valid hunting and isn't fun.

my problem with this is that all your doing is shitting on infantry. just appeasing the people that hate infantry is just going to make less people want to play infantry until it is dead. change infantry so that other people actually like the idea of it. you have to remember that people hating on departments can change with how they're laid out and what they get/do. all this does is encourage anti-infantry bullying, which will eventually kill it. take constructive criticism from the people who actually play the department, and keep in mind everyone else. other departments may shit on them, but at the end of the day buffing one little six member department won't fundamentally destroy the server, only make the people that do play that department happier. and you also have to remember that a quick, painless death is often better than a slow, painful one

**Comment by DriedCrust** [comment]
Removing general utility (binocs, RPDs, pry bars, C4) is too much, in my opinion.

**Comment by wisezombiekiller** [comment]
From Yacobpo157
Current nerf:
Removes relays, needed to coordinate and do their job, meaning we can’t find an explorer in danger without their coordinates or binocs. Okay just take from explorers so we can still do our jobs.
Removes radios and prybars from prep. Why even? So again just take from explorer or tool prep?
Removes tactical masks, did you at least replace with gas masks?
Removes C4 from everyone including tech? Makes sense except the removal from CTechs. We'll just use welder tank bombs now for the same result, so not an issue.
Removes 2 inf slots, making people only want to play it more,  but does help to balance the issue of boarders being overwhelmed. 
Wanting to remove renegade and traitor and ling from Inf? Then why can Sec be them?
Nerfing plate carriers never used anyways? Doesn’t seem apt, why do they have plate carriers anyways?
Putting weapons behind a second button the bridge has to press? Okay, that's actual balance like the numbers change, but the walls can just be cut down so.

Here’s a nerf I feel would  actually combat people's complaints:
Remove Inf from Rev, Cult, Ling but keep traitor and renegade.
Remove platecarriers since no one in Inf will use a light carrier since carriers were rarely used anyways, buff Inf RIG ballistic from 20 to 45-50 but increase slowdown in Inf RIG
Keep C4 for CTech, remove for everyone else
Add back prybars or add crowbars and relays to Inf prep, tools needed for their job.
Keep TVP removal since it's never used anyways.
Lower to five from six, four is very limiting.

And maybe add a softwhitelist on all Inf roles like whitelisted races?

**Comment by wisezombiekiller** [comment]
note that the above is not my idea, someone just wanted their idea posted and didn't have a git

**Comment by Jaraci** [comment]
Security cannot be renegades, by the way.

**Comment by Sparrowbird611** [comment]
Not really a fan of the new changes you made, but I think more importantly is you should update this description. It first goes on to tell you that inf slots were reduced by two, then says they were returned to six.

**Comment by ProbablyCarl** [comment]
Mistake on my part. Had intended to cross it out, but hadn't. Just caught it, as I updated it not even a few minutes ago.

**Comment by DriedCrust** [comment]
4 riflemen is too much, should go back down to 2 im my opinion.

**Comment by reklaw9** [comment]
just sayin',but you guys could give a argument or a reason behind why it should'nt be nerfed instead of saying "why are u nerfing it?you are on the side of the [insert antag name here]" people know that it is because infantry can easily kill a ascent gyne or any big threat to the ship  without security help (which was why infantry was removed).

**Comment by Jackofashepard** [comment]
These changes were pretty good

**Comment by AdamElTablawy** [comment]
The sec voidsuit buff is a little much.

Also, infantry really don't need the numbers they have right now. Explorers don't need that level of protection, which means the only reason to have so many is to be replacement sec.

And doing what we discussed and just making infantry weapons unable to be used on the ship period is preferable.

They absolutely do not need c4.

**Comment by ProbablyCarl** [comment]
Returned to four man team.

**Comment by BurgerLUA** [comment]
This PR should've been atomized. It was dumb to close #888 over this PR as it was made earlier and actually follows proper guidelines.

**Comment by N8-Toe** [comment]
I think 6 was a good number, I think making it 4 is to few.

**Comment by AdamElTablawy** [comment]
@N8-Toe 

No, six is ridiculous. There's already eight sec, we don't need to add six more.

And yes, infantry and security are indistinguishable. They have the same purpose, just different  gear, and anyone who pretends they're not the same thing is lying to themselves.

**Comment by bearrrrrrrr** [comment]
spot the infantry mains

**Comment by BurgerLUA** [comment]
Is this PR good to merge?

**Comment by ProbablyCarl** [comment]
Assuming it's acceptable, yes.
You may want to re-lower the numbers to disable the job, if staff still wishes such, however.

**Comment by BurgerLUA** [comment]
Going to merge.

**Pull request merged**
