### PR TITLE
Burntime increase for Ecigs

### PR DESCRIPTION
**Pull request by Audion-triodeman**
changes some values and causes the Ecigs to last longer. and adjusts other values to balance things out. (this is my first proper PR so someone look over it please).

## Changelog

:cl:
/:cl:

### CODE REVIEW

**Comment by Audion-triodeman** [comment]
Someone look over this please.

**Review by N8-Toe — DISMISSED** [review]
code looks good. will leave up for abit for input from other maintainers if they so choose

**Review by Audion-triodeman — COMMENTED** [review]
I edited a value because i did a dumb

**Comment by Audion-triodeman** [comment]
Changes applied.

**Comment by ShadeAware** [comment]
I see no reason not to have this, its just an excellent QOL

**Comment by Anton-Kr** [comment]
Honestly the only thing I feel iffy about is ecig cartridges now holding the equivalent volume of a large beaker. Any chance you can just reduce the consumption rate and make the cell bigger?

**Comment by Kaksisilma** [comment]
> Honestly the only thing I feel iffy about is ecig cartridges now holding the equivalent volume of a large beaker. Any chance you can just reduce the consumption rate and make the cell bigger?

Agreed with Anton here. Everything else looks OK.

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
Make ecigs not hold 100 units

**Comment by Audion-triodeman** [comment]
Alright give me a while to work on this then.

**Comment by N8-Toe** [comment]
converted to draft, unconvert it when its ready for review again

**Pull request closed without merging**
