### PR TITLE
Bear Robotics + Medical Skill PR

### PR DESCRIPTION
**Pull request by Higgin**

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
just a heads up this is my pr, but higgin posted it for me b/c my github is haunted

<3

**Comment by N8-Toe** [comment]
not to hot on lowering physician skills. as there is a lot of hefty expected skill purchases for physician. specificly the 4 points atleast to chem, and 16 to jump to master in medical skills. for robotics I will admit I dont play robotics often. But should it be reasonable to expect a single character to have trained anatomy and medical skills AND be a trained engineer, it feels like specialty over dipping

**Comment by bearrrrrrrr** [comment]
@N8-Toe so like the thing is i agree with you on both points, BUT, 

1) master medicine does, uh, actually nothing, if you wnated to optimize your skill point use. as is, on my physician, i have experienced cqc, master eva, trained construction, trained electric, basic IT, trained complex, etc,. every skill i have on them is trained or above, AND i have both chemsitry and max anatomy

2) i actually didn't change any of the default skills on robotics. currently, you need to put 8 points into it to do surgery, and 16 points in it to do surgery WELL, which leaves you to a phhhat 8 skillpoints left after the change.

it's just a consequence of the skill system that there are inherently going to be some imbalances but i'm trying to patch out the most eggregious ones like this, where a roboticist **doesn't know how to use wires** and how a physician can be a master surgeon, and also cqc expert, and also experienced pilot, and also electrical engineer

**Comment by Sparrowbird611** [comment]
Yeah, as bear said, master is really only necessary for ghetto surgery, something a doctor should rarely have to do. Chemistry I will grant you is important, but not too terrible.

I appreciate the roboticist changes, however, I'm not quite sure why you gave them max construction by default.

I honestly don't feel it's over dipping, since the roboticist has so many tasks he has to do that require a wide variety of skills. No one is really going to go to him anyway for medical treatment though, because doctors will have all the chemicals.1

**Comment by bearrrrrrrr** [comment]
@Sparrowbird611 
'I'm not quite sure why you gave them max construction by default.'

haha

i did what, now?

**Comment by bearrrrrrrr** [comment]
oh FUCK FUC KFUC KFUC KFUCK FUCK FU FCKFU FKUFC K FUC

**Comment by Sparrowbird611** [comment]
Yeah, I assume that was supposed to be basic. It's only one line to fix so.

**Pull request merged**
