### PR TITLE
Last SOME Vox ship up doots.

### PR DESCRIPTION
**Pull request by Armyguy**
Fixs a few things like nav points. And I HOPE fixs the turrets.

### CODE REVIEW

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
Please add nav points for ship boarding

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
Remove thermals to align with thermals removal PR.

**Comment by Armyguy** [comment]
Ok, I think that's the last of them

**Comment by Armyguy** [comment]
This will fix the CI errors for the vox ship

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
