### PR TITLE
Take two: Traitor Branch Expansion.

### PR DESCRIPTION
**Pull request by Sparrowbird611**
I'm not going to go over all of this again. This is an exact copy of https://github.com/BoHBranch/BoH-Bay/pull/719 the only addition is I lowered the price on the smuggler's satchel, which I have lowered to 10 TC (from 20 TC). If you want to read the details, click the link. This version shouldn't conflict with Higgin's PR.

### CODE REVIEW

**Comment by EldritchSigma** [comment]
I am still going to transfer you my up because I am a good guy and that is nice which is very wholesome.

**Comment by Sparrowbird611** [comment]
Travis is kill.

**Comment by ProbablyCarl** [comment]
Fix the travis errors, please, so we can merge this.

**Comment by Sparrowbird611** [comment]
This commit should hopefully fix it.

**Pull request merged**
