### PR TITLE
Gantry

### PR DESCRIPTION
**Pull request by sgtmind**
## About The Pull Request
Adds in gantry, am tired of having to keep make new pull requests
## Changelog

:cl:
/:cl:

### CODE REVIEW

**Comment by gilvian** [comment]
agree

**Comment by Kaksisilma** [comment]
Please refer to https://discord.com/channels/821894151872315392/937500774584418336/955621767387443230 in #dev

**Comment by sgtmind** [comment]
Must ask, anything else need to be done?

**Comment by Anton-Kr** [comment]
Not at the moment. I'll be reviewing this shortly.

**Review by Anton-Kr — DISMISSED** [review]

**Comment by Cupax3** [comment]
Squash please

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
