### PR TITLE
Revert "Revert "Makes all silicons have zero skills by default.""

### PR DESCRIPTION
**Pull request by Roland410**
Reverts BoHBranch/BoH-Bay#764
This was reverted for absolutely no fucking reason.

### CODE REVIEW

**Comment by SilvernKell** [comment]
No nooo
You need surgery borgs to have surgery skills.
Don't engi borgs need construction?
I mean the only issues would be piloting (a gameplay choice whether to have it or not) and exosuit training/. . actually, I cannot think of another issue right now

**Comment by Roland410** [comment]
Look at the code before you complain please, thank you. Borgs get their skills from their modules. This literally has no effect on anything else than the AI.

**Comment by SilvernKell** [comment]
Who was complaining
How does it affect AI then besides flying the shuttles?

**Comment by Roland410** [comment]
Sorry about that, I'm just tired in general and tired of everyone bitching about every change.
To clarify, this means the AI can't use NTnet monitoring, so hackerman need to be stopped by actual people such as the CE, SE etc. and that they can't fly ships nor use the sensors to give a scan of PoI.

**Comment by SilvernKell** [comment]
I know the feeling. Thanks for clarifying.

**Comment by ProbablyCarl** [comment]
Does this also have your patented code?

**Pull request closed without merging**
