### PR TITLE
Resprites Vents and Scrubbers

### PR DESCRIPTION
**Pull request by ShadeAware**
### What this does:
Resprites the vents and scrubbers to their more modern counterparts from TG/Citadel station. Because the current sprites are old as hell, and capital U Ugly.
image

:cl:
Edit: Vents and Scrubbers sprites have been updated to their more modern counterparts.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Forgot to edit that commit autotitle. Whoopsies.

**Comment by MarinaGryphon** [comment]
A direct port doesn't really fit this server's style. It's a bit too grimy and seems a bit jarring against the floor tiles in the screenshot provided. The outer rim of the vent uses way too many shades and it seems like it would fall apart if you blew on it. Maybe crank down the contrast between those shades to make it seem more like lighting rather than wear?

Unless that's a still frame of an animated sprite, in which case disregard all that until I see the full animation.

**Comment by ShadeAware** [comment]
> snip
You can view the file directly to see the animations.

**Comment by ShadeAware** [comment]
Scrubbers were updated earlier today by the by

**Comment by Andromeda-K22** [comment]
Poll held. In favor of merge.

**Comment by Wesreidau** [comment]
These sprites are ugly as hell, I don't care how warm a pile of horse shit I'm still not going to eat it.

**Pull request merged**
