### PR TITLE
Removes Vox Armalis Nab Grab

### PR DESCRIPTION
**Pull request by EldritchSigma**
Saw this somewhere on the discord that this is to be added or rather removed.

Removes the Vox Armalis nab.

### CODE REVIEW

**Comment by EldritchSigma** [comment]
Should work since its a simple removal.

**Comment by ProbablyCarl** [comment]
While a simple change, this is something we've been discussing. 
It was added a long while back, due to the species being whitelisted, and filling a very niche role with one slot.
It no longer really has a reason to exist, and just fuels powergame type plays.
I'll ultimately leave it up to Mazian.

**Comment by MemedHams** [comment]
I'd argue that, in-game, an armalis -should- be more powerful then most other races at CQC, considering that they are war-bred bio-mechanical monstrosities. Maybe reducing the number of armalis spawns might help, though I wouldn't be sure about that either. A competent armalis should, IC, be a dreaded threat that any normal human would be extremely cautious about facing.

**Comment by Andromeda-K22** [comment]
I haven't seen this abused, really. I've only seen Armalis use to meatshield with the crew and such, so uh, i'm gonna close this.

**Pull request closed without merging**
