### PR TITLE
adds maid outfit to loadout menu

### PR DESCRIPTION
**Pull request by AMcilraith**
## About The Pull Request
Adds maid outfits
## Why It's Good For The Game
ADDS MAID OUTFITS
## Did You Test It?
Yes
## Authorship
Dr. Farson
## Changelog

:cl: AMcIlraith
rscadd: adds maid outfit to loadout menu
/:cl:

### CODE REVIEW

**Comment by Rafflesia7793** [comment]
Needs: `allowed_roles = list(/datum/job/janitor)` in my opinion. Otherwise we will have infantry/sec running around shooting people in maid outfits calling themselves battle maids.

**Comment by ProbablyCarl** [comment]
Battle maids would be hilarious, but yes. It should be restricted if it's to see a chance of introduction.
image

**Review by N8-Toe — CHANGES_REQUESTED** [review]
Requires restriction to service and janitorial, maybe passenger up to you. Also Carl you weeb

**Comment by Rafflesia7793** [comment]
Much better. I really like that you added it to bartender and chef too. Makes sense. Maids can do more than just clean.

**Comment by BurpleBineapple** [comment]
I want to die.

Carl why would you forsake me like this.

**Comment by Anton-Kr** [comment]
lmao at this being allowed for bartender

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
