### PR TITLE
Nerfs tracking implant + Removes death alarm implant.

### PR DESCRIPTION
**Pull request by Sparrowbird611**
Tracking implant: Can not longer be targeted by the teleporter device.

Death Alarm implant: Removed from all Dagon locations. Can still be crafted by science.

The tracking implant teleportation was just a stupid feature. Being tracked is enough, having an entire security squad teleport on you because the hostage negotiator was implanted is pretty stupid, among other scenarios.

The Death Alarm is just utterly shit. It's hard enough trying to kill people who have access to them, (Mainly high profile people in command, along with the BC, CoS, and any sec grunts they implant) having a machine that screams their location and demise post mortem to security and medical is beyond irritating, and hard to deal with.

### CODE REVIEW

**Comment by Roland410** [comment]
I agree with the tracking implant, but the death alarm is fine.

**Comment by Sparrowbird611** [comment]
Meh. They're abundant, and you can easily kit half of security with the alarms. As it is, antagonists have a hard time doing anything without some one screaming their location, we don't need an implant for it as well.

**Comment by Roland410** [comment]
I'm fine with removing them from the map, but at least let it be a thing for science.

**Comment by MemedHams** [comment]
ultimately, command staff SHOULD be hard to kill, and require planning and consideration to properly pull off.

**Comment by MemedHams** [comment]
Idea: emagging a death implant creates an improvised counter that prevents death implants in it's vicinity from working, but also causes tox to the user every time it shorts when a deathalarm goes off nearby. 
Ultimately I'd recommend making a counter instead of taking the toys and leaving the sandbox.

**Comment by Roland410** [comment]
EMPing the death alarm will result in it breaking and giving a random location afaik, but just removing them from the map should solve the issue of everyone having them, as you need R&D to make them otherwise.

**Comment by Sparrowbird611** [comment]
> ultimately, command staff SHOULD be hard to kill, and require planning and consideration to properly pull off.

They're hard to kill by nature of being in the bridge 24/7. It's hard enough to even get to them, let alone kill them. I'm not going to agree with death implants existing at all.

I don't wish to leave it in R&D, because R&D is a meme rn. You max tech levels in 20 minutes or not at all, so we either end up with all or nothing.

**Comment by bearrrrrrrr** [comment]
we removed autorolling kill objectives for a reason. it basically devolved into people trying to pull off sick funny heehee killmix ganks. if you want to kill someone it's fine if you have a good IC reason, but it is also HARD for a reason

also, there are ways to get around it. one of them is by being very quick in your execution to straight up avoid the response. if you don't have a plan to get the fuck out of dodge after killing the CO, you kind of deserve it

**Comment by Sparrowbird611** [comment]
> we removed autorolling kill objectives for a reason. it basically devolved into people trying to pull off sick funny heehee killmix ganks. if you want to kill someone it's fine if you have a good IC reason, but it is also HARD for a reason
> also, there are ways to get around it. one of them is by being very quick in your execution to straight up avoid the response. if you don't have a plan to get the fuck out of dodge after killing the CO, you kind of deserve it

Auto roll kill objectives are shit and I will agree with that. However, that's not at all related to death implants.

Command tier personnel are very difficult to effectively murder, due to numerous factors, some of which I believe I've mentioned. The fact that there's also a device that full on screams out your location and their demise is beyond stupid.

Yeah, there's ways to get around it. There was also ways to get around the point decrease you receive from age. That doesn't mean either are a good mechanic.

**Comment by BurgerLUA** [comment]
conflicting with a map. this PR doesn't seem that popular , though.

**Comment by Sparrowbird611** [comment]
A little surprised by that. I think I'm just gonna separate these two for now, and just make this one the tracking implant nerf.

**Pull request closed without merging**
