### PR TITLE
Removes Partial understanding on alien languages.

### PR DESCRIPTION
**Pull request by Sparrowbird611**
Does what it says on the tin. For some reason, you could have a small understanding of sinta, yeosa, skrellian, and whatever sergals speak. Kind of stupid to partially understand these languages just because I know ZAC and spacer, especially skrell, so this PR rectifies that.

### CODE REVIEW

**Comment by MarinaGryphon** [comment]
> Does what it says on the tin. For some reason, you could have a small understanding of sinta, yeosa, skrellian, and whatever sergals speak. Kind of stupid to partially understand these languages just because I know ZAC and spacer, especially skrell, so this PR rectifies that.

ZAC is a conlang *designed* for mutual intelligibility.

Spacer is a pidgin language consisting of a bunch of languages spoken in space and literally ONLY EXISTS because people who don't share languages and interact commonly need to be able to communicate, if only primitively.

I am against this PR.

**Comment by Sparrowbird611** [comment]
Yeah, because ZAC and spacer totally let me understand random hissing, confused yapping, and literally a language that isn't even on a frequency the human ear can hear.

Seems legit.

If you're speaking an alien language, you shouldn't have a clue what's being said unless some one grabs translation tech, or actually understands said language.

**Comment by MarinaGryphon** [comment]
> literally a language that isn't even on a frequency the human ear can hear.

This is literally the only one that's an issue. I am not budging on the rest. They shouldn't have *high* values but I believe a previous PR already reduced it to, what, a 2% contribution each?

**Comment by Jaraci** [comment]
The intent of this tiny, utterly insignificant bit of mutual intelligibility is meant to represent ZAC/Spacer loanwords entering alien languages (i.e. Dagon, Garuda, Gaunt, NanoTrasen). This is a phenomenon that exists in more or less every human language I can think of (seriously, name one widely-spoken language with no borrowings from English).

I don't know if you can really grasp how low a percentage 2% is when you're dealing with partial intelligibility. This change went in weeks ago and since then I don't think I've ever understood a single word of Skrellian or Sinta that I've seen spoken around me.

**Comment by Jaraci** [comment]
Only part of Skrellian is beyond the range of human hearing, by the way, or at least that's how I always understood it. I believe that's what the * ! and other such characters are meant to represent.

**Comment by MarinaGryphon** [comment]
> The intent of this tiny, utterly insignificant bit of mutual intelligibility is meant to represent ZAC/Spacer loanwords entering alien languages (i.e. Dagon, Garuda, Gaunt, NanoTrasen). This is a phenomenon that exists in more or less every human language I can think of (seriously, name one widely-spoken language with no borrowings from English).

What they said, _capiche_? If you think that mutual intelligibility is _kitschy_, that's your opinion, but don't be a _prima donna_ about it; that's kind of a _faux-pas_. Not even a _quid pro quo_ is going to get this PR in as-is; that's just not my _modus operandi._ I get that the current _zeitgeist_ is language nerfs, but like, do you guys get some kind of _schadenfreude_ from this?

None of that is serious, mind you, but it's an example of loanwords in English. I bet you could also tell what _azucar_, _café_, and so on. Even "Kindergarten" is from German.

Yiddish is probably one of the biggest source of loanwords, especially slang: Glitch, klutz, spiel (technically itself a German loanword), schmooze, chutzpah, golem, maven, schlong, schmuck, schnoz, schtick, tush, and tuchus. Most people don't even know these are loanwords.

**Comment by Sparrowbird611** [comment]
Then what the hell is the point of an alien language if it can be understood, even partially. And for the record, I've understood enough parts of conversations to know what people were talking about plenty of times. If you really want loanwords, then make it so things like "Dagon, Garuda, Gaunt, NanoTrasen" are automatically translated, instead of some random chance to let me in on people's conversations. The whole system is stupid.

If people want to understand these languages, then they should go get a universal recorder, something literally in the loadout.

**Comment by Jaraci** [comment]
Because it's a two percent partial intelligibility. It's called flavour, it isn't something to get heated about and it will literally have a tiny, negligible effect on gameplay or round progression once in a blue moon.

You haven't randomly understood parts of Skrellian/Sinta/Sergal conversations enough to know what people were talking about "plenty of times". I'm calling bullshit on that right now, and to even make that claim you clearly don't know just how tiny a percentage 2% is when it comes to partial intelligibility. A rigorous loanword system is unfeasible simply because of how argumentative people would be over whether X word should or should not be included.

This comment is about 150 words long. Go ahead, pick any three words at random and then make the claim to me that you can know what I'm talking about in any way, shape, or form. That's what you're essentially arguing here.

**Comment by Sparrowbird611** [comment]
It doesn't take much to figure out what people are talking about. With just one word, I was able to put together that the two yeosa in the room were talking about the mercenary with the invisiblity suit.

**Comment by MemedHams** [comment]
Ok I'm not really sure why this PR is so spicy, but I'm pretty sure it makes decent sense for there to be a very small chance of word translation. Languages tend to steal from each other pretty damn often, particularly in societies and regions with a large amount of cross-cultural contact(This is historically border and port regions, but this could pretty well describe literally the entirety of civilized space.) If someone would like to put themselves through the absolute, mind-cracking torture of **manually** mapping out overlap words, I might get behind a change, but as it is I'm pretty sure the current system is quite fine.

**Comment by BurgerLUA** [comment]
Please ask the lore people permission to merge this PR.

**Comment by Sparrowbird611** [comment]
https://i.gyazo.com/a9169ccdc5184eaf1780a4f2a26735f9.png

As requested.

**Comment by MarinaGryphon** [comment]
Putting it up to a vote.

**Comment by Sparrowbird611** [comment]
I mean, it already had awaiting merge, but sure. Go ahead.

**Comment by BurgerLUA** [comment]
I don't know why it was polled in the first place, but the Lore Maintainer right now does not approve of the PR because of the poll so unfortunately this will have to be closed.

**Comment by Sparrowbird611** [comment]
Shame. Oh well.

**Comment by SilvernKell** [comment]
I don't really like understanding alien words but 2% very low, I would say it's kind of like a bit of understanding of inflection, if you don't understand what they're saying maybe the reason you understood any of it is just because you made a deduction based on their tones and body language along with it

**Pull request closed without merging**
