### PR TITLE
Remaps Medical Bay

### PR DESCRIPTION
**Pull request by MarinaGryphon**
Remaps Medical to shift away from surgery (since it's currently bugged due to the regen mechanics) and towards other, more effective methods of healing. There is still one operating theatre (and the abandoned one in D4 maint, IIRC).

### CODE REVIEW

**Comment by Hekzder** [comment]
Screenshots would be nice. Mapdiffbot is either not working for this PR or you did something terribly wrong.

**Comment by MarinaGryphon** [comment]
screeny_no_areas
screeny
Two screenshots, one with and one without areas.

**Comment by MarinaGryphon** [comment]
Also, this is intended to address [this comment](https://github.com/BoHBranch/BoH-Bay/pull/956#issuecomment-646812225). It doesn't look like an issue report was made about it, though.

**Comment by Sparrowbird611** [comment]
This...... is a god tier shitpost, right? That's just another mess hall.

**Comment by Tename** [comment]
forgot the robotics surgery bay 0/10

**Comment by MarinaGryphon** [comment]
> forgot the robotics surgery bay 0/10

I didn't, that was intentional. I downgraded surgery, I didn't remove it entirely. They also got extra equipment to help with the way Medical works now.

**Comment by Tename** [comment]
> 
> 
> > forgot the robotics surgery bay 0/10
> 
> I didn't, that was intentional. I downgraded surgery, I didn't remove it entirely. They also got extra equipment to help with the way Medical works now.
> robotics_no_areas

make the floors carpet and add a sauna machine, surgery should be relaxing

**Comment by MarinaGryphon** [comment]
IT PASSES TRAVIS

**Comment by Knightfall5** [comment]
10/10

**Comment by MarinaGryphon** [comment]
Unfortunately with #990, this PR is no longer compatible with the medical system. C'est la vie.

**Pull request closed without merging**
