### PR TITLE
Removes Telepathy from genemods

### PR DESCRIPTION
**Pull request by DriedCrust**
I've only seen telepathy being used for LRP purposes but there are plenty of arguments for and against it. This might get heated so I expected a vote from this.

### CODE REVIEW

**Comment by chaoko99** [comment]
Here's a better idea! Give it an admin log, and we can PUNISH the LRP people. We have this cool admin team and we refuse to use it apparently.

**Comment by chaoko99** [comment]
Also please provide examples of LRP behavior instead of going "Oh, but it's so LRP! Guess there's nothing we can do!"

**Comment by DriedCrust** [comment]
nice thats a better fix

**Comment by chaoko99** [comment]
Sorry for being so hostile, this isn't the kind of thing I was expecting to awake to.

**Pull request closed without merging**
