### PR TITLE
[READY] Better Sprites 2: Not-Awful Boogaloo

### PR DESCRIPTION
**Pull request by ShadeAware**
### What this does:
Overhauls a ton of sprites of a wide variety, updating old and outdated looks with new ones. Most are ported from Citadel/TG, or made by myself. Some are animated, as well.

**PREVIEWS:**
image
image
image
image
image
image
image

:cl:
Edit: Many, many sprites have been updated to modern standards. Some are even animated now!
/:cl:

### CODE REVIEW

**Comment by Roland410** [comment]
Not a fan of the new MMI sprites. They are really confusing since they just look like a brain now.
What is the traitgun used for? If it's the floral somatoray, might want to not change that.
The new powersink sprite looks like some kind of breaching charge.
I think with the modular mechs, those sprites are redundant as well, but not sure.

**Comment by ShadeAware** [comment]
*Mmi sprites are strange since actual MMIs use a different sprite with a brain overlay. I just included them for consistencies sake
*Traitgun was a machine in the sprite beforehand, so, eeh?
*Powersink is ported from TG, and fits the style better
*Mechs included before I knew Mechs were Modular. Whoopsies.

**Comment by ShadeAware** [comment]
Although I could maybe still change it later if it really fucks something that badly

**Comment by ShadeAware** [comment]
Did some final edits, this should be ready for merge now.

**Pull request merged**
