### PR TITLE
Gun Tweaking.

### PR DESCRIPTION
**Pull request by Sparrowbird611**
Alright, lets do this.

First off, majorly reduces the number of laser carbines around the Dagon. Every laser carbine on bridgedeck has been removed or replaced, with the full list being these.

Byakhee: Two laser carbines. Updated version: replaced with three smart guns
Bridge emergency bunker: three laser carbines. Updated version: replaced with three smartguns
Bridge protection armory: Four laser carbines. Updated version: Replaced with one pump shotgun, and two SMGs. Comes with four SMG mags, one box of lethals for the shotgun, and one box of non lethals for the shotgun.

Next off, buffs the XO's pistol. Original stats: 45 damage, zero AP. new stats, 45 damage, 10 AP. Sufficient against normal forms of armor, but not too insane.

The thing we've all been waiting for. AMR no longer has screen shake. This  should prevent it from breaking your screen immediately after firing while scoped.

Next off, I removed the foundation's nullglass weaponry from the Dagon. Psionic threats are seldom seen, and they rely upon insane amounts of RNG to acquire a great power that'd even give them a chance against security.

I thought I'd tweak two underused picks for traitors, namely, the grenade launcher and the Ion pistol. The Grenade Launcher was reduced to 40 TC, from 60, but no longer spawns loaded with grenades. The Ion pistol was just flat out buffed to 10 TC, from 20. Before any one riots at me, the haywire shell and zip gun slug combo come out to five tc, and a current PR will likely buff the zip gun to 1 TC, making it even better **Update** Ion gun moved to 16 TC, Haywire moved to 3 TC.

Finally, infantry prep has had all of it's weapons, C4, and other weird equipment removed. It's now just an empty room for the most part.

### CODE REVIEW

**Comment by Superhats** [comment]
I'm fine with the changes, but as I've stated several times on discord, I think the nullglass revolver should stay, considering the ammo is already in extremely limited supply (12 shots with no way to make more), and it's the ONLY way, powerful or not, to disable psions.

**Comment by Tename** [comment]
There's no real reason to remove the null glass revolver it should really stay. Ammo can't be acquired, and needs to be put in the suitcase or it will drain the advisors own powers.

**Comment by OolongCow** [comment]
> Byakhee: Two laser carbines. Updated version: replaced with three smart guns
> Bridge emergency bunker: three laser carbines. Updated version: replaced with three smartguns
> Bridge protection armory: Four laser carbines. Updated version: Replaced with one pump shotgun, and two SMGs. Comes with four SMG mags, one box of lethals for the shotgun, and one box of non lethals for the shotgun.

Agreed. There were more guns than the bridge crew could ever conceivably use just lying around, everywhere.

> Next off, buffs the XO's pistol. Original stats: 45 damage, zero AP. new stats, 45 damage, 10 AP. Sufficient against normal forms of armor, but not too insane.

Good.

> The thing we've all been waiting for. AMR no longer has screen shake. This should prevent it from breaking your screen immediately after firing while scoped.

A quick and dirty fix, but it works.

> Next off, I removed the foundation's nullglass weaponry from the Dagon. Psionic threats are seldom seen, and they rely upon insane amounts of RNG to acquire a great power that'd even give them a chance against security.

I've never agreed with outright removing counters, even if they're rare, underutilized, or just weird. I'd rather see psionics be touched on and made more common (as I believe some recent PRs are attempting to do) than have their only real counter be outright removed.

> I thought I'd tweak two underused picks for traitors, namely, the grenade launcher and the Ion pistol. The Grenade Launcher was reduced to 40 TC, from 60, but no longer spawns loaded with grenades. The Ion pistol was just flat out buffed to 10 TC, from 20. Before any one riots at me, the haywire shell and zip gun slug combo come out to five tc, and a current PR will likely buff the zip gun to 1 TC, making it even better.

Yeah, I was actually going to suggest that the Ion Pistol/Rifle nerf be extended to haywires as well. My repricing of ions came before the push for a nerf, so while I agree with it, 10 seems really, really low. That's even cheaper than the Mk58 (which is probably the most fairly-priced gun on the uplink), and only 2 TC more than a small energy gun. It should be at least the same price as the Mk58 (at 16TC) when the actual lethality of ions hasn't changed at all.

> Finally, infantry prep has had all of it's weapons, C4, and other weird equipment removed. It's now just an empty room for the most part.

Since I doubt anyone else will, I'd highly suggest keeping a copy of the map file with it still in, just in case.

**Comment by Sparrowbird611** [comment]
Nullglass revolver I'm not a fan of still. I don't particularly care for weapons that completely shut down a specific, rare ability that's supposed to terrifying and difficult to fight when it's actually encountered. I may reconsider it, but I'd like to make a few points about the arguments presented here.

12 shot limit: Ok, I first off, thought this was 18 shots, since I thought the revolver came loaded. Either way, it only requires one shot to successfully disable a foe, which, unless they're stimmed out of their mind, wielding an e shield, and dodging like a king, I can't see you missing with twelve shots. Given there's rarely more than one psyker who actually has any real power, and only one faculty can actually remove these shards without going to the hospital, it's not exactly a huge limitation in the end.

Draining the psi advisor's power: This really might as well not be an argument, since this isn't a huge loss. You lose the a mind toolbelt, that's really it. Nothing the psi advisor does is so good that having the pistol will affect. Additionally, I believe this is countered by wearing a holster, or having it in your back pack, but don't quote me on this.

Psionic power level: This argument wasn't brought up yet, but I thought I'd get it out of the way before some one comes and uses it. Psionic power level requires the stars to align for you with RNG, and only one ability can even be considered OP, this being TK. Now, I know the argument of "just dodge bro," is a shitty one for the most part and doesn't always work, but in most cases, you'll have enough time to run out of range, (Which is like, two tiles from the edge of the screen) given it takes a full five seconds for him to actually start slamming. Between this and having some better numbers, you can beat even that power. The rest are pretty lame, with the other biggest one, paramount laser cannon eyes, requiring the psi crown to fire off more than three shots, which leaves your head majorly exposed.

~~I'm definitely not doing this for the meme of watching some one throw nullglass coins and crosses at their foes.~~

**Comment by Sparrowbird611** [comment]
Any who, as for ions, I may up the price of the pistol to 16, and the price of the haywires to 3, so they aren't dirt cheap at least. In general though, I'd like to point out all EMP destroying technology is cheap, and often quite overtuned, such as the huge AoE on the EMP nade, which needs to be toned down, and I don't plan to make them incredibly expensive.

**Comment by OolongCow** [comment]
> Any who, as for ions, I may up the price of the pistol to 16, and the price of the haywires to 3, so they aren't dirt cheap at least. In general though, I'd like to point out all EMP destroying technology is cheap, and I don't plan on making any of them incredibly expensive.

That's fine. My big gripe was just that a specialist tool that can totally remove certain things from the round and doesn't use ammo would've been cheaper than the "baseline" traitor gun.

**Comment by BurgerLUA** [comment]
Has conflicts.

**Comment by Superhats** [comment]
I'm still very much against the advisor being removed.

**Comment by BurgerLUA** [comment]
Has conflicts.

**Comment by Sparrowbird611** [comment]
I will revert the foundation pistol as requested. Not the biggest fan, but there's only one so, I guess it just means any big brain who wants to go on a rampage should have the foresight to go and kill the psi advisor first.

**Comment by Sparrowbird611** [comment]
Alright, conflicts should be mostly fixed. Just don't merge this yet until after I take a look at the map one last time. I'll comment when I do.

**Comment by Sparrowbird611** [comment]
If travis passes this, it should be ready for merging.

**Comment by Sparrowbird611** [comment]
Nevermind, I've screwed up. Lemme just look at that some more.

**Comment by Sparrowbird611** [comment]
You saw nothing.

**Pull request closed without merging**
