### PR TITLE
Makes xenos unable to grenade stuff

### PR DESCRIPTION
**Pull request by Cupax3**
... because they're clowns
Also fixes ventcrawling grenade activation
Also also adds proper defines for xeno species
Also also also new list for all xeno species

## About the Pull Request
This should make benos unable to clown on infantry because 🅱️enos 🅱️ad
Also makes ventcrawling creatures unable to activate grenades.

## Why It's Good For The Game
🅱️enos 🅱️ad
✌️ent 🅱️ad

## Did you test it?
No

## Authorship
Me, idea belongs to @anconfuzedrock

## Changelog

:cl:
balance: No grenades for benos
balance: No grenades for ventcrawlers
tweak: All xenophage species are now defines and in a list
/:cl:

### CODE REVIEW

**Comment by Anton-Kr** [comment]
Before some screams at me for balance this fixes an issue of them priming grenades from vents (which should be a separate fix anyway) and they can't shoot guns now anyway so this isn't too far of a stretch.

**Comment by Cupax3** [comment]
Wait hang on don't merge

**Comment by Cupax3** [comment]
This is even more broken and not what's advertised I didn't read the code properly gimme a minute

**Comment by Cupax3** [comment]
Review plox

**Comment by Jeff-jefferson-jeffery** [comment]
OOHRAH MARSOC XENOPHAGE

**Comment by Kaksisilma** [comment]
CI is failing.

**Comment by ProbablyCarl** [comment]
A reactionary PR(I think?) that provides a genuinely good change.
Props to ya. This'll be merged when you get the checks to stop having a stroke.

**Comment by Cupax3** [comment]
> A reactionary PR(I think?) that provides a genuinely good change.
Props to ya. This'll be merged when you get the checks to stop having a stroke.

no see I had @anconfuzedrock make a PR for me (#1415) so now I'm making one for them

**Comment by ProbablyCarl** [comment]
based

**Pull request merged**
