### PR TITLE
New Taser Rifle

### PR DESCRIPTION
**Pull request by RomanZC**
:cl: RomanZC
rscadd: Added the Stinger Stunrifle. Fires a lot of weak pellets and can self charge, instead of strong accurate beams. It's available on the traitor uplink for 50 telecrystals.
/:cl:

Some stats:
Changed: It takes 60 seconds to charge, so that its more viable purchase as a traitor item.
Armor penetration is 20
Agony is 4 (used to be 3)
Accurate = 2 (it was godawful and wouldnt hit shit when not pointblanking, even with experienced skill in firearms)
It fires in 3 round bursts, with a fire delay of 1 (lots of bollet)

Testing:

No armor:

With agony at 3 and disorientation at 5 = 
Pointblanked myself on the leg, toke 2 - 3 bursts to down me.
Pointblanked myself on the chest, toke 4 - 6 bursts to make me reel in pain and drop my items, also started the disorientation effect.

With armor (security voidsuit):

Pointblanked myself on the leg, toke me 3 bursts to down me.
Pointblanked myself on the chest, toke entire magazine to make my chest yellow.

**Conclusion, use this gun while aimming for weakspots and on unarmed personnel, the stun rifle / carbine on shock mode is much better than the Stinger at taking down armored people**

todolist:

- [ get good sprite ] 

- [ get good firing sound ] 

- [ balance it properly ]

### CODE REVIEW

**Comment by RomanZC** [comment]
also currently using placeholder sprite, because i cant sprite for shit. if this does get merged, i hope somebody who can actually sprites makes a neat one for this gun

**Comment by Roland410** [comment]
Pretty funny idea, but feels unnecessary, especially since it's adminspawn-only. The sprite stuff is also pretty meh.

**Comment by RomanZC** [comment]
I still didnt add it to the traitor uplink, doing testing :/

**Comment by RomanZC** [comment]
also why tf is travis failing, how does travis even work

**Comment by RomanZC** [comment]
made agony damage be 4 instead of 3, now it feels much more powerful while keeping the same amount of bursts to stun somebody

**Comment by BurgerLUA** [comment]
What is your operating system?

**Comment by RomanZC** [comment]
Win10

**Comment by BurgerLUA** [comment]
The issue with the editor needs to be fixed before this is merged.

**Comment by RomanZC** [comment]
How the fuck do you expect me to find the issue then? I never had this problem on github and I've checked all dreamseaker options.

**Comment by BurgerLUA** [comment]
https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by RomanZC** [comment]
Not gonna bother with this, I personally dont see the issue with this but okay.

**Pull request closed without merging**
