### PR TITLE
Legal PR: The second coming.

### PR DESCRIPTION
**Pull request by Sparrowbird611**
Literally PR https://github.com/BoHBranch/BoH-Bay/pull/791 but updated for current build.  Anything that applies to that PR applies to this. The only difference is I've left the locker fix on the APA locker out, which I'll do in a separate PR soon.

Also includes slightly expanded access, which was given to the SGR and now given to the Adjudicator in a previous PR.

Update. Credit to @Roland410 for all the work done in this section.

Adds a courtroom.
Adds a lawyer's office.
Adds the lawyer role, removes the lawyer alt title.
Fixes a lot of my shitcode.

Courtroom
image

Lawyer's office
image

### CODE REVIEW

**Comment by N8-Toe** [comment]
I'm still against this, but if it must go in I think their faction should be SCG. and not some ill defined "neutral" group.

**Comment by ProbablyCarl** [comment]
Memos and faxes still list the owner as SCGR.

Honestly, I think it'd be best if we just made this a separate entity from the SCGR entirely, rather than it replacing them.

**Comment by ProbablyCarl** [comment]
Office isn't even redone for it, lol.
Replace the bridge saferoom and expand it south/towards the SCGR office and boom, you've got a Bailiff and Adjudicator location.

**Comment by Sparrowbird611** [comment]
> Memos and faxes still list the owner as SCGR.
> Honestly, I think it'd be best if we just made this a separate entity from the SCGR entirely, rather than it replacing them.

I'll see about that. Will require some reworking, but I'll take a look.



> Office isn't even redone for it, lol.
> Replace the bridge saferoom and expand it south/towards the SCGR office and boom, you've got a Bailiff and Adjudicator location.

I planned to rework the office. Bailiff just shares that part, similar to the CL and APA.

**Comment by ProbablyCarl** [comment]
@Sparrowbird611 
Figured such. Just wanted to point it out just in case, as it's the first thing I noticed. Aside from the documents being the same.
Really though, I think there's potential for having the SCGR still present, for those that want it, and making this role/subrole its own separate thing with a genuine court room, which we can map as well.

**Comment by Sparrowbird611** [comment]
> @Sparrowbird611
> Figured such. Just wanted to point it out just in case, as it's the first thing I noticed. Aside from the documents being the same.
> Really though, I think there's potential for having the SCGR still present, for those that want it, and making this role/subrole its own separate thing with a genuine court room, which we can map as well.

The documents were an oversight, I had planned to make new ones but forgot about it.

I'll make a new version of this PR, do some mapping, and leave the SCGR alone this time. I can see it having potential, but in it's current state he doesn't really justify his existence IMO.

**Comment by alexpkeaton** [comment]
CL doesn't have access to his augmented tie.  Says "Unauthorized user, access denied."  Probably only gave access to the adjudicator and forgot the CL?

**Comment by alexpkeaton** [comment]
Also, CL does not have access to the "Trained" Exosuit operation skill, this would need to be adjusted if we're giving the CL a hardsuit with the augmented tie.

**Comment by Sparrowbird611** [comment]
> CL doesn't have access to his augmented tie.  Says "Unauthorized user, access denied."  Probably only gave access to the adjudicator and forgot the CL?

Frick I forgot to change that. Adjudicator probably can't access it either, given the tie used internal affair's access (Which no longer exists in general).



> Also, CL does not have access to the "Trained" Exosuit operation skill, this would need to be adjusted if we're giving the CL a hardsuit with the augmented tie.

I don't believe he needs exosuit operation to operate a RIG, only EVA. Exo suit operation I believe is only used in mechs, not rigs.

**Comment by Roland410** [comment]
I'm making some additions to this PR, as discussed on Discord, and fixing some bugs with it as well.

**Comment by Sparrowbird611** [comment]
I think most of the issues have been solved now. If we still want the SGR, I'll need to do a little work to make a new area for the Adjudicator and Bailiff, which I'll start on for now.

**Comment by Roland410** [comment]
I wouldn't bother with the SCGR personally. It can be coded again in the future if someone wants to bring it back, but right now it's pointless.

**Comment by ProbablyCarl** [comment]
Conflicts.

**Comment by BurgerLUA** [comment]
There seems to be a tonne of commits since approval. Is this still WIP?

**Comment by Sparrowbird611** [comment]
> There seems to be a tonne of commits since approval. Is this still WIP?

Still WIP, yes. I've been working on fixing the conflicts it had, which is done now, so I just need to see what travis is bitching about before this can be merged.

**Comment by BurgerLUA** [comment]
```## UNIT_TEST ##: [MAP: Station pipes shall not leak]: Following pipe is leaking: Scrubbers pipe (/obj/machinery/atmospherics/pipe/simple/hidden/scrubbers) ([0x200440e]) (the deck) (110,108,3) (/turf/simulated/floor/tiled/techfloor/grid)
## UNIT_TEST ##: [MAP: Station pipes shall not leak]: Following pipe is leaking: Scrubbers pipe (/obj/machinery/atmospherics/pipe/simple/hidden/scrubbers) ([0x2004533]) (the deck) (110,110,3) (/turf/simulated/floor/tiled/techfloor/grid)
## UNIT_TEST ##: !!! FAILURE !!! [MAP: Station pipes shall not leak]: 2 station pipes leak.

## UNIT_TEST ##: [AREA: Areas shall be coherent]: The Third Deck Safe Room (/area/crew_quarters/safe_room/thirddeck) ([0x400005a]) (62,87,3) is incoherent. Expected 1 subarea, fill gave 2. Origin turfs:
## UNIT_TEST ##: [AREA: Areas shall be coherent]: The reinforced plasteel bulkhead (/turf/simulated/wall/r_wall/prepainted) ([0x1017bed]) (62,87,3) (/area/crew_quarters/safe_room/thirddeck)
## UNIT_TEST ##: [AREA: Areas shall be coherent]: The deck (/turf/simulated/floor/tiled/techfloor) ([0x1018d4d]) (110,109,3) (/area/crew_quarters/safe_room/thirddeck)
## UNIT_TEST ##: !!! FAILURE !!! [AREA: Areas shall be coherent]: Found 1 incoherent area.```

**Comment by Sparrowbird611** [comment]
Yeah, those are the ones. I'll work on fixing those soon.

**Comment by Sparrowbird611** [comment]
was this conflict me or did something else get merged and I didn't notice? No matter, I'll fix it.

**Comment by Tristan63** [comment]
bailiff smack his nuts

**Pull request merged**
