### PR TITLE
Fleet polo & pants uniform additions

### PR DESCRIPTION
**Pull request by Ctr-Truescreen**
## About The Pull Request
Adds female sprites to the existing fleet polo uniform, fixing a bug where females rolling down their polo uniform got greeted with a null sprite.
Also adds all polo uniforms into the loadout, adds the fleet polo shirt itself into undershirt selection and adds an alternate fleet polo shirt into undershirt selection.

image
Left - Male polo uniform
Middle - Female polo uniform
Right - Polo uniform with alternate undershirt

## Why It's Good For The Game
Fixes a bug where females rolling down their fleet polo uniform causes the whole thing to break. Also, loadout, undershirt selection and alternate polo shirt.

## Did You Test It?
Tested on localhost. 

## Authorship
Superhats - Owner of #910 (Source of original Baystation 12 polo uniforms)
BurpleBineapple - Owner of https://github.com/Alanii/NewHestia/pull/266 (Source of white shirt polo)
Me - Edits to BurpleBineapple's white polo shirt

## Changelog

:cl: John_Bigless
imageadd - The fleet polo & pants uniform now has female sprites.
rscadd - Added fleet polo uniform selection to the loadout.
rscadd - Added fleet polo shirt to undershirt selection.
rscadd - Added an alternate fleet polo shirt to undershirt selection.
/:cl:

### CODE REVIEW

**Comment by Ctr-Truescreen** [comment]
TODO: Allow the fleet polo shirt to be tucked in/tucked out.

**Comment by BurpleBineapple** [comment]
I'm not a huge fan of how the shading on the white shirt looks. It's extremely flat. It needs more defined edges so that it doesn't all look like one white blob.

**Comment by Ctr-Truescreen** [comment]
> I'm not a huge fan of how the shading on the white shirt looks. It's extremely flat. It needs more defined edges so that it doesn't all look like one white blob.

image

I did some light editing after cross-examining with the loadout polo shirt. This time it's no longer a straight copy-paste, but i took my time to make the fleet polo darker than the NewHestia edition, but lighter than the loadout polo's. The fleet polo is also droopier (1 pixel below the pants waistline) than the NewHestia edition, but less droopier than the loadout polo's. (Yes, i know i forgot the departmental markings. It'll all be fixed, don't worry.)

**Comment by Ctr-Truescreen** [comment]
I'm done here. Awaiting a review and subsequent merge.

**Comment by Cupax3** [comment]
I'm not a huge fan of replacing things outright - could this be turned into an addition over a replacement?

**Comment by Ctr-Truescreen** [comment]
> I'm not a huge fan of replacing things outright - could this be turned into an addition over a replacement?

As said in the description, if you don't like the new polo, you can pick the alternate polo shirt and roll down the uniform.
I get that this is missing the point, but editing uniform vendor code is beyond my capabilities.

If you wanna make it so that both full fleet uniforms are available in uniform vendors + loadout after this is merged, be my guest.

EDIT: I won't be available next week for *reasons*, but i could add the fleet uniform as a seperate item and you could figure out making the right types appear in the vendor when i get around to it.

**Comment by Cupax3** [comment]
Also, could you check who sprited those uniforms?

**Comment by Ctr-Truescreen** [comment]
> Also, could you check who sprited those uniforms?

Authorship updated.

**Comment by Ctr-Truescreen** [comment]
This PR has been left horizontal for quite a while now. If nothing else is needed, then i suggest merging.

**Comment by Anton-Kr** [comment]
Ill take a look today. Ping me if I dont.

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
Apologies this took me that long to get to. 

Coupe of things:
- Not a fan of the whole selecting the department from loadout thing. I'd rather just keep the polo accessible from the uniform vendor only. 
- I think the default "look" should be with the shirt tucked in. I know it's minor, but with it being a uniform, it looks a bit silly untucked. I don't mind having that as a flavor mind you, but it's just kinda ehh
- This one is optional, but I am not a huge fan of the way "rolling down" the uniform works in just making the shirt disappear. Any chance you can sprite the shirt being actually I dunno, rolled down or otherwise visible in some way? Fine if not. Even better would be to make the shirt part an accessorie, but I don't think we support alternate accessory sprites so that's okay.

**Comment by Ctr-Truescreen** [comment]
> * Not a fan of the whole selecting the department from loadout thing. I'd rather just keep the polo accessible from the uniform vendor only.

The loadout part was one of the things i was most looking forward to, but i'll remove it if need be. I don't see a reason why the polo uniform shouldn't be the loadout, seeing as all the other uniforms are. I can make the departmental checks stricter and make sure that the wrong roles can't pick the wrong flavor of polo uniform.

> * I think the default "look" should be with the shirt tucked in. I know it's minor, but with it being a uniform, it looks a bit silly untucked. I don't mind having that as a flavor mind you, but it's just kinda ehh

I made it so that the uniform was untucked when putting it on for the first time, since, y'know. Shirt won't tuck in itself. Easy change, however, so i can definetly switch this around.

> * This one is optional, but I am not a huge fan of the way "rolling down" the uniform works in just making the shirt disappear. Any chance you can sprite the shirt being actually I dunno, rolled down or otherwise visible in some way? Fine if not. Even better would be to make the shirt part an accessorie, but I don't think we support alternate accessory sprites so that's okay.

The "rolling down" mechanic that a lot of people have been crying about being a "bug" is actually an intended feature, present in even the Baystation 12 fleet polo uniform. Rolling it down hides the shirt entirely so that it can be overlayed over an undershirt of the player's choosing (For example the old fleet polo shirt i moved into undershirt selection) or something completely different. Making it visible would ruin the ability to attach on other shirts, and would also probably look weird. (How do you roll down a non-jumpsuit shirt????)
Making it so that the fleet uniform is accessory-reliant would work for the loadout, but it would be the same as adding both fleet & polo uniform variations to the uniform vendor. Uniform vendor code is black magic to me and Cupax3 clearly doesn't seem to be interested in helping.

**Comment by Anton-Kr** [comment]
Two things,

Rolling up sleeves makes the uniform disappear altogether and seems to break it. 

Please rename the polos in loadout to polo, security; polo, exploration etc to keep them all in one place alphabetically.

**Comment by Ctr-Truescreen** [comment]
> Please rename the polos in loadout to polo, security; polo, exploration etc to keep them all in one place alphabetically.

Done. Looks better now.

> Rolling up sleeves makes the uniform disappear altogether and seems to break it.

I've double-checked all uniform states ingame and i haven't found any invisible sprites. Could you send an image, or even better, a video of you reproducing the bug?

**Comment by Anton-Kr** [comment]
In particular use case I used a female character spawning using a loadout security polo and rolled down the jumpsuit immidiately on round start. Rolling up sleeves causes the same issue. This does not appear to cause issues when the character is male.

**Comment by Ctr-Truescreen** [comment]
> In particular use case I used a female character spawning using a loadout security polo and rolled down the jumpsuit immidiately on round start. Rolling up sleeves causes the same issue. This does not appear to cause issues when the character is male.

It's most likely the fact that the polo uniform is genderless and i forgot to consider the female version when assigning the tucked-in variants. Whoops.

I'll look into this tommorow and decide if females also get unique sprites or if i just do more copy-pasting.

**Comment by Ctr-Truescreen** [comment]
Conflict with #1711 because of the political officer uniform. Fucking hell, nothing is simple.

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
