### PR TITLE
GAS job tweaks

### PR DESCRIPTION
**Pull request by Superhats**
GAS now have access to all the jobs lower grades can access, along with their usual stuff.

This means grade B GAS can be janitors, and grade A GAS can be janitors, bartenders, and chefs, along with their regular jobs.

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
Ehhhh….? Idk about this one, GAS are specialists, and I see little sense in allow "Le A+ janitor."

**Comment by ProfessorPopoff** [comment]
Yeah... Nah. This is pointless and kinda retarded chief. GAS are specialists, as the other lad said. The tier of the GAS is supposed to correlate with the tier of job they are able to specialize in. You wouldn't waste a perfect breed GAS that can cooperate with others perfectly on a fucking jantior. You'd get him fixing the ship and mixing chemicals. 

**Dare** I say, This PR is stupid?**

**Comment by Roland410** [comment]
I think the comments above summed up my opinion as well.

**Comment by Superhats** [comment]
Right. PR closed due to negative feedback.

**Pull request closed without merging**
