### PR TITLE
Re-Buff CO Revolver

### PR DESCRIPTION
**Pull request by ProbablyCarl**
Undoes the nerf that someone had applied prior.
This makes it an actual threat, once again, instead of something that can be walked off.

### CODE REVIEW

**Comment by chaoko99** [comment]
The CO does not need a validhunting gun.

**Comment by Sparrowbird611** [comment]
As the one who originally made the nerf, I feel I have to comment. The thing, even in it's current state, is hilariously strong for a pistol, with only 10 less damage than a slug, and the same AP. The stats you intent to give it in this PR are, put bluntly, absolutely insane. It would deal more damage than an AMR, and have AP higher than a dedicated combat weapon, ON TOP of also dealing direct agony damage.

The fact that he's the captain doesn't justify him having a pistol this busted. If they want the bridge to be difficult to raid, they should use the actual rifles in the bridge (There's like, three las carbines in there last I checked). As it stands, being hit by this thing in it's current state is no laughing matter, the stats you intent to return to it are horrific.

It's not really relevant if the ammo is exceptionally expensive, or the fact that there's only one of them. The gun doesn't deserve this much damage, AP, or direct agony damage.

**Comment by ProbablyCarl** [comment]
Ah, no.
You state it's great, but it's absolute garbage in its current state - unless my luck is just exceptional. 
I've had a case where Decker, as a Space Ninja, point blanked me to the head in an attempt to execute me, and it did so little damage that I've walked it off.

It's nowhere near as good as you're painting it. Go ahead and attempt to use it as a self defense weapon in its current state against mercs or Vlad Hunt.

**Comment by Dark1Star3s** [comment]
Hi, it's me Cookie. While on the topic that this does more damage than the AMR, then perhaps we should consider buffing the AMR? Considering such weapoin is an "Anti-Material-Rifle" which is usually reserved for blowing big holes in engine blocks of light armored vehicles, or destroyng a helicopters engine. Then perhaps we should consider buffing the AMR?

Back on topic to the .454. The .454 is a REALLY big round, and 50 damage is actually... really poor compared to some of the other weapons in this game. IIRC a 4mm bullet does... 26 damage? The Holdout Pistol IIRC does 40. (which is a bit much for a  7mm) anyways, the captains pistol should be a very deadly wepaon, and should only be used in self defence purposes, and the captain shouldn't be going around, out of his way to hunt antags. The low AP power on this pistol with the buff, will still lower the damage by a lot, against anyone wearing any decent amount of ballistic protection.

**Comment by CrackParrot11** [comment]
I do not really see the issue if giving the CO a powerful weapon. Its only a single weapon compared to the already powerful shotguns and laser carbines alread in security hands.

**Comment by ProbablyCarl** [comment]
We also already treat Command to a higher standard, and have recently started Command banning players who don't meet that standard. If the concern is someone being a shitter with the firearm, then they're already probably going to be Command banned.

**Comment by Sparrowbird611** [comment]
Alright, first off.

Buffing the AMRs damage. This is what we got out of this? Guns as it is do absurd levels of damage, with the AMR dealing 70 per shot, along with all it's special bonuses to shooting. It does not need more.

You say 50 damage isn't great, but that's the average for rifle tier weaponry. The pistol has AP on par with the shotgun, a very common pick amongst security officers as their primary weapon, and damage that can overpower freaking rifles. The average rifle does 45 damage per shot, the shotgun slug does 60. 50 damage is an exceptional amount of damage on a hand gun. And low AP my ass, it's shotgun tier AP, that's enough to penetrate your average armor.

While it's nice to hear command will be held to higher standards, that's not justification for this weapon to be this powerful. And as for your example carl, ngl, I call bad luck or something. You'd have to state the scenario with all the factors, but the gun is literally the highest grade of pistol available.

**Comment by ProbablyCarl** [comment]
No. It's not.
Here's holdout:
`/obj/item/projectile/bullet/pistol/holdout
	damage = 40
	shrapnel_chance_multiplier = 1.2
	arterial_bleed_chance_multiplier = 1.2
	distance_falloff = 4`

Now here's the 15mm revolver:
`
/obj/item/projectile/bullet/pistol/strong
    fire_sound = 'sound/weapons/gunshot/gunshot_strong.ogg'
    damage = 50
    shrapnel_chance_multiplier = 0.8
    arterial_bleed_chance_multiplier = 0.8
    distance_falloff = 2.5
    armor_penetration = 15`

Finally, here's the LL round that the HoS gets:
`
/obj/item/projectile/bullet/pistol/strong/rubber
    damage = 10
    armor_penetration = 5
    agony = 45
`


Now, to compare to rifles. Here's the AT Rifle:
`
/obj/item/projectile/bullet/rifle/shell
	fire_sound = 'sound/weapons/gunshot/sniper.ogg'
	damage = 80
	stun = 3
	weaken = 3
	penetrating = 3
	armor_penetration = 70
	shrapnel_chance_multiplier = 1.2
	arterial_bleed_chance_multiplier = 1.2
	distance_falloff = 0.5
`
Here's the APDS round of the AT Rifle:
`/obj/item/projectile/bullet/rifle/shell/apds
	damage = 70
	penetrating = 5
	armor_penetration = 80
	shrapnel_chance_multiplier = 1.5
	arterial_bleed_chance_multiplier = 1.5
`


Now, lets compare those two to military bullpups:
`
/obj/item/projectile/bullet/rifle/military
	fire_sound = 'sound/weapons/gunshot/gunshot2.ogg'
	damage = 40
	armor_penetration = 35
	shrapnel_chance_multiplier = 1
	arterial_bleed_chance_multiplier = 1
`

**Comment by Dark1Star3s** [comment]
Again, yeah, of course it's going to do much more damage than a rifle, it's a MUCH bigger round, not just that, but it's going to have WAY less AP because it travels MUCH slower than a regualr rifle round. The balance of the pistol, is the fact that if it comes up against any reasonable armor, it's useless.

**Comment by Sparrowbird611** [comment]
I'm not really seeing your point bringing all those stats up. They all just confirm what I've said. The gun has more AP and damage than any other pistol save like, one or two, deals more direct damage than your average rifle, and will deal more damage than the AMR if you buff it.

**Comment by ProbablyCarl** [comment]
You've not even looked at the stats, if you think it'll compare to an AMR, lol.
Against an unarmored target, yeah. Against literally anyone else? No.

**Comment by Sparrowbird611** [comment]
I never said it would have more AP than the AMR, only damage. Tell me this, why does the gun need to do more damage than it already does? It already can two shot unarmored, and it has incredibly high AP for a pistol. You're pushing for an AP buff and a damage buff on a weapon that's incredibly respectable on both stats.

Your example of surviving the gun makes me skeptical tbh carl, and I can't judge that unless you tell me what you were using. Either way though, it's a hand gun with fantastic stats as is, it doesn't need them to be higher. Just because you're the captain doesn't mean you need a hand cannon. You've got three laser carbines in the bridge lockers, use those if you need a stronger primary weapon.

**Comment by ProbablyCarl** [comment]
I wasn't using anything.
I was bald headed, in maint running from a Ninja. He cornered me, managed to disarm my gun, and point blank shot me in the head. It could've been incredibly shoddy luck on his part, sure, but I've used the revolver myself in other instances including against boarders hunting me, and it's lackluster at best.

**Comment by Sparrowbird611** [comment]
Ok that's...…. I really need to call bad luck on that if you survived. I blame combat RNG more than this gun's stats in that case, since even if he had pulled a combat shotgun, you would have likely survived that.

What kind of boarders, and why are you trying to use a pistol to fight off heavy duty boarders carl? It's a pistol, it's not supposed to be the end all be all, primary weapon destroyer of foes. If you want that, you need a rifle. If these stats were on some kind of heavy duty rifle given to the CO, I'd be fine ~~even though the man doesn't need a rifle,~~ but this is a pistol. It doesn't need stats this heavy duty, and I doubt giving it these stats would have changed anything if combat RNG said "You will survive this day."

**Comment by Dark1Star3s** [comment]
Again, the thing a rifle has over a pistol, realisticly speaking, is accuracy, range and muzzle velocity. Thing with a huge pistol like this, the rounds are slow, heavy and there's no way in hell they're going to pierce any decent set of armor plates. Armor is all about speed, not power, though both can help in certain circumstances.

"It's a pistol, it's not supposed to be the end all be all, primary weapon destroyer of foes. If you want that, you need a rifle."
It's not no, however what it IS, is a revolver, with a huge calibre compared to rifles. Why not give the armory .454s instead of shotguns, or SMGs? Well, a revolver like that is going to have a HUGE amount of recoil, which also means that the fire-rate is going to drop significantly, and on top of that, the accuracy with it... it's questionable.

Besides, an antag shouldn't be scared of this weapon with this buff, if they're wearing armor, and if any antag is coming up against such a weapon, armed then it's to be expected that he is wearing armor, no antag with a brain is going to take over the bridge with nothing but a shotgun and the clothes on his back.

**Comment by Sparrowbird611** [comment]
I don't mean to be rude or anything when I say this, but I don't particularly care how bullets work realistically. If I cared about realism, I wouldn't have been against the headshot stun, or any of those mechanics.

I don't know why we would give the armory .454s to be honest. We already have the SMGs as well. In it's current state, it's a slight downgrade to a shotgun. If this buff to were go through, it'd be a full on upgrade, and I'd rather not see security carrying these in that hypothetical situation.

As for "Antags not being scared of this weapon with this buff, so long as they wear armor" you miss two points. The first one being that this PR buffs it's AP, meaning that even fewer forms of armor will effectively stop this gun, on top of the massive damage buff it receives. Secondly, this PR re adds it's agony damage, which, (please, correct me if I'm wrong, because I'm only like 75% sure on this) last I checked, agony damage goes through armor, so you now also need to stack pain killers on top of armor to survive this gun.

It's an unnecessary buff in general. The captain has a gun that overpowers many weapons within it's class, as well as several outside of it. His gun is one of the best picks out there, it doesn't need more power slapped on to it.

**Comment by AdamElTablawy** [comment]
@Dark1Star3s 

Realism has never and will never matter. Balance does.

**Comment by bearrrrrrrr** [comment]
mi think pistol is ok as-is :)

**Comment by Tename** [comment]
Last time I faced up against the cos gun he rushed up next to me during a fight and instantly knocked me down and crited me with one shot. Is this going to be the same as before?

**Comment by Dark1Star3s** [comment]
No because stuff like that you A-Help. The captain should only use the revolver in self defence, and if he rushes at you and shoots you, then you A-Help it.

**Comment by Tename** [comment]
I was fine with the way it was used, but I just wanted to know if it is still that powerful.

**Comment by chaoko99** [comment]
That does a fat load of good when it's marked as an IC issue or you're already dead.

**Pull request merged**
