### PR TITLE
Diona can now be Detectives

### PR DESCRIPTION
**Pull request by Sparrowbird611**
Top text. Literally just enables the forensic technician job for diona.

Because I thought it would be fun to let all two diona players be detectives.

🆑
Tweak: Diona can now be forensic Technicians.
/🆑

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
Reeee travis sucks.

**Comment by bearrrrrrrr** [comment]
> tfw the diona in-universe metacomms with rootspeak to ask the plant gang where the cult is

**Comment by Jeff-Dome** [comment]
ey fellow sun eating people, where the vailds at?

**Comment by Sparrowbird611** [comment]
,q All diona...… form up at the mess hall....... there's a criminal in there......

**Pull request merged**
