### PR TITLE
Viewcones

### PR DESCRIPTION
**Pull request by ProbablyCarl**
Pulls viewcones from: https://github.com/Baystation12/Baystation12/pull/21764

That's about it. Tested it and it functions. Thought it'd be worth tossing it up as a PR to gauge reactions.

Viewcones are as they were on the PR mentioned. They only hide mobs.
image

### CODE REVIEW

**Comment by InfinitelyThinRectangles** [comment]
horror2


_Please no._

SS13 combat is already super duper melee centric due to how short the view distance is and bay-madness regarding the chances of actually hitting, and then more bay-madness meaning that actually putting someone on the floor during a fight rather than 15 minutes of medbays wild ride later requires enough shooting to down a B-17.

If you make sneaking up behind someone with high CQC super good by mechanically preventing anyone from seeing you until they're already in range to grab then syringe-click, the Sam Fisher shit is gonna become so overpoweringly dominant that anything else is obsolete, I fear. :(

**Comment by Plaguewalker** [comment]
> horror2
> 
> _Please no._
> 
> SS13 combat is already super duper melee centric due to how short the view distance is and bay-madness regarding the chances of actually hitting, and then more bay-madness meaning that actually putting someone on the floor during a fight rather than 15 minutes of medbays wild ride later requires enough shooting to down a B-17.
> 
> If you make sneaking up behind someone with high CQC super good by mechanically preventing anyone from seeing you until they're already in range to grab then syringe-click, the Sam Fisher shit is gonna become so overpoweringly dominant that anything else is obsolete, I fear. :(

It'll kill a good chunk of players from enjoying the server aside from the TDM sweats

**Comment by anconfuzedrock** [comment]
Alternatively you could turn around. Or face your back to a wall. I think it's worth a testmerge at least.

**Comment by InfinitelyThinRectangles** [comment]
> Alternatively you could turn around. Or face your back to a wall. I think it's worth a testmerge at least.


I, too, have an amazing sixth sense that just _activates_ when someone's about to attack me. Oh, no, no I don't, that's called metacomming or living in Croydon, neither of which I do.

The only people this benefits are on-ship murderbone antags.

**Comment by Pariah919** [comment]
I'm probably very, very biased here but, personally I enjoy vision cones as a mechanic for a few reasons-

1. They add to the overall feel of SS13, in my personal opinion. I honestly think its natural once you get used to it but eh, heavily biased.
2. They add a higher tension to combat and proper movement.
3. They make people face each other properly.

Vision cones aren't TOO bad once you get used to them, but I don't know if we have noise pings like Matt.
Also you're gonna have to make face direction a thing if you want this to work at all.

**Comment by Jeff-jefferson-jeffery** [comment]
How do they only benefit "murderbone on ship antags". They let you actually sneak past people. You're acting like every single round has supergod solid snake ripping their way through the crew. Vision cones are an interesting idea and we should try them.

**Comment by InfinitelyThinRectangles** [comment]
> How do they only benefit "murderbone on ship antags". They let you actually sneak past people. You're acting like every single round has supergod solid snake ripping their way through the crew. Vision cones are an interesting idea and we should try them.

I do not feel the need to extrapolate on why something that makes it much easier to bypass and assassinate ship crew is a boon to people who are hostile to shipcrew, it is self evident.

And no, I'm not "acting like it", I'm worried that's what's going to happen and further encourage the unimaginative murderbone we still get from time to time.

**Comment by Plaguewalker** [comment]
> > How do they only benefit "murderbone on ship antags". They let you actually sneak past people. You're acting like every single round has supergod solid snake ripping their way through the crew. Vision cones are an interesting idea and we should try them.
> 
> I do not feel the need to extrapolate on why something that makes it much easier to bypass and assassinate ship crew is a boon to people who are hostile to shipcrew, it is self evident.
> 
> And no, I'm not "acting like it", I'm worried that's what's going to happen and further encourage the unimaginative murderbone we still get from time to time.

You mean the usual Jefferson special

**Comment by Rafflesia7793** [comment]
> Vision cones aren't TOO bad once you get used to them, but I don't know if we have noise pings like Matt. Also you're gonna have to make face direction a thing if you want this to work at all.

Face direction is already a thing. Alt+Direction to face, Alt+the direction you are already facing in to stop.

**Comment by ShadeAware** [comment]
Absolutely awful; SS13 has never been and is not meant to have vision cones, and Hestia sure as hell isn't. I can't think of anyone who actually wants this beyond antag mains and fraggers; limiting vision with an ugly fog-of-war effect better seen in something like Project Zomboid that serves no purpose here other than making the simple act of _seeing things_ a miserable and janky experience.

**Comment by Yurek1** [comment]
great in concept, bad in application
unless you want to add footstep notifiers, rework sound design, add new sounds, make footsteps louder, and generally rework the entire audio system for the whole server?
no thanks
if you want to do all of those things first? absolutely, but otherwise, this is a bad idea- works for some servers like soj/eris with their different soundscape, but ours is barebone as it is

**Comment by ShadeAware** [comment]
image

**Comment by Rafflesia7793** [comment]
Seems like a really, really good candidate for a 2-3 round testmerge so people can try it out and see how they feel.

**Comment by anconfuzedrock** [comment]
> Seems like a really, really good candidate for a 2-3 round testmerge so people can try it out and see how they feel.

or maybe 2-3 day.

**Comment by ShadeAware** [comment]
> > Seems like a really, really good candidate for a 2-3 round testmerge so people can try it out and see how they feel.
> 
> or maybe 2-3 day.

**God** no.

**Comment by ProbablyCarl** [comment]
We'll be test merging this for a short period. Feedback during this time will be invaluable, so feel free to shout on this PR about it still.

**Comment by BurpleBineapple** [comment]
So, feedback from the testmerge from me.

- There's a lack of indicator for people even sprinting directly behind you. Having icons pop up beside you or speeding out from behind you is a little strange.

- Personally, they're a little disorienting when in casual settings. Trying to reposition my character without locking direction first will inevitably make other people disappear when I turn. It feels more like a child that hasn't developed object permanence than field of view.

- View cones allow you to see icons like people typing, which may or may not be intentional?

Personally, I don't like them. They make it more disorienting to move around in a casual setting. Honestly they're only cool for combat.

**Comment by MichaelMaCleod007** [comment]
Ok so I was using binoculars and had the cone of blindness show up when using to look in front of me. Not cool.

**Comment by Rafflesia7793** [comment]
I liked them. It made me feel more immersed. My character cannot see behind theirself, so why should I? The choice for a 270 degree viewcone rather than something smaller like 180, I think was a good choice. It is a nice middle ground. In casual gameplay it shouldn't feel too restrictive.

**Comment by SilverCelestine** [comment]
It appears I've been requested to comment on this.

I like it as a concept, however there is a lot more supporting element that'll be necessary to make this fully viable. Some kind of indicator as to where sound is coming from outside of your vision, a gradual fade of mobs at the corner of your vision instead of just outright disappearing. Probably a proper UI button to lock your view for the people who can't figure out hotkeys.. aaaand lastly, I feel as if shoving should shove you back, but not outright 180 your direction of facing.

**Pull request closed without merging**
