### PR TITLE
Nerfs swords, buffs machetes

### PR DESCRIPTION
**Pull request by Anton-Kr**
The swords were overwhelming for the amount of force they were given for essentially free. They shouldn't be an outright upgrade to machetes. This nerfs them to a more appropriate (but still useful) force, and gives machetes the game intended (unless I am reading code wrong) force.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
note the other advantages of sword, most notably having a rare 10 melee accuracy bonus.

**Comment by InfinitelyThinRectangles** [comment]
Just a thought, but when I wanted to make swords easier to carry and fit in bags like machetes can, I was told that part of the reason it was okay that they're difficult to wear was how powerful they are. If they're no longer going to be so strong, I'd be really appreciative if they could fit into bags like the very machete they're now functionally a reskin of, since the entire reason they could not has fallen away.

**Comment by Anton-Kr** [comment]
@InfinitelyThinRectangles they are still at the strength of pathfinder's machete, with an accuracy bonus. The expense here is obtainability and inventory clunkyness.

**Comment by anconfuzedrock** [comment]
that and +10 armor penetration on the sword.

**Comment by ProbablyCarl** [comment]
Good to merge?

**Pull request merged**
