### PR TITLE
[Ready For Review] Medi remap

### PR DESCRIPTION
**Pull request by Tename**
This is a remap of the center areas of medbay(Treatment Center, Morgue, Recovery, Resleeving, Autopsy, OR rooms, and more.) the main goal is to make medbay easier to organize during overflow times. Another goal I had was also to make the morgue and autopsy lab fully stocked to remove laces and prep corpses for resleeving, this should reduce the load on the other two OR rooms if managed properly. 

Feedback welcomed, while I am done drafting I still am willing to consider major changes based on feedback. Pictures can be viewed by clicking checks and then Mapdiffbot.

## Changelog
:cl:
add: Surgical Spray bottle 50/50 mix of sterilizer and space cleaner
add: Weak Medical Lollipop box
Fix: Missing camera in the bridge from my last PR
del: Escape pod 9
tweak: Medical Wardrobe spawns with nurse hats and dresses
tweak: Plastic an aluminum now spawns next to the medical auto lathe
tweak: Treatment center renamed to Trauma Center
imageadd: Triage Sprites
imageadd: Reversed loading decal (Not used)
map: Back areas of medical completely rebuilt
map: Aux Medical Storage moved next to OR rooms
map: Old Aux Medical Storage replaced with a medical EVA room.
map: New Triage drop-off room
map:  Extra recovery room
map: Morgue is now fully stocked to remove laces and process bodies
map: Morgue spawns with a shipping closet to send items back to their departments.
map: Escape pod 8 moved behind Briefing room
map: Medical equipment area mostly untouched, say for a new uniform vendor
map: Slightly less morgue trays than the old design, but more space to move
map: Many maint changes around medical
map: Treatment center reworked for better organization during overflow times
/:cl:

((Drafted to check Travis as I work))

### CODE REVIEW

**Comment by Roland410** [comment]
After talking about it in Discord, this looks pretty good, just needs minor changes etc.
Really would like to maintain the maintenance continuity though.

**Comment by Tename** [comment]
I can look into that in the morning, incase I have to, would a staircase under and up again do?

**Comment by chaoko99** [comment]
image
bad pipes. Also no airlocks where there really should be airlocks. Also missing firelocks.

**Comment by Tename** [comment]
> 
> 
> image
> bad pipes. Also no airlocks where there really should be airlocks. Also missing firelocks.

I am aware, I don't put certain airlocks in till I am done because they get in the way, please look at the checklist.

**Comment by Tename** [comment]
Taking a small break from this, will be back to it in two days.

**Comment by chaoko99** [comment]
image
None of these disposal bins appear to be connected to the pipeline. Don't forget about trunks.

**Comment by Tename** [comment]
> 
> 
> image
> None of these disposal bins appear to be connected to the pipeline. Don't forget about trunks.

Ah, it looks like I forgot about that or they arent loading in on map bot, will check tomorrow

**Comment by Tename** [comment]
Alright, fixing up the pipes and starting to finish this up. I am also going to remove one of the OR rooms and replace it with something else, I feel 3 is a bit too much now that the morgue is fully fitted to remove laces.

**Comment by Roland410** [comment]
You have committed a backup map.

**Comment by Tename** [comment]
> 
> 
> You have committed a backup map.

Fixed, thanks, not sure how that happened.

**Comment by Tename** [comment]
Think I got everything, this is ready for review now, tell me if I missed anything and I will fix it when I have a chance.

**Comment by Roland410** [comment]
Needs pictures and squashing would be good as well (unless Burger wants to do it for you).

**Comment by Roland410** [comment]
Also if you haven't done so, please make sure that the equipment/locker room doesn't use virology access anymore, as that's unused, and needs to be removed from the jobs' access list as well.

**Comment by Tename** [comment]
> 
> 
> Also if you haven't done so, please make sure that the equipment/locker room doesn't use virology access anymore, as that's unused, and needs to be removed from the jobs' access list as well.

I have all my doors set to autoset on whats defined for the area, I tested it all though to make sure its working out. Since mapbot isnt working I'll get some in a moment.

**Comment by Roland410** [comment]
I know it will work for medical, but iirc the area for the lockers uses virology access still, which should have been purged a while ago.

**Comment by Tename** [comment]
> 
> 
> I know it will work for medical, but iirc the area for the lockers uses virology access still, which should have been purged a while ago.
I'll check it in a moment
Center 
Image
Center full bright
Image
Morgue
Image
Morgue full bright
Image
Lower full bright
Image

**Comment by Tename** [comment]
> 
> 
> I know it will work for medical, but iirc the area for the lockers uses virology access still, which should have been purged a while ago.

Locker access is "access_medical_equip"

**Comment by Roland410** [comment]
Is that for the zone itself as well?
Also, the shutters should probably start open on the left, so EMTs can get people to treatment ASAP.
Not sure where the crates that were on the lower level went (or their contents at least), but afaik chemists used that for stuff like dex+ and to speed up the making of other chems.

**Comment by Roland410** [comment]
Additionally, I'd remove the ETC->cryo door, and put them below to the recovery room and the entrance->lockers hallway.

**Comment by Sparrowbird611** [comment]
Looks cool for the most part, not sure I really like how you removed the maintenance doors though.

**Comment by BurgerLUA** [comment]
Needs to be testmerged for feedback.

**Comment by Tename** [comment]
Could I get pinged on discord when it is?

**Comment by bearrrrrrrr** [comment]
MED REMAP PART 4: THE MAPPENING

**Comment by Tename** [comment]
Conflicts are from the engineering remap, I can't resolve them as I am without an internet connection until my new router comes in the mail.

**Comment by Tename** [comment]
I am at the hit random buttons until it works stage.

**Comment by Tename** [comment]
Oh my fucking god I am making a new fucking branch holy fucking shit kill me

**Comment by Tename** [comment]
New PR: https://github.com/BoHBranch/BoH-Bay/pull/924

**Pull request closed without merging**
