### PR TITLE
Adds Boron & Supply Stuff

### PR DESCRIPTION
**Pull request by Kaksisilma**
- Adds Boron Cartridges & Boron reaction, though I took liberty in nerfing it a little bit.
- Fixes Uranium typo (nuranium)
- Reduces excessive number of empty blood bags from the blood packs refills
- Adds an extra Auto-Compressor to the auto-compressor refiller
- Re-adds laser weapons to supply. Adds pulse weapons & an orderable L6 SAW at competitive prices. Willing to re-adjust their cost if requested.

### CODE REVIEW

**Comment by ProbablyCarl** [comment]
oh god oh fuck

L6 I think is broken still. Might want to check it.

Looks fine otherwise.

**Comment by Vizoplez** [comment]
l6 saws are broken but yes, its just a mag issue. They cant take the large boxes of 7.5 or they lose their sprite.

Still takes large mags fine though.

**Comment by ProbablyCarl** [comment]
> l6 saws are broken but yes, its just a mag issue. They cant take the large boxes of 7.5 or they lose their sprite.
> 
> Still takes large mags fine though.

Would be worth not allowing it to take boxes until it's fixed then, I'd think.

**Comment by InfinitelyThinRectangles** [comment]
Wasn't there a big deal in the discord relatively recently about not allowing boron through cargo because it was OP as hell with regards to the SM? I'm pretty sure that hasn't changed?

**Comment by Kaksisilma** [comment]
> Wasn't there a big deal in the discord relatively recently about not allowing boron through cargo because it was OP as hell with regards to the SM? I'm pretty sure that hasn't changed?
Capture




> l6 saws are broken but yes, its just a mag issue. They cant take the large boxes of 7.5 or they lose their sprite.
> 
> Still takes large mags fine though.

Going to look into it and change this pr to a draft in the meantime.

**Comment by miniusAreas** [comment]
> Wasn't there a big deal in the discord relatively recently about not allowing boron through cargo because it was OP as hell with regards to the SM? I'm pretty sure that hasn't changed?

Boron was OP not in the SM, but in the RUST. At the same time, it's funny and requires both departments cooperation to aquire.

**Comment by Kaksisilma** [comment]
Ok going to merge this. If any concerns pop up we can revert it or do upgrades.

**Pull request merged**
