### PR TITLE
Nanites can no longer be produced 

### PR DESCRIPTION
**Pull request by Jackofashepard**
Title. Honestly was hoping my other PR would be preferable but here it is.

### CODE REVIEW

**Comment by SouthyOsmanli** [comment]
Yeah, sadly nanites are incredibly overpowered currently and need a heavy rework done on them. Disabling them from production until someone wishes to do that said heavy rework is prefable.

**Comment by Roland410** [comment]
Literally use big brain and shoot a burst at it once. The charge time is 5 minutes for 1 shot blocked.

**Comment by Sparrowbird611** [comment]
While that is accurate roland, it still basically cucks any one not using an AR. Stealth traitor trying to run away by disabling you? Nanomachines son. Nanites essentially ruin everything short of an auto pistol, e sword, or AR, so I can't support their existence in good faith.

**Comment by BurgerLUA** [comment]
I'll give this another week for more feedback.

**Comment by BurgerLUA** [comment]
Okay I'm being told that these should be removed with the balance concerns. Hopefully they can be re-added in the future with a nerf.

**Pull request merged**
