### PR TITLE
allows plasmemes to wear most things humans can wear + plasmaman backup tank fix

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

allows plasmemes to wear most things humans can wear

## Why It's Good For The Game

they get basically 0 suit variety and are already dogshit as it is

this makes no sense lorewise either as they're proportionally still 'human'

## Did You Test It?

yes, works 100%

## Changelog

:cl:
balance: plasmemes can into human clothes
fix: plasmeme backup tanks
/:cl:

### CODE REVIEW

**Comment by Plaguewalker** [comment]
The main question I have is, how does this impact plasma men and their suit mechanics? Does it prevent them from catching flames if they wear the rig in place of their suit or does the rig go over their suit and helmet akin the hard suit boots?

**Comment by Cupax3** [comment]
Please test it

**Comment by lolman360** [comment]
> The main question I have is, how does this impact plasma men and their suit mechanics? Does it prevent them from catching flames if they wear the rig in place of their suit or does the rig go over their suit and helmet akin the hard suit boots?

plasmamen in unsealed suits burn. plasmamen in sealed suits don't burn. changing suits in an oxygen atmosphere will fuck you, so use a shower + meds or get an oxygen-free room to change in

**Comment by lolman360** [comment]
@cupax3 done

**Review by Cupax3 — APPROVED** [review]
Looks good, probably works

**Pull request merged**
