### PR TITLE
xenobio buffs/changes

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

slimes can now be held in your hands (d'aw)

pink extracts no longer make a shitty docility potion, now they can generate small quantities of useful medicine reagents- ghetto kompoton, ghetto hypeross, and a bleeding-reduction/artery-closing reagent.

adds slime mutators and slime stabilizers, which increase and decrease mutation rate respectively.

## Why It's Good For The Game

xenobio fucking SUCKS, moving slimes is a chore because they cant' even be grabbed so now you can hold them.

there's really nothing interesting barring yellow slime cells, steel/plasteel and phoron.

medicine reagents improves utility, makes medical/science interactions more important other than just IMS since these reagents are consumable and unobtainable otherwise.

## Did You Test It?
yes, works fine

## Changelog

:cl:
rscadd: ghetto hypeross, kompoton and a new bleeding-healing reagent to pink slimes, pink slime docility is now made via sugar
rscadd: you can pick up slimes now 
rscadd: slime mutators, stabilizers
fix: yellow slime cores are no longer worthless
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
Can you modify your changes in a way that keeps the existing reactions? The additions sound cool and good, but no reason to straight up remove the old stuff imo.

**Comment by lolman360** [comment]
@Cupax3 done

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
Looks fine to me now.

**Review by BurpleBineapple — APPROVED** [review]
haha funny wrong button. Approved properly.

**Review by SilverCelestine — APPROVED** [review]
So far it looks fine to me as well, I don't really have any objections.

**Pull request merged**
