### PR TITLE
Yaya

### PR DESCRIPTION
**Pull request by Armyguy**
Sergs no run times all tested fuck Travis

### CODE REVIEW

**Comment by Snownbloodyflowers** [comment]
https://api.travis-ci.com/v3/job/261176029/log.txt
 Please fix the error with culture tags being incorrect.

**Comment by Armyguy** [comment]
> https://api.travis-ci.com/v3/job/261176029/log.txt
> Please fix the error with culture tags being incorrect.

When you tell me what the fuck its "Valid Types And Length" is

**Comment by Armyguy** [comment]
I see what it is the fix i was ABOUT to pr when you fucked it all had the "Valid Types And Length" fixed.
When i had to refork to unfuck this they got unticked in the compile

**Comment by Armyguy** [comment]
There if it STILL "Valid Types And Length"'s its all on Travis

**Comment by Snownbloodyflowers** [comment]
The logical thing to do when you see a errors is to revert to when you have no errors. Please don't take it personally as I am still trying to familiarize with the code. 

I see no errors right now but I'm re-running travis. Should be A-okay if it doesn't cause any runtimes/ Culture valid types and lengths errors again.

**Comment by Snownbloodyflowers** [comment]
3 incorrect indentations (expecting exactly 0)
You have 2 incorrect indentations. In otherwords, check your spacing.

**Comment by Armyguy** [comment]
SERGS POSTING TIMES

**Pull request merged**
