### PR TITLE
Makes Loadout Guns LTL

### PR DESCRIPTION
**Pull request by AMcilraith**
## About The Pull Request
This makes loadout guns Less Than Lethal, by making them use pepperballs.
## Why It's Good For The Game
Random people can no longer play the roles of infantry/sec, therefore cutting down on all around validhunting. Lethals can still be requested from the SECARM, at the brig chief's discretion. As it should be.
## Did You Test It?
Yes.
## Authorship
Dr. Farson
dudeman100
## Changelog

:cl: AMcIlraith
tweak: changes loadout guns to LTL
/:cl:

### CODE REVIEW

**Comment by Yurek1** [comment]
I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason. Also, pepperballs barely work on _unarmored_ targets. All this will do is make sidearm guns worthless.

**Comment by Rafflesia7793** [comment]
> I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.

Cargo, engineering, security, and science can provide you with additional ammunition from their lathes.

**Comment by AMcilraith** [comment]
> I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.

This is literally the job of sec/infantry. Not the job of explorers. Additionally, self-defence on a ship should not require lethal shots, again, exploration has a locker full of guns on the gaunt that the pilot/pf can unlock.

**Comment by Yurek1** [comment]
> > I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.
> 
> This is literally the job of sec/infantry. Not the job of explorers.

So if someone charges explorers with an automatic rifle, they're expected to lay down and die or run away? They're part of the military. The entire ship is military.

**Comment by Yurek1** [comment]
> > I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.
> 
> Cargo, engineering, security, and science can provide you with additional ammunition from their lathes.

You've clearly never played skeleton shift secret, where there's nobody in any of those departments, and command has their heads up their asses or isn't there to begin with.

**Comment by AMcilraith** [comment]
> > > I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.
> > 
> > 
> > This is literally the job of sec/infantry. Not the job of explorers.
> 
> So if someone charges explorers with an automatic rifle, they're expected to lay down and die or run away? They're part of the military. The entire ship is military.

In the REAL military, you have to check out your guns, sign paperwork saying you won't abuse your gun, requisition your gun , requisition your ammo, and sign papers every time you fire your gun. Would you prefer I replaced the guns with requisition forms so it can be more realistic?

**Comment by Yurek1** [comment]
> 

If that's the case, let's codelock security's guns too, so they can't fire on green, like infantry's. That'll help validhunting, and make it more scifi-realistic, won't it? (Spoiler: No, it won't.)

**Comment by AMcilraith** [comment]
> > 
> 
> If that's the case, let's codelock security's guns too, so they can't fire on green, like infantry's. That'll help validhunting, and make it more scifi-realistic, won't it? (Spoiler: No, it won't.)

Security is already codelocked, they require auths for lethals for the compacts.

**Comment by Pariah919** [comment]
>I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason. Also, pepperballs barely work on unarmored targets. All this will do is make sidearm guns worthless.
>
I'm going to go step by step, since I'm in a rant mode for some reason.

>Each gun is only issued one magazine
>
1 magazine? One magazine is enough to shoot someone and run away, the brig chief is around for a reason in my opinion. Though.

>and LTLs are generally accepted as being completely worthless against anything but unarmored targets
>
LTLs are fine against most threats you want to take out in self defense, in my opinion. You're still a threat to most unprepped antag players and anyone normal who isn't wearing any type of heavy armor.
Pepperballs are fine.

>If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason. 
>

Brig chief is around for a reason IMO. I think people should run to him for ammo in most scenarios, or go to the emergency armory. The emergency armory bloody sucks, though. Probably needs a buff.

>Also, pepperballs barely work on unarmored targets. All this will do is make sidearm guns worthless.
>
why are you running up to armored targets with assault rifles with your sidearm in the first place, though? I understand this is a poor argument, but.. Try running, ASAP. Run speed is so fast you can run fast enough to get away from most threats that aren't targeting you in specific, and most people aren't.
My main take is that if the crew has an ACTIVE ARMORED TARGET running around the ship shooting people, the EARM is there for a reason, I'd buff EARM in general, its pretty trash.

**Comment by Yurek1** [comment]
> > I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason. Also, pepperballs barely work on unarmored targets. All this will do is make sidearm guns worthless.
> 
> I'm going to go step by step, since I'm in a rant mode for some reason.
> 
> > Each gun is only issued one magazine
> 
> 1 magazine? One magazine is enough to shoot someone and run away, the brig chief is around for a reason in my opinion. Though.
> 
> > and LTLs are generally accepted as being completely worthless against anything but unarmored targets
> 
> LTLs are fine against most threats you want to take out in self defense, in my opinion. You're still a threat to most unprepped antag players and anyone normal who isn't wearing any type of heavy armor. Pepperballs are fine.
> 
> > If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.
> 
> Brig chief is around for a reason IMO. I think people should run to him for ammo in most scenarios, or go to the emergency armory. The emergency armory bloody sucks, though. Probably needs a buff.
> 
> > Also, pepperballs barely work on unarmored targets. All this will do is make sidearm guns worthless.
> 
> why are you running up to armored targets with assault rifles with your sidearm in the first place, though? I understand this is a poor argument, but.. Try running, ASAP. Run speed is so fast you can run.

As someone who played security quite a lot, Brig Chiefs are typically incompetent, jackasses, or SSD on the job. CoS' are too busy, and nobody else has access. I didn't say 'running up to', I implied that someone going mass-shooter mode (which happens a lot more frequently than I would like) isn't going to be stopped by pepperballs. I've seen antags in heavy armor with STS-35s take down the entire Security team because they had no lethal options, and this is taking lethal options away from EVERYONE ELSE. Explorers get sidearms because they're expected to take down hostile xenofauna, as well as defend themselves. I understand the reasoning behind this, but ultimately, it's a bad idea. All it's going to do, like I said, is make sidearm guns absolutely worthless unless there's someone around to print ammo. And need I remind you that according to in-game SOP, nobody but Security is supposed to have a hacked lathe, and only four people on the entire ship have access to the armory. The reason I say that LTLs are worthless is because most antag players _do_ have heavy armor and gas masks. Frequently. I've seen more heavily armed and armored antags than i've seen people running around doing creative things in maintenance. Yes, one magazine is enough to shoot someone and run away, but that's mostly if they're unarmored, and I don't think I need to repeat myself there. Also, LTL doesn't work on someone who's on painkillers/drugs- at all. So if the local crethhead charges you with a baseball bat and starts caving your skull in, you better roll over and die unless you have lethal options available.

**Comment by Yurek1** [comment]
If you want to reduce validhunting, quality control needs to be improved. Removing their avenues limits everyone else, too.

**Comment by AMcilraith** [comment]
> > > I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason. Also, pepperballs barely work on unarmored targets. All this will do is make sidearm guns worthless.
> > 
> > 
> > I'm going to go step by step, since I'm in a rant mode for some reason.
> > > Each gun is only issued one magazine
> > 
> > 
> > 1 magazine? One magazine is enough to shoot someone and run away, the brig chief is around for a reason in my opinion. Though.
> > > and LTLs are generally accepted as being completely worthless against anything but unarmored targets
> > 
> > 
> > LTLs are fine against most threats you want to take out in self defense, in my opinion. You're still a threat to most unprepped antag players and anyone normal who isn't wearing any type of heavy armor. Pepperballs are fine.
> > > If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.
> > 
> > 
> > Brig chief is around for a reason IMO. I think people should run to him for ammo in most scenarios, or go to the emergency armory. The emergency armory bloody sucks, though. Probably needs a buff.
> > > Also, pepperballs barely work on unarmored targets. All this will do is make sidearm guns worthless.
> > 
> > 
> > why are you running up to armored targets with assault rifles with your sidearm in the first place, though? I understand this is a poor argument, but.. Try running, ASAP. Run speed is so fast you can run.
> 
> As someone who played security quite a lot, Brig Chiefs are typically incompetent, jackasses, or SSD on the job. CoS' are too busy, and nobody else has access. I didn't say 'running up to', I implied that someone going mass-shooter mode (which happens a lot more frequently than I would like) isn't going to be stopped by pepperballs. I've seen antags in heavy armor with STS-35s take down the entire Security team because they had no lethal options, and this is taking lethal options away from EVERYONE ELSE. Explorers get sidearms because they're expected to take down hostile xenofauna, as well as defend themselves. I understand the reasoning behind this, but ultimately, it's a bad idea. All it's going to do, like I said, is make sidearm guns absolutely worthless unless there's someone around to print ammo. And need I remind you that according to in-game SOP, nobody but Security is supposed to have a hacked lathe, and only four people on the entire ship have access to the armory. The reason I say that LTLs are worthless is because most antag players _do_ have heavy armor and gas masks. Frequently. I've seen more heavily armed and armored antags than i've seen people running around doing creative things in maintenance. Yes, one magazine is enough to shoot someone and run away, but that's mostly if they're unarmored, and I don't think I need to repeat myself there. Also, LTL doesn't work on someone who's on painkillers/drugs- at all. So if the local crethhead charges you with a baseball bat and starts caving your skull in, you better roll over and die unless you have lethal options available.

I have literally repelled jeff with a pepperball gun. It worked.

**Comment by AMcilraith** [comment]
> > > I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason. Also, pepperballs barely work on unarmored targets. All this will do is make sidearm guns worthless.
> > 
> > 
> > I'm going to go step by step, since I'm in a rant mode for some reason.
> > > Each gun is only issued one magazine
> > 
> > 
> > 1 magazine? One magazine is enough to shoot someone and run away, the brig chief is around for a reason in my opinion. Though.
> > > and LTLs are generally accepted as being completely worthless against anything but unarmored targets
> > 
> > 
> > LTLs are fine against most threats you want to take out in self defense, in my opinion. You're still a threat to most unprepped antag players and anyone normal who isn't wearing any type of heavy armor. Pepperballs are fine.
> > > If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.
> > 
> > 
> > Brig chief is around for a reason IMO. I think people should run to him for ammo in most scenarios, or go to the emergency armory. The emergency armory bloody sucks, though. Probably needs a buff.
> > > Also, pepperballs barely work on unarmored targets. All this will do is make sidearm guns worthless.
> > 
> > 
> > why are you running up to armored targets with assault rifles with your sidearm in the first place, though? I understand this is a poor argument, but.. Try running, ASAP. Run speed is so fast you can run.
> 
> As someone who played security quite a lot, Brig Chiefs are typically incompetent, jackasses, or SSD on the job. CoS' are too busy, and nobody else has access. I didn't say 'running up to', I implied that someone going mass-shooter mode (which happens a lot more frequently than I would like) isn't going to be stopped by pepperballs. I've seen antags in heavy armor with STS-35s take down the entire Security team because they had no lethal options, and this is taking lethal options away from EVERYONE ELSE. Explorers get sidearms because they're expected to take down hostile xenofauna, as well as defend themselves. I understand the reasoning behind this, but ultimately, it's a bad idea. All it's going to do, like I said, is make sidearm guns absolutely worthless unless there's someone around to print ammo. And need I remind you that according to in-game SOP, nobody but Security is supposed to have a hacked lathe, and only four people on the entire ship have access to the armory. The reason I say that LTLs are worthless is because most antag players _do_ have heavy armor and gas masks. Frequently. I've seen more heavily armed and armored antags than i've seen people running around doing creative things in maintenance. Yes, one magazine is enough to shoot someone and run away, but that's mostly if they're unarmored, and I don't think I need to repeat myself there. Also, LTL doesn't work on someone who's on painkillers/drugs- at all. So if the local crethhead charges you with a baseball bat and starts caving your skull in, you better roll over and die unless you have lethal options available.

Also this 
image

**Comment by miniusAreas** [comment]
> > > I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.
> > 
> > 
> > This is literally the job of sec/infantry. Not the job of explorers.
> 
> So if someone charges explorers with an automatic rifle, they're expected to lay down and die or run away? They're part of the military. The entire ship is military.

Do you need a fucking gun to kill someone as an explorer? Man, explorations gotten soft. Back in my day we just cut up anyone who got on the Gaunt that we didn't like with our machetes.

Point being - sure it may be in-theme to have lethals, but for a gameplay point of view this does help massively alleviate validhunting (as your gun is now a distraction tool at best)

**Comment by Yurek1** [comment]
> > > > I disagree with this. Each gun is only issued one magazine, and LTLs are generally accepted as being completely worthless against anything but unarmored targets. Yes, it'll reduce validhunting a little, but not by a lot. If you're someone who doesn't normally have access to ammo, like an Explorer, having a lethal firearm is very important if an antag decides 'fuck your shit' for whatever reason.
> > > 
> > > 
> > > This is literally the job of sec/infantry. Not the job of explorers.
> > 
> > 
> > So if someone charges explorers with an automatic rifle, they're expected to lay down and die or run away? They're part of the military. The entire ship is military.
> 
> Do you need a fucking gun to kill someone as an explorer? Man, explorations gotten soft. Back in my day we just cut up anyone who got on the Gaunt that we didn't like with our machetes.
> 
> Point being - sure it may be in-theme to have lethals, but for a gameplay point of view this does help massively alleviate validhunting (as your gun is now a distraction tool at best)

Again, I see this as a QC issue, and not something for code.

**Comment by InfinitelyThinRectangles** [comment]
Man, when Evo told me Hestia was coming back up, he told me it WASN'T going to be a hugbox or over-moderated like Hestia was and that this was part of what made it so great.

Now we have people trying to remove sidearms worth a damn from soldiers on a military ship because "muh valid huuuuuuuuuuuuuuuuuunt!!!111!!!!!11!!!"

Good lord above, that didn't take long to lose the original vision at all. Frankly, I'd be in favour of giving them _better_ loadout weapons, maybe we'd have less murderbone if more people could clap a would be columbine shooter's cheeks the moment they tried it.

If you go active shooter on a military ship, you should expect lightly armed disorganised resistance from nearby military personnel with sidearms. Having a better armed, more combative populace was an intentional design decision to facilitate internal combat more often, and this entire mindset has evidently been totally and utterly forgotten in favour of trying to run the place like just another standard "NT Research Station" culture wherein **NOOOOOOO ONLY SECURITY ARE EVER ALLOWED TO CLICK HARM INTENT!** Evidently, there's such a thing as _too much_ HRP influence.

Goddamn, _let people have fun._

**Comment by anconfuzedrock** [comment]
Chill, man. While this isn’t how I would fix the issue, current handgund have a ludicrously high fire rate, the mk49 being faster than smgs, and all handguns do a SHIT ton of damage being magdumped with that is not “fun” and makes it harder to rp with antags. The options were probably this or major merfs to the handguns.

**Comment by InfinitelyThinRectangles** [comment]
I've been present for the discussion on handguns, and it's a one-line config tweak to change their fire delay. That's it, that's literally it, it's 4 characters, 3 if you don't count the decimal.

That is _not_ a big deal if handguns really do require adjusting,

**Comment by Teragenic** [comment]
Just change it to rubbers in my opinion, still enough to kill any hostile maint dwellers in case. Plus can still do damage if needed.

**Comment by AMcilraith** [comment]
> Just change it to rubbers in my opinion, still enough to kill any hostile maint dwellers in case. Plus can still do damage if needed.
Easily done.

**Comment by InfinitelyThinRectangles** [comment]
Crew being lightly armed and being able to resist active shooters was an intentional design decision intended to facilitate _having fun_ by allowing people to avoid being hapless victims. This is not a design oversight, this is _as it's supposed to be._

**Comment by anconfuzedrock** [comment]
You're not a hapless victim just because you don't have a fucking gun. If you want to fight, you can grab a toolbox or whatever. I don't think rubbers will be ideal for killing maint goblins though, those care more about damage than pain.

**Comment by ProbablyCarl** [comment]
For once, I have to agree with ITR on something. Considering I'm the one who added it.

This is intended design, yes. It's a single lethal load, and while our gameplay can be fast and loose, that doesn't necessarily mean you're instantly going to win. Y'all are just unrobust, lol.

The entire issue otherwise is sorted with QC that we're working on. Be patient. It's 2d spessmen.

**Pull request closed without merging**
