### PR TITLE
Removes the death alarm implants

### PR DESCRIPTION
**Pull request by Sparrowbird611**
The fixed version, separated from the tracking implant nerf I did previously.

I really hate items that proc on death, especially ones that scream over half the radio frequencies "HEY, THIS GUY DIED HERE!" as soon as they expire, with no real way to determine if they even have said implant. Command staff doesn't need it, they're literally surrounded by lackies most of the time, security doesn't deserve it, they have plenty of equipment and don't need a post mortem screaming device.

Thank you for coming to my ted talk. You may now scream.

### CODE REVIEW

**Comment by JohnBigless** [comment]
No. Death alarms are literally the only thing protecting lower-ranking command members from the 'i order you to come with me into a private room' antag murder method.

**Comment by Roland410** [comment]
Still gonna go with keep it as a research thing and remove it from the map.

**Comment by Sparrowbird611** [comment]
> No. Death alarms are literally the only thing protecting lower-ranking command members from the 'i order you to come with me into a private room' antag murder method.

You were dying either way, the only difference is you'll be found sooner.

Death alarm implants don't protect. Antagonists don't even know about them most of the time, because there's no signs that they exist. The only thing they do is help avenge you, but they aren't going to prevent your death or protect you in the slightest.

**Comment by Sparrowbird611** [comment]
> Still gonna go with keep it as a research thing and remove it from the map.

I really dislike this option, because of the way research is. It's either "That one guy who does research exists and everyone has it" or "No one does research and it never arrives."

**Comment by Roland410** [comment]
> > Still gonna go with keep it as a research thing and remove it from the map.
> 
> I really dislike this option, because of the way research is. It's either "That one guy who does research exists and everyone has it" or "No one does research and it never arrives." I could leave it in I guess and see how it goes, but I'm not a fan.

That means it's even less reliably, which would be in line with your goal, I think. You can't count on research doing R&D every round, unlike you know that there are three boxes of it on the ship every roundstart.

**Comment by Sparrowbird611** [comment]
I'm more focused on the boxes than the printable ones to be honest, so I'll remove the research part of this PR for now.

**Comment by AdamElTablawy** [comment]
@JohnBigless 

Suit sensors?

Also, if you're getting shot wordlessly and decapitated out of the blue that's kind of LRP.

**Comment by JohnBigless** [comment]
@AdamElTablawy

Suit sensors can't help when you're getting completely stripped the moment you're cuffed, not even if the sensors are locked.

And while death alarms won't actually protect someone, they'll cock-block shitters who opt for stealthily taking out command members with the afromemtioned method by notifying everyone that something is up.

**Comment by Sparrowbird611** [comment]
> @AdamElTablawy
> Suit sensors can't help when you're getting completely stripped the moment you're cuffed, not even if the sensors are locked.
> And while death alarms won't actually protect someone, they'll cock-block shitters who opt for stealthily taking out command members with the afromemtioned method by notifying everyone that something is up.
> Taking out command should be challenging, not just bait them one-by-one into a room and sedate them.

And it is challenging, because unless Command is full blown idiotic, they aren't all going to forget about the missing co workers and go "Hippity  hoppity, I'm going to go into this office where all my freaking co workers disappeared to with Mr Bones, this cannot go wrong at all."

**Comment by BurgerLUA** [comment]
A poll is needed on this one.

**Comment by AdamElTablawy** [comment]
@JohnBigless 

If someone vanishes from sensors, medical should notice. If someone gets lured to a room and never comes back, command should notice.

And nobody has ever done what you're describing, nor do they actually 'protect' command members...or make taking them out challenging, tbh. They just serve as powergame gear for play2win nerds, like you.

**Comment by ProfessorPopoff** [comment]
Yeah. I don't entirely know about the situation so I'm not entirely qualified to talk about it- But in short...

The game is about roleplaying, Or so i'm led under the impression. Death is a fact of life, game or not. The fact that this was ever a thing is really ridiculous, I think. 

**Command personnel have many things going for them. Such as:**

- Being CONSTANTLY surrounded by other high ranking individuals

- The ability to get Security to their location at a moment's notice

- The CO in particular literally has a revolver to wipe you off the ship in a few clicks

- Hate to say it. But "subtle" clique-ness to them.

With all this into account, People in higher ranks really do NOT need any other advantages, Not to mention in the event that these motherfuckers do actually die, Hestia has cloning with their Altered Carbon ripoff stuff. It's a real pain in the ass to make sure that some people die, and keep it that way. I think that this boils down overall to a playerbase issue than a development side one, if anything. But there's not all that much you can do to change that without just wiping the things that allow these powergamer retards to walk around and do whatever they please, like Death Alarms and Cloning.

**Comment by BurgerLUA** [comment]
The poll on this is an overwhelming no. I don't see the reason to remove it from the map either.

**Comment by ProfessorPopoff** [comment]
Surprise surprise. Local playerbase is seething at the thought of making death meaningful once again.

**Comment by Sparrowbird611** [comment]
> The poll on this is an overwhelming no. I don't see the reason to remove it from the map either.

Understandable. I've said most of what I had to say, and anything I didn't popoff pretty much covered, so I won't spout any more arguments. Do as you will.

**Comment by AdamElTablawy** [comment]
@BurgerLUA Ask carl instead of the playerbase. Of course the poll will be a no.

It was a no for mindslave implants too, but we removed those in the end after another poll and it was for the better.

If they don't voice their opinions on the github and don't offer a counterargument, why should they be heard at all? Popoff is correct in everything he said.

**Comment by BurgerLUA** [comment]
If Carl wants to merge this, he can, but I'm not going to be merging this myself.

**Comment by BurgerLUA** [comment]
The poll says no and I don't think carl is interested in merging this.

**Pull request closed without merging**
