### PR TITLE
fuck you bay

### PR DESCRIPTION
**Pull request by Vizoplez**
removes god-awful cancer mechanic that resulted in nearly everyone dying to awakening their psionics

https://www.youtube.com/watch?v=g7_I6kj9fTc

### CODE REVIEW

**Comment by Noobetski** [comment]
If it's caused only by Three Eye it's a feature so people would actually ask help from psionic advisor with awakening, if it works on any kind of awakening it's fucked

**Comment by Vizoplez** [comment]
> If it's caused only by Three Eye it's a feature so people would actually ask help from psionic advisor with awakening, if it works on any kind of awakening it's fucked

this is false and I do not believe you have read the code.

This applies to all types of awakenings, including brain damage awakenings.

**Comment by Squigger** [comment]
Should really be capped at a threshold rather than removed, so it's the more dangerous option than asking the PADV for assistance. Chugging drugs to go fight interdimensional Egyptian deities should hold some risk.

**Comment by Vizoplez** [comment]
> Reference in new is

done

**Comment by ProbablyCarl** [comment]
Good stuff, with not complete removal.

**Pull request merged**
