### PR TITLE
Holy vox books

### PR DESCRIPTION
**Pull request by Rayfod**
Holy books for the voxes, as requested by the vox lore maintainer "**Weezer**"
Skærmbillede 2022-02-28 214331
Skærmbillede 2022-02-28 231911
Skærmbillede 2022-02-28 231957

Get them from your local loadout shop for now.
And yes, you can fill the book with booze if you want.

### CODE REVIEW

**Comment by Anton-Kr** [comment]
@Armyguy This cool with you? note that everyone can spawn with these books, and the code will need to be different if that isn't your wanted behavior.

**Comment by ProbablyCarl** [comment]
Restrict this to the alien branch.

**Comment by Rayfod** [comment]
Changes made as requested by @ProbablyCarl

**Comment by John-Dang** [comment]
It has my approval as the vox maintainer, and I wrote all of the descriptions so, I have reviewed it fully!

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
