### PR TITLE
Minor map tweaks and fixes

### PR DESCRIPTION
**Pull request by Roland410**
🆑Roland410
:maptweak:Makes it harder to escape from the psionic cells.
:maptweak:Added some camera coverage to places where it was lacking across the ship.
/🆑
This also fixes Travis failing because of the wiring @Andromeda-K22 forgot to place.

### CODE REVIEW

**Comment by Andromeda-K22** [comment]
Mapdiff is shitting itself so I can't really tell what changed.

**Comment by Roland410** [comment]
As said in the DMs on Discord, this places cameras over the decks where it was lacking camera coverage, makes stairs babyproof, and makes it so you can't jump out of the psionic cells like you can right now.

**Comment by BurgerLUA** [comment]
Please post the images here so people can review what was changed.

**Comment by Roland410** [comment]
It'd take a while to make screenshot of all the individually added cameras to be honest.

**Comment by BurgerLUA** [comment]
Just do the prison cell, then.

**Comment by Roland410** [comment]
image
image
image
image
image
image
image
image
image
image
image

**Pull request merged**
