### PR TITLE
Adds Laser Carbines, Combat Knives and inducers to antag uplink

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Laser carbines, combat knives and Inducers added
~~i'm dumb and an idiot so~~ these are costed based off the CRETH they cost.
Combat knives being equivalent to 
## Why It's Good For The Game
Laser carbines being accessible to traitors make sense, I asked around and people said it should cost a bit less than an STS, it has hitscan and burn damage but less DPS.
Combat knives make sense, they're a bit more than the switch blade.
Inducers can be useful, and they're 20 TC overall. That's FOUR syringes.
## Did You Test It?
Not sure how to test uplink stuff, if someone could give me some help with that, ping me on discord.
## Authorship
MJP#4043, Dudeman100- Ckey
## Changelog

:cl:
tweak: Added laser carbines (68tc), Inducers (20tc), Combat knives (5tc) to antag uplinks.
/:cl:

### CODE REVIEW

**Comment by Yurek1** [comment]
> 

i think this is fine but combat knives don't seem like something worth adding, since they can be printed from any hacked autolathe

**Comment by Rafflesia7793** [comment]
> > 
> 
> i think this is fine but combat knives don't seem like something worth adding, since they can be printed from any hacked autolathe

Yeah but that requires to you break into those departments to use their autolathe. If we're worried about bloating the uplink, there's TONS of dumb stuff with zero use that can be removed.

**Comment by Yurek1** [comment]
> 

almost every department has a lathe, with the exception of civilians, service, and exploration. i guess if you put the cost to something like 3TC it might be more worth it? anyone who's military can spawn with them in most scenarios, with few exceptions, so the only people who this will apply to is civilians

**Review by N8-Toe — APPROVED** [review]
code and concept look good

**Comment by Pariah919** [comment]
>almost every department has a lathe, with the exception of civilians, service, and exploration. i guess if you put the cost to something like 3TC it might be more worth it? anyone who's military can spawn with them in most scenarios, with few exceptions, so the only people who this will apply to is civilians
>

Switchblades are like worse, in every scenario statistically outside of TC cost and fashion. I can get the idea though. This is moreso a 'If I need some sort of stabbing implement on the cheap, NOW.' Kind of thing. I could make it plasteel, however.

**Comment by Yurek1** [comment]
> 

i wasn't talking about switchblades, but that would be neat. a new knife, traitor only, that does a little more damage? that would be cool and unique enough to be worthy to be put into the uplink. 
as it stands, the regular steel combat knife can be spawned with from the tactical gear loadout menu, or printed from literally any hacked autolathe

**Pull request merged**
