### PR TITLE
Readds Legalese

### PR DESCRIPTION
**Pull request by Roland410**
🆑Roland410
:rscadd:Readds Legalese, it ain't dying so easily.
/🆑

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
Absolutely based.

**Comment by peeesh** [comment]
ok but why. why is legalese useful or needed

**Comment by Roland410** [comment]
Legalese is mostly a gimmick-ish language for people who want to play an educated lawyer/bureaucrat type of character basically. It's just about as "useful" as any language other than ZAC, but this makes taking higher bureaucracy skill (experienced) have some meaning as well, unlike other selectable languages.

**Comment by BurgerLUA** [comment]
The early polls for this PR looks good. Will be merging this tomorrow if it still has approval from the community.

**Pull request merged**
