### PR TITLE
removes lean

### PR DESCRIPTION
**Pull request by gilvian**
fuck you

## About The Pull Request

removes lean

## Why It's Good For The Game

less crackheads that just OD on lean, might improve the RP quality

## Did You Test It?

yes

## Authorship

me

## Changelog

:cl:
* rsdel - Removes lean, fuck you
/:cl:

### CODE REVIEW

**Comment by Dark1Star3s** [comment]
+1

**Comment by gilvian** [comment]
image
carl agrees

**Comment by gy1ta23** [comment]
I officially support this PR

**Comment by gilvian** [comment]
image
im going to sleep, gonna fix it somehow when I wake up

**Comment by Armyguy** [comment]
Antidexafen will not even DO what lean does unless your ODing on it. So from a code POV this code is shit as its not killing you when you drink it.

**Comment by N8-Toe** [comment]
There is no point in removing this feature. 

if there is an issue with player behavior please speak to the admins, we don't remove things for the sake of removal. If you'd like to discuss this further contact myself or Carl

**Comment by ghost** [comment]
Hello, I am the one who ported tilt to the codebase in #1490 and this is my official statement.

First, we overlook lean. Then we permit lean. Then we legalize lean. Then we promote lean. Then we celebrate lean. Then we persecute those who still call it lean.

In other words, the administration needs to ban people who call it lean for fail RP.

**Pull request closed without merging**
