### PR TITLE
Temporary Prommie disable

### PR DESCRIPTION
**Pull request by CrackParrot11**
This removes the Spawn flag for prommies until they can be worked into a state where they are not extremely broken.

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
I'd like to hear what exactly makes them "broken." They seem to be working fine from what I can see, though I confess they're rare and I usually only see a few.

**Comment by CrackParrot11** [comment]
I am going to get assblasted for this but, this was under the discretion of the lead maintainer that wanted this to happen. And prommies are extremely strong in the code right now with almost complete resistances to burn,brute damage and can only really take damage from sources like water. and i believe that the shape shifting feature of prommies is not completely finished either.

**Comment by chaoko99** [comment]
I'm just gonna be an ass right now and say that typically speaking, based on my several years of history with the topic: Soft removing something doesn't endear people to fix them. IT just encourages people to remove them later.

**Comment by Roland410** [comment]
As said above, "temporarily" removing them will result in them being abandoned. I've fixed up what I could with Lonefly, and we have lore in the works (mostly not done because I'm busy).

I've spent at LEAST A WEEK balancing them, hell, they had to be buffed because water could instakill them (it takes ~4 sprays now to kill them with an extinguisher). I'm not going to fly by and drop changes to them every time because someone decided to, say nerf lasers etc.

When my/Lonefly's PR was merged, they were in a perfectly usable and balanced state, except the transformation being buggy because oldcode.

**Comment by AdamElTablawy** [comment]
>temporarily removing them will lead to them being removed

what's the flaw

**Comment by CrackParrot11** [comment]
I am going to keep this up in case the Lead maintainer wants to still use it or not but i was asked to do so.

**Comment by listerla** [comment]
image

**Comment by SilvernKell** [comment]
Please don't remove them, then it'll be like marines or something
Would rather play them "broken" then not at all, just make them weak if they're insanely strong right now (I'm not sure they are though?)
If they're weak just let people play 'em


Better to "fix" then to remove.

**Comment by MarinaGryphon** [comment]
There was a fix PR already made that unbalanced them even more. Frankly, I've had it up to here with dealing with the issues Prometheans cause.

This PR will not be hardmerged, so it will remain open and testmerged until someone comes up with a proper fix. Frankly, I could care less if they were permanently removed, because _apparently_ no one cares enough about them to fix them properly anyway.

**Comment by Roland410** [comment]
Prometheans were perfectly balanced until people started fucking with damage values here and there.

**Comment by Roland410** [comment]
@MarinaGryphon By the way, you can go ahead and merge this, considering Lonefly seems to have left the server/is MIA and I doubt anyone else wants to "fix" them.

When I made the initial PR, I've tested them for a week, constantly nerfing them to be balanced. I've asked for feedback a LOT of times. You came into the PR, took a big pile of shit on it and closed every communication with me. I don't have the time or patience to put up to your shitty behavior.

If you can make a proper, and acceptable list of changes, I may make them, but your idea of balance considering your response to the initial PR, will be probably a joke.

However, as always, I'm open to feedback, as long as you can do it constructively.

**Comment by MemedHams** [comment]
Yeesh, this got a bit spicy. Myself and @Roland410 are working on a revised lore for Prometheans, I was planning on working on it but put it on the backburner to Coronavirus things. If it's a contentious issue I guess I could start hashing out now. In the mean time, could we not throw them down the infantry scullery chute? I started off more or less noncommittal about prommies but have become rather attached to them.

**Comment by ProbablyCarl** [comment]
Discussed with various individuals. This'll be closed for the moment, as testing shows this isn't required, as bad as they are at times.

**Pull request closed without merging**
