### PR TITLE
Changes fixes one tile to be made correctly next to pathfinder office

### PR DESCRIPTION
**Pull request by gilvian**
Changes this 
image
Into this
image

:cl: sabiram
tweak: Fixes one tile to fix someone OCD
/:cl:

### CODE REVIEW

**Comment by ProbablyCarl** [comment]
Something else is edited in the file?

**Comment by BurgerLUA** [comment]
For some reason it's changing the order of every single variable so half the file is getting edited.

**Comment by BurgerLUA** [comment]
I don't think mapmerge was run properly on this or something.

**Comment by BurgerLUA** [comment]
Conflicts, and map merge wasn't run on this properly.

**Pull request closed without merging**
