### PR TITLE
Turns Away Site's CI green

### PR DESCRIPTION
**Pull request by Kaksisilma**
Gives bearcat a display case for the Solid Argument instead of a glass window.

makes our repo have pretty, cute green CI checks

### CODE REVIEW

**Comment by Armyguy** [comment]
Um just to point out, some of the "fixs" for the vox ship are not fixs. It was using the torch/engine_main as it needed the power output, and the ("ACCESS_VOXSHIP_CAPTAIN") was the door to the quills room, you know the captains bed room/office. 

And a few of the doors you added access too, I removed to make the lifes of guest on the ship not shit.

**Comment by Kaksisilma** [comment]
Torch/engine_main is supposed to be used only on the Torch, hence why it is on the torch_presets folder. Using it here inevitably leads to a runtime.

Voxship was still runtiming in airlocks, so I replaced some of them for doors I knew were working. Qill's office still has vox_captain access. The infirmary cryo thing does not, but it can be re-added if you want since including his access there felt like a mistake.

**Comment by Kaksisilma** [comment]
FIX-SHIT FRIDAY LETS FUCKING GOOOOOO

**Comment by Anton-Kr** [comment]
I fuckin love you!!!

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
