### PR TITLE
Adds Three Eye to the uplink and Jerraman changes, minor fixes.

### PR DESCRIPTION
**Pull request by Roland410**
🆑Roland410
rscadd:Adds Three Eye to the uplink for 50TC.
rscadd:Readds the Jerraman vial carrier to the PADV's closet.
tweak:Jerraman vial carrier only has 5 vials now instead of 20.
tweak:Fixes up some leftovers after FADV was renamed to PADV.
/🆑
Weezer approved giving the Jerraman back to the PADV, but only with the reduced numbers.
Allows traitors to buy a pill bottle of Three Eye for 50TC as an alternative if the PADV decides not to awaken you (boo hoo hoo) or for them to sell it to people etc.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
three eye is worth WAY less than 80tc lmao

**Comment by Roland410** [comment]
I upped the awaken chance in the FADV PR to 50% from 30% so you need to OD less, and you have Alky for the brain damage for dirt cheap.
In exchange you get to roll 2 latencies, which can theoretically be Psychokinesis on Paramount, which is full TK.

**Comment by bearrrrrrrr** [comment]
mmm

i still don't think it's worth 80tc tbh

like if it being too strong was a concern yes i'd be down for 80tc but we HARDLY EVER see psyker traitors as-is.  i'd personally like to see if it started lower and then if it was too high, adjusting the price

buuut that's just me lol

**Comment by Roland410** [comment]
What I expect to happen, is the PADV will start scanning people and since he can only give five people the vials, traitors knowing that they can be psions, will resort to this.
And frankly, this contains 10x10 Three Eye, and you only need 30+ to OD. This means that one traitor can make 3 psions theoretically.

**Comment by Sparrowbird611** [comment]
Seems exceptionally overpriced on the three eye, but otherwise I like the idea.

I'd go with what bear said, and make it cheaper. Given there isn't even a way for the traitor buying three eye to know if they're awakened in the first place without begging the counselor or psi advisor, (Who don't always spawn) and that, on top of the RNG of rolling latency, you have to take another roll chance to **maybe** roll paramount in a school, 80 TC seems far too expensive, not to mention the fact that most powers short of TK can't compare to just buying a gun and going on a shooting spree.

**Comment by Roland410** [comment]
Well, I am going with the above for now, if it feels to expensive, I'll lower the price.

**Comment by Roland410** [comment]
Travis fail is unrelated, but let me update to dev.

**Comment by AdamElTablawy** [comment]
you can make threeye in chem. 80tc is a hot meme.

**Comment by Roland410** [comment]
Noone said you can't. It's just that most will not, especially that even Three Eye needs Carpotoxin, which is a pretty rare maint loot from my experience, and very few will go EVA and get carps to make it.
At the end of the day, this is for ease of access and consistent availability for traitors.
By the way, you could technically make Jerraman in chem as well, but even less people will, no matter if they have Three Eye for it or not. The ingredients are pretty time consuming to acquire.

**Comment by Sparrowbird611** [comment]
Experience with RNG varies, though I've found carpotoxin in maint fairly often. However, more relevant to this is that you can currently buy carpotoxin in the PDA now, and while it does still require chemistry skills and supplies, it's not hard for a robust chemist to get all that no matter their role. Though most will not, I agree, since most chemicals aren't worth the time to make.

**Comment by Roland410** [comment]
I totally forgot you implemented Carpotoxin, but yeah, my point is that most people don't know how to make it, or where to find the ingredients outside of chemistry.
As I said above, if this gets merged, and feels too expensive, I'm open to changing the price, but the possible benefits you can get from psionics will quite possibly worth the price.
Or you can just get the components and ghetto it.

**Comment by Superhats** [comment]
To be fair, the only component that makes three-eye expensive is carpotoxin. Everything else is pretty much readily available.  Considering Carpotoxin costs a whole **6** telecrystals, it feels dumb to multiply the price by 10 just because it mixes the rest of the chems (Which you can get in a chem dispenser)

**Comment by Roland410** [comment]
Ah yes, because all traitors play chemistry. I have already clarified the reasons above, please read it.

**Comment by Superhats** [comment]
I've read those reasons. I personally don't think a fully mixed chem is worth eighty telecrystals, which is half your uplink.

**Comment by AdamElTablawy** [comment]
Roland why would anyone spend half their TC on an illegal drug that will almost definitely kill you if misused when they can just buy the ingredients for 6tc from their uplink and mix it themselves in chem.

And that's 80tc for something that might not even be worth it. I can buy better shit myself. It'd be easier to fake being a chemist and get into chem or use sci-chem than to bother spending eighty telecrystals.

Cut the price.

**Comment by Roland410** [comment]
While those are fair points, the dangerous part is easy to counter, RNG was decreased, and it's obtainable normally, just pretty damn illegal.
However, the general consensus seems to be that it's too expensive, so I'm cutting down the price to 50TC. Any less than that feels unreasonable, when you get enough of it to awaken THREE people.

**Comment by Sparrowbird611** [comment]
50 Is a fair price.

**Comment by Roland410** [comment]
Done, thanks for the reminder.

**Comment by BurgerLUA** [comment]
Failing tavis.

**Comment by Roland410** [comment]
Not anymore, take that, Travis.

**Pull request merged**
