### PR TITLE
Vox mindslave implant

### PR DESCRIPTION
**Pull request by Rayfod**
Vox mind slave implants are organic and can get people captured instead of killing them.
A lockbox was made with a few implants in it.
A new sprite for when you take the implant outside of a person, it wiggles!
Funky code, that is bad but works.
You can see the laws in your notes if you ever get confused.

"You are the property of the voxes."
"You are worth a lot as a property, so make sure that you stay away from harm."
"You are not allowed to use any device that is considered dangerous. This may include using weapons, delaming a supermatter, or activating a bomb, as an example. "
"If you are sold to someone, then you are to treat them as your new owner."

Skærmbillede 2022-03-03 221546

**I will add the lockbox in a separate PR**

### CODE REVIEW

**Comment by ProbablyCarl** [comment]
Map merge this. Use TGM if needbe.
Don't want it like it is currently.

**Comment by Rayfod** [comment]
**Do wait a bit to merge it**

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
Since the implant will seriously impact a person's round and may put them in a position of feeling uncomfortable with continuing to play in the round, please add an option for the host to reject the implant and face the consequences of the Vox knowing that the implant was rejected.

**Comment by Rayfod** [comment]
**Do not merge. Let me see if this works**

**Comment by Rayfod** [comment]
I will just make a new PR, for this is useless to work with right now

**Pull request closed without merging**
