### PR TITLE
Adds an new "energy Tectonic" to the SEC-ARM

### PR DESCRIPTION
**Pull request by Jaraci**
Oh boy. All values here are very WIP.

- Adds the BXJ-5 Culverin, a 3-round pulse rifle variant, to the SEC-ARM. It can fire 12 bursts before needing recharged.
- The Culverin has two fire modes: high-frequency fire, which inflicts burn; and experimental fire, which inflicts brute damage instead at the cost of raw power.
- The Culverin requires specific authorisation for both fire modes, like the Tectonic. It cannot be fired otherwise unless on red alert or above.
- The final shot of each burst has some dispersion to it and will occasionally go wide. The Tectonic's penetrating power meant it caused some collateral damage when used; this should help replicate this effect.

Security got a flat-out nerf with the addition of infantry. This should help rectify that without just giving them a second Tectonic again. It uses the pulse rifle sprite for now, but considering that pulse rifles are actually just flat-out not used anywhere I don't foresee this being an issue.

High-frequency (burn damage) mode is intended to be the default, with the brute damage secondary mode being an inferior alternative in terms of damage.

Feedback is very much appreciated. Thanks to @ProbablyCarl for some help with this PR.

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
First off, why do we need ANOTHER gun to ignore armor. This is literally unnecessary.

Secondly, jeez, you gave it 36 shots? What in the world man.

**Comment by Jaraci** [comment]
It is locked to three-shot bursts because it is a pulse rifle. You can only actually click twelve times.

It ignores a shitload of armour because that was the Tectonic's original gimmick -- ignoring armour at the cost of raw damage.

**Comment by Sparrowbird611** [comment]
Meh. I just don't see why security actually needs an armor ignoring gun. They already have plenty of decent weapons, I see no reason to give them this one.

Though if it does go through, at least we can say that the plasma pulse projector does something now.

**Comment by Roland410** [comment]
The sprite should probably be changed, as antags can still buy a pulse rifle afaik.

**Comment by Jaraci** [comment]
@Roland410 fair point, although I have never once seen anyone actually use it because of how dogshit it is. I'll try to see what I can do in that regard

**Comment by Roland410** [comment]
True, but you can probably do some minor changes so it's distinct from the pulse rifle.

**Comment by AdamElTablawy** [comment]
this does 54 dmg per full burst

this is effectively just an infinitely better laser carbine there's no reason not to take because it's hitscan

it'll fleece anything including ascent armor and merc armor and do serious amounts of blood evaporation and lung damage, and without the usual tectonic drawback, which is running out of ammo/penetration/friendly fire

i'd be careful with this tbh

**Comment by Sparrowbird611** [comment]
If this has to go through, I'd lower the damage far more, to ten at most for laser mode, and two less for the brute mode.

Actually, why even have two modes is what I have to ask. It's not really a bad thing but it's an odd addition tbh.

**Comment by Roland410** [comment]
Going to agree with the above. A hitscan laser with huge AP like this combined with the damage values is a tad bit too high. 10 damage for both modes seem alright, as it still does 30 damage then.

**Comment by Roland410** [comment]
Also you should probably mention that you're removing the teargas nade and the ziptie boxes to place this on the map.

**Comment by Jaraci** [comment]
With lower damage the burn laser mode tends to fall apart regardless of penetration and seems to have severe issues applying organ damage at all, which turns it into little more than a flashlight. I could solve this by making it single-shot instead of a pulse gun, but I'm somewhat sold on the idea of a pulse laser as-is.

I could cut the burn laser mode entirely and drop the damage on the new primary fire without too much issue, though.

**Comment by Roland410** [comment]
I still don't understand why people insist so much on every weapon having to fuck each internal organ of your target. 99.9% of the time your job is not to assblast your target, but to capture them.

**Comment by Sparrowbird611** [comment]
> I still don't understand why people insist so much on every weapon having to fuck each internal organ of your target. 99.9% of the time your job is not to assblast your target, but to capture them.

I get why they want it, since organ damage is the best way to cuck most people, since it's harder to recover from than just normal stuff, but in this case, it's security. I don't feel they even need heavy penetration weapons like this tbh, let alone "ORGAN DEATH MELTORATOR CANNON."

**Comment by Jaraci** [comment]
Without organ damage, energy weapons are essentially useless unless they just flat-out stun. Burn damage is 100% worthless -- it can't cause arterial or break bones or do anything except turn the target's screen white and potentially make him have a heart attack five minutes down the line. If a laser weapon can't carry over any of its damage into organs there is no point in using it; it is essentially non-lethal due to how brainmed works.

**Comment by Roland410** [comment]
Laser weapons evaporate your blood and that's why they are actually dangerous, not because they microwave your organs.

**Comment by AdamElTablawy** [comment]
@Roland410 All weapons must do organ damage to be useful as a weapon, due to the nature of brainmed.

If it merely applies damage without doing organ damage, then it's basically a glorified taser.

**Comment by Roland410** [comment]
@AdamElTablawy The real killer in brainmed other than straight up brain damage is... *drumroll* blood oxygenation. Low blood oxygenation is caused by lack of oxygen or blood, which lasers evaporate from you.

**Comment by AdamElTablawy** [comment]
@Roland410 Fair enough, but i'm not actually sure how much bloodloss this actually ends up doing.

**Comment by Roland410** [comment]
Considering you get 12x3 shots, assuming you only hit even half of that, that's 18x10 (with the suggested values), which should be 180 damage, more than lethal enough by itself, and you honestly don't need to do much damage to get someone below 80% oxygenization, so I'd go with quite major.

**Comment by AdamElTablawy** [comment]
Either way as it currently stands this is 'massive overkill: the gun'.

I'd have difficulty justifying taking anything else. With the amount of damage it does, it's easy to incapacitate someone, yet hard to kill them.

**Comment by BurgerLUA** [comment]
More feedback is needed for this PR. Maybe a poll is needed if no additional feedback is given.

**Comment by Jackofashepard** [comment]
Personally i think sec's in a fine spot with their new bullpups but this could have a place as a antag item.

**Comment by BurgerLUA** [comment]
Is this PR still being worked on? It's failing tavis and has conflicts.

**Comment by Superhats** [comment]
Closing this. It's conflicting, and the PR owner has left the server. Feel free to contact a maintainer to re-open it.

**Pull request closed without merging**
