### PR TITLE
GAS can now be passengers

### PR DESCRIPTION
**Pull request by Superhats**
Literally every other species in the game (Minus vox for obvious reasons) can be passengers.

### CODE REVIEW

**Comment by Roland410** [comment]
GAS are bred and trained for a specific job with our current lore afaik, so them just being passengers is a bit strange.

**Comment by Sparrowbird611** [comment]
Not really against this, but Roland does kind of have a point. Though you could argue GAS botanist and things like that could exist.

**Comment by Superhats** [comment]
Adherents are ALSO built with a specific job in mind, yet they can be passengers too. Just like an adherent investor, a GAS investor will be noticed quickly, and will probably get in trouble.

**Comment by Roland410** [comment]
Adherents were built to serve, it's a huge difference in my opinion. GAS have been trained by Xynergy to perform specific tasks.
Technically GAS are I'd say slave-like, while Adherents serve people as they have nothing else to do with their life.

**Comment by Superhats** [comment]
Still, I don't see why a GAS wouldn't be able to go off-duty, if anything.

**Comment by Superhats** [comment]
Surely they don't work 24/7, they _are_ sapient and that would take a toll on their mental health.

**Comment by BurgerLUA** [comment]
Needs a poll.

**Comment by ProbablyCarl** [comment]
Poll is a resounding 'no'.

**Pull request closed without merging**
