### PR TITLE
Redaction Counselor Buff

### PR DESCRIPTION
**Pull request by ZenoAntelic**
:cl: Antelic
tweak: Bumps up Redaction Counselors to Master, Coercion untouched.
/:cl:

### CODE REVIEW

**Comment by ZenoAntelic** [comment]
I'm a dumbass, and know this is abit stupid even, talked about it in discord. But the first way to seeing something change is action, not inaction. Please let me know how you fellers feel about this

**Comment by Squigger** [comment]
This instantly makes the counselor better than the entirety of the rest of the medbay staff, invalidating a lot of roles.
```

		if(redaction_rank >= PSI_RANK_MASTER)
			if(E.status & ORGAN_ARTERY_CUT)
				to_chat(user, SPAN_NOTICE("You painstakingly mend the torn veins in \the [E], stemming the internal bleeding."))
				E.status &= ~ORGAN_ARTERY_CUT
				return TRUE
			if(E.status & ORGAN_TENDON_CUT)
				to_chat(user, SPAN_NOTICE("You interleave and repair the severed tendon in \the [E]."))
				E.status &= ~ORGAN_TENDON_CUT
				return TRUE
			if(E.status & ORGAN_BROKEN)
				to_chat(user, SPAN_NOTICE("You coax shattered bones to come together and fuse, mending the break."))
				E.status &= ~ORGAN_BROKEN
				E.stage = 0
				return TRUE

		for(var/datum/wound/W in E.wounds)
			if(W.bleeding())
				if(redaction_rank >= PSI_RANK_MASTER || W.wound_damage() < 30)
					to_chat(user, SPAN_NOTICE("You knit together severed veins and broken flesh, stemming the bleeding."))
					W.bleed_timer = 0
					W.clamped = TRUE
					E.status &= ~ORGAN_BLEEDING
					return TRUE
				else
					to_chat(user, SPAN_NOTICE("This [W.desc] is beyond your power to heal."))
```

This gives the counselor the ability to mend everyone's organs, arteries and broken bones for free upon use, and most of their superficial wounds too. There is a reason guaranteed psionics in the form of the counselor and PADV are extremely limited. This is a no, in my opinion.

**Comment by ProbablyCarl** [comment]
As pointed out prior, this invalidates most roles in Medical, if not the entirety of Medical. There's a _very_ good reason we have them limited. The role is intended to be an RP role first and foremost, which is what it currently serves perfectly as. If you want to play Physician? Go Physician.

**Comment by ProbablyCarl** [comment]
Nothing more to discuss. Closing this for now.
The conversation has been had and councilor in regards to Psionics is fine as is. Everyone is in need of content, but getting _masterclass_? Oof.

**Pull request closed without merging**
