### PR TITLE
IPC's can use vey med prostheses.

### PR DESCRIPTION
**Pull request by chaoko99**
🆑 
tweak: IPC's are no longer restricted from vey med prostheses.
\ 🆑 
image

Keek is very handsome

### CODE REVIEW

**Comment by Keekenox** [comment]
You bet your ass I am.

**Comment by chaoko99** [comment]
make a cute boop for me

**Comment by Keekenox** [comment]
*beep

**Comment by Sparrowbird611** [comment]
I'd give the generic argument of "But then we won't know who the robots are!" but lets be real.

This already applies to FBPs. Adding it to IPC changes nothing, the only way to fix that is completely removing vey med. Good PR.

**Comment by chaoko99** [comment]
for the record Keek actually just straight asked me to do this

**Comment by chaoko99** [comment]
restarting build

**Comment by Keekenox** [comment]
Good PR good PR good PR 

image

**Comment by Ikmachek** [comment]
I got asked to sign off on this and I like it, FPBs can already try to pass as human and as far as I know the ban on Vey-Med was a Bay community problem.

**Comment by chaoko99** [comment]
WE WON BOYS

**Pull request merged**
