### PR TITLE
Security Armory, Permanent Holding, and (Emergency) Bridge remap

### PR DESCRIPTION
**Pull request by OolongCow**
Makes security's armory less terrible-looking. Adds a break room to security where the old locker room once was. Makes the emergency bridge usable (though much less secure) without an AI present. Makes permanent holding less of a death sentence (both literally and emotionally) for antags. Also, the TOC now has (some) purpose. And is accessible.

[Break Room](https://i.imgur.com/aRN0s6A.png)
[New Armory](https://i.imgur.com/XHm0iTT.png)
[Interview Room](https://i.imgur.com/Dink51E.png)
[Forensic Tech Office](https://i.imgur.com/Yxdje5V.png)
[Evidence Storage (With typical spawns)](https://i.imgur.com/rjH6zMS.png)
[Shutters Button](https://i.imgur.com/TgL21hD.png)
[New Main Area of Emergency Bridge](https://i.imgur.com/KfgJ4q7.png)
[New AI Inner Chamber](https://i.imgur.com/S6A4D0S.png)
[New Tactical Operations Center](https://i.imgur.com/Tsml77Z.png)
[New Perma](https://i.imgur.com/Vq40KqZ.png)

- [x] Remap armory
- [x] Make the emergency bridge usable
- [x] Replace old locker room with a break room
- [x] Make perma less hellishly boring
- [x] Miscellaneous security changes
- [x] Make the TOC mildly useful
- [ ] Pass Travis

Thanks to @Roland410 and @Sparrowbird611 for all the assistance.

:cl: OolongCow
maptweak: The security armory has been totally remapped. As has the security locker room.
maptweak: The secondary bridge's door is no longer bolted at roundstart. The only way it was possible to be unbolted was hacking three secure doors in a row, or an AI being in the game to push the door bolt button.
maptweak: Added a button to the emergency armory that requires bridge access which when pushed opens the shutters blocking the stairs up to the AI data chamber. With the above change, the secondary bridge is now actually accessible (though less secure) without an AI.
maptweak: The turrets on the secondary bridge have been moved into the internal chamber. Command will no longer be automatically shot for attempting to use the emergency bridge without an AI to disable the turrets beforehand.
maptweak: CO's office window shutters start the round closed to prevent red hardsuit man from effortlessly taking his incredibly valuable and important things while the rest of command watches in rounds without a captain.
maptweak: Security armory exterior now has turrets.
tweak: Security's number of ion pistols 2 -> 1
tweak: Security armory ammo amounts changed (almost universally removing the two boxes of a single ammo type and replacing them with one of each)
tweak: amount of ammo in boxes should now be more consistent (there's finally a box of buckshot with more than two holders in it!)
tweak: CoS's AMR replaced with an unloaded Tectonic. As a reminder, the Tectonic, due to the changes made for infantry, WILL NOT fire off of red alert without being authorized.
tweak: Security's frag shells removed (Makes zero sense that security can have them and not real bullets, and #961 will make them even more dangerous to the ship)
tweak: PPP removed while I try to figure out what the hell to do with it.
maptweak: Permanent Holding now has a nanomed!
maptweak: Pemanent Holding has also had its hydroponics area redone!
maptweak: Permanent Holding now has workout equipment and some vendors!
maptweak: The TOC is now actually accessible (from the bridge deck's maintenance tunnels, starboard aft). It requires head(or SEA!)-level access to open, and contains a myriad of useful monitoring computers, as well as the supplies to commit backwoods surgery, and a fully-kitted toolbox. Will most likely benefit the CE, CMO, and traitors the most.
/:cl:

### CODE REVIEW

**Comment by OolongCow** [comment]
I accidentally un-drafted this because my eyes hurt. Oof.

**Comment by OolongCow** [comment]
Reverting to an earlier commit to fix some things. Will need to redo some things that came after it, like the buttons.

**Comment by OolongCow** [comment]
Assuming this passes Travis, this should be the extent of my changes.

**Comment by OolongCow** [comment]
Travis is only throwing up a runtime. Reattempting.

**Comment by OolongCow** [comment]
I am fighting tooth and nail with Travis and these errors at the moment.

**Comment by OolongCow** [comment]
Travis is failing purely off of the back of a 2x3 area that I don't even want to use, but it is forcing me to, not having an APC (which it does) and a vent + scrubber. Can confirm said area works perfectly fine (since it's connected to an area that DOES have those things by a ladder opening).

**Comment by OolongCow** [comment]
At this point, I'm just trying to figure out which button opens windoors (since every button is limited in what it can open) so that I can implement the emergency open buttons as intended. Otherwise, should be feature complete and ready for review (as the Travis failure is a separate check it runs that has nothing to do with stability or failure to compile).

**Comment by OolongCow** [comment]
Will have to leave the PR here for now due to health reasons. The buttons will have to come later.

Again, the Travis failures are due to compile-agnostic checks for APCs and scrubbers/vents Travis does on its own. Something is up with it, though, because they **are** there and **do** work.

**Comment by Roland410** [comment]
The area Tactical Operations Center(/area/command/gunnery/mim) is not coherent, which means you've either reused the same area or it's cut apart somewhere, and it doesn't have an APC, air vent or scrubber in either place.

**Comment by BurgerLUA** [comment]
Needs additional feedback. Tell me when this is ready for a test merge.

**Comment by Tristan63** [comment]
ngl this is pretty hot

**Comment by BurgerLUA** [comment]
Failing travis and conflicts.

**Comment by Mastergodown** [comment]
It looks good seeing that its being more fun for players, but also I would recommend increasing its security. Its permanent sentencing. Ment to hold people for a long time. People can literally just take a stool and smack the window and grill a couple of times and they're out.

**Pull request closed without merging**
