### PR TITLE
Rework de void suits

### PR DESCRIPTION
**Pull request by ABAtilus**
Intento de reworkear algunos voidsuits para mas similitud a los de dead space.
Modifique los voidsuits de:
Seguridad
Mineria
RIG de mineria (El que debe acoplarse a la espalda)
imagen
imagen

Modifique los archivos:

icons/mob/onmob_head.dmi

icons/mob/onmob_suits.dmi

icons/obj/clothing/suits.dmi

icons/obj/clothing/hats.dmi

### CODE REVIEW

**Comment by Aurelien3189** [comment]
Could we get a comparison to the current suit sprites, and maybe the suits from the game? Just curious on what exactly changed about the look.

**Comment by BurgerLUA** [comment]
Needs more feedback.

**Comment by Jackofashepard** [comment]
I like them all except the sec one, needs a tiiiny bit more texturing

**Comment by Roland410** [comment]
I'm not sure if this was even intended to be PR'd here considering the language difference.

**Comment by Jackofashepard** [comment]
I mean translated it says 


I try to reworke some voidsuits for more similarity to those of dead space.
Modify the voidsuits of:
Security
Mining
Mining RIG (The one that must be attached to the back)

**Comment by Roland410** [comment]
Neither Super, or I like this PR, and after he asked about it in general feedback was negative. Closing.

**Pull request closed without merging**
