### PR TITLE
Bay Overmap sprites

### PR DESCRIPTION
**Pull request by Kaksisilma**
Ports bay overmap sprites.

## About The Pull Request

Ports bay overmap sprites

Capture

## Why It's Good For The Game

Looks better than ours tbh

## Did You Test It?

Yes

## Authorship

I didn't make those. This was ported from Bay.

## Changelog

:cl:
imageadd: New overmap sprites from Bay.
/:cl:

### CODE REVIEW

**Comment by Kaksisilma** [comment]
Capture

This is an alternative I had in mind, though I think it's better to first do those initial changes and then play around with color schemes.

## This green and black color scheme is not in use in this PR.

**Comment by SilverCelestine** [comment]
I prefer the blue one myself, though the green one would be interesting if it could be switched to as a "High Contrast" option. I approve of this though.

**Comment by N8-Toe** [comment]
I'm partial to the green and black. The low contrast on the blue one I find harder to read

Also put both through a color blind filter and found them both readable still.

**Review by Anton-Kr — APPROVED** [review]

**Comment by Cupax3** [comment]
Baysed

**Pull request merged**
