### PR TITLE
Crashed Fighter v2

### PR DESCRIPTION
**Pull request by gilvian**
This time the fucker should be working

## About The Pull Request

Adds a new exoplanet ruin

<details>
  <summary>How it looks, spoiler for those who want to see it in game</summary>
  
image

  
</details>

## Why It's Good For The Game
New exploration content

## Did You Test It?

yes :)

## Authorship

Me - I made it

## Changelog

:cl:
* rscadd - New exoplanet structure (Crashed Fighter)
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
Hello, can you please make some other push? GitHub is refusing to run CI.

**Comment by gilvian** [comment]
done

**Comment by gilvian** [comment]
:)

**Review by N8-Toe — APPROVED** [review]
Code looks good, and so does the map

Great work on the PR and getting things working

**Pull request merged**
