### PR TITLE
Adds attachments, removes gun safety overlays

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Adds gun attachments, removes gun safety overlays.

Adds a overlay remove for safety_icons, rather than an overlay cut.

Gun safety overlays, the ! and S icons are gone for the below reasons.
## Why It's Good For The Game
Attachments are good and add a lot of game mechanics which are neat, they let us move sprites and have BIGGER gun sprites in the future.

Gun safety overlays are a strange idea which at first sound useful, but you already have examining your gun for that, and the way the overlay is applied and the function of it working requires you to either have it 24/7 or make it literally make every other gun icon overlay tool be basically useless because you're gonna have to cut the overlays entirely, eventually.
## Did You Test It?
Yes, attachments work. The overlays for safety icons do not overflow like before, the safety overlay is gone.
## Authorship
MJP#4043, Pariah919, Dudeman100-Ckey
## Changelog

:cl:
add: gun attachies, not acquireable at any requesitions near you.. Yet.
del: Gun safety overlays, they were awful, awful code.
/:cl:

### CODE REVIEW

**Comment by BurpleBineapple** [comment]
> Removes safety_icons, they literally do not work and do nothing. I have no idea why its still in the code?

Hi, so, you know those S and ! marks next to your gun in bright green and red that show up if your gun is set to safe or fire respectively? That's what safety_icon is. It only shows up if you have above untrained gun skill. I'm unsure why you think those do nothing. Don't remove those.

**Comment by Pariah919** [comment]
>Hi, so, you know those S and ! marks next to your gun in bright green and red that show up if your gun is set to safe or fire respectively? That's what safety_icon is. It only shows up if you have above untrained gun skill. I'm unsure why you think those do nothing. Don't remove those.
>
3AM MJP was wrong, but I think I've already said that.

Safety icons are just the funny blinking light, the overlays for them work fine, apologies for being dumb.

The overlays ruling over the ! and S are however, insanely badly made. And I can't think of a way conceptually that wouldn't end up being finnicky in the end to make them apply and deapply properly, outside of ruling it to a possible proc, but that'd require you to change the safety most likely, which would be strange to make it work, and honestly I don't think its that important as a gameplay mechanic. The original makes had an overlay cut for a reason, I'd imagine.

**Comment by Anton-Kr** [comment]
I am honestly fine with us losing the ! S. I'll let other maintainers weigh in on this, but imho it's worthwhile to lose that so we can make funky attachments.

**Comment by Anton-Kr** [comment]
Following discussion, PR author will attempt to make alternative to current overlay safety system.

**Pull request closed without merging**
