### PR TITLE
Engineering Remap

### PR DESCRIPTION
**Pull request by Aurelien3189**
### Headline

Essentially a hand made remap using Bay's current layout, intended to open up engineering to provide a more 'comfy' feel to it in the sense that everything from suit prep, to locker prep, to moving five meters to the right don't require engi mains to shuffle through single file lines.

Makes small additions to their gear and second deck maintenance to feel a little more than just a bunch of hollow passages with stuff shoved in.
Engi Bay: https://streamable.com/5g73mp
Maint: https://streamable.com/5g73mp
Hard Storage: 
image
Also engi bay: 
image

In a nutshell:

-Removes certain walls and doors in engi Bay (bay monitoring room walls, engine monitoring room's second airlock/locker room door, hard storage walls)
-Moves locker room to the left side of engineering, with monitoring adjacent to the engine room monitoring
-Adds small lounge (some tables and chairs) to engi bay
-Gives autolathe small workshop space (tables and chairs)
-Makes D2 teleporter and engi storage shutter connected rooms tucked on the left side of engineering, makes 2 tile hallway near ladders for future mapping plans (Supply trolley elevator?)
-Makes D2 cargo storage actually store useful stuff, like materials, stamps, and package paper instead of this messy useless closet
-Tucks atmos canister storage room near elevator and adds 2 of every canister
-Adds phoron tanks to hard storage
-Adds wall first aid vendors to engineering to appease Aerospace Sanitation inspectors

### CODE REVIEW

**Comment by Roland410** [comment]
Needs pics as the mapdiffbot shit itself as usual.

**Comment by SilvernKell** [comment]
> Needs pics as the mapdiffbot shit itself as usual.
> Also considering this is the Bay remap redone by hand, I'm gonna downvote anyways, as I really dislike it.

Glad it's not copyrighted then

**Comment by Roland410** [comment]
> > Needs pics as the mapdiffbot shit itself as usual.
> > Also considering this is the Bay remap redone by hand, I'm gonna downvote anyways, as I really dislike it.
> 
> Glad it's not copyrighted then

Agreed.

**Comment by SilvernKell** [comment]
*Tailwave*

The carpeted area is strange imo
Remove the windows on the mats because it makes me so angry that you don't have access to them just by having lobby access, please?
Very good work, thank

**Comment by Aurelien3189** [comment]
Any idea how to solve these issues? ALso, it prompts me to place scrubbers/vents in maint, is that a thing we do? 

image
image

**Comment by ProbablyCarl** [comment]
Oh. Conflicts. 
As is tradition.

**Comment by Roland410** [comment]
Usually there are no vents/scrubbers in maint, I don't recall where it would be on the current map, but may need to change the unit test then.

**Comment by Tename** [comment]
I don't know if I am a big fan of everything being so open. I also think that break area with the carpet looks really out of place.

**Comment by BurgerLUA** [comment]
Seems to be a lot of work done on this. Is this WIP?

**Comment by Aurelien3189** [comment]
There's no work currently being done, besides the occasional extra details. 

Should be finished by now.

**Comment by ProbablyCarl** [comment]
We'll do another test merge, and if it's working well, we'll fully merge it.

**Comment by Aurelien3189** [comment]
Awesome, by then, I'll be around to ask for feedback like last time, hoping to stay in touch with the players.

**Comment by Aurelien3189** [comment]
What do I do about this? 
image

**Pull request merged**
