### PR TITLE
ARMORY CHANGE: THE MUSICAL

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
Hi, all. This is gonna be my first semi-seriously written PR.

What this does is it removes the heavy equipment from the heavy armory in the brig, **BUT-** adds a bunch of materials to add to the weapon printer, adds quite a few _guns_ to the weapon printer, lowers the print time of weapons from 5 minutes to 25 seconds, and lowers the prerequisite research levels for a lot of weapons, some of them to base!

**Why?**

A lot of reasons! For one, Brig Chief never actually, uh, did anything. He stood in the doorway. Now, he has a little window in the armory named the 'requisitions desk' that security guards are able to request equipment at. For another, nobody USED half the weapons in the armory. It was a mad dash for the combat shotguns, with the loser getting a laser carbine, and one *really* unlucky fucker grabbing a bunch of smartguns.

There may be balance changes on this in the future.

'But BEARRR it's too EASY to get through a windoor' haha fuck you the armory has NORMAL WALLS

**Why this is good for the game**

Gives the BC something to do, allows an adaptable armory for adaptable situations, makes it so that you can't just piss guns into the wind and have to actually suffer consequences for losing one.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
this concept is obviously in the early stages and will be for a while. i have purposely included more mats than i think will be necessary and will be balancing as such in mnid in the future.

**Comment by AdamElTablawy** [comment]
Why would you print anything but tons of combat shotguns then?

**Comment by bearrrrrrrr** [comment]
@AdamElTablawy combat shotguns are not the end-all-be-all. they will also probably just cost more if it ends up with people spamming them. they use plastic, which is already part of a limiting resource

like i said before, values WILL be changed. this is to get the concept out and start adjusting it

**Comment by Roland410** [comment]
Needs pics, and list of changes, also I'm making an alternative to this PR today.

**Comment by Sparrowbird611** [comment]
I feel security should really have to rely on another department to get more weapons, like science or supply.

If the issue is brig chief having to do something, I don't see how this fixes it. It just means he has to click a few buttons every shift, which isn't exactly amusing.

And as you literally say in this PR, it means we don't have two guys with combat shotguns, two with laser carbines, and two with smartguns, we have four with combat shotguns and the rest with whatever they could scrounge up because the BC spent all the resources on one of the best gun options in the game.

**Comment by bearrrrrrrr** [comment]
@Sparrowbird611 

>combat shotguns are not the end-all-be-all. they will also probably just cost more if it ends up with people spamming them. they use plastic, which is already part of a limiting resource
> 
> like i said before, values WILL be changed. this is to get the concept out and start adjusting it

and yes, they are going to have to rely on supply for mats and for gunz if they print too much

as for 'it doesn't actually give the BC anything to do', walking up to the desk and being like 'hello, yes, gun please' is a good bit 

i talked to quite a few sec players, none of them seemed to have a problem with it. if it turns out to be a balance problem, it will be fixed.

**Comment by bearrrrrrrr** [comment]
changed print time from 25sec to 30sec as per roland's suggestion that print time may be too short. this is a 20% increase.

**Comment by BurgerLUA** [comment]
Needs a poll. Please summarize the changes in 1-2 sentences.

**Comment by AdamElTablawy** [comment]
if you hAve to do this, don't gate the shotguns behind plastic, cargo can get moore of it

put the better weapons behind rarer materials, like diamond

**Comment by bearrrrrrrr** [comment]
i am by no means going to put a shotgun behind diamonds. not only does that make no sense, it...also, could be acquired from cargo?? that would punish SCIENCE more than sec if all of the high-importance mats had to go to them

**Comment by bearrrrrrrr** [comment]
@BurgerLUA summary:

'Removes the huge stock of weapons from the heavy armory at round-start that allowed Security to immediately heavily-arm themselves for any threat within twenty seconds. Adds it so that Security can now properly print their own weapons, leading to more flexibility to respond to threats while giving the Brig Chief a job (printing, distributing weapons through requisitions window).'

**Comment by AdamElTablawy** [comment]
@bearrrrrrrr 

Cargo can order 10 sheets of diamond, or 50 sheets of plastic.

Hence, materials like diamond-or osmium, or whatever else rare material that's harder to get-gate security out of the bullshit strong stuff better than just plastic.

Otherwise, like I kept telling you, it's just going to lead to security nagging cargo for extra plastic, which negates the 'resource scarcity' part of this as a limiter. At least when it comes to the rarer materials, it's harder to get a fuckton of it.

I'd prefer if every sec officer couldn't have a combat shotgun, basically.

**Comment by BurgerLUA** [comment]
Map Conflicts

**Comment by bearrrrrrrr** [comment]
what in the fuck

**Comment by BurgerLUA** [comment]
Your PR doesn't have Travis for some reason.

**Pull request closed without merging**
