### PR TITLE
removes deity from the votable antag pool temporarily

### PR DESCRIPTION
**Pull request by AdamElTablawy**
it's a buggy piece of shit podunk abandoned gamemode

satisfies nobody

### CODE REVIEW

**Comment by Roland410** [comment]
I personally like deity, and going down on this road means we'll only have traitor and extended in the end.

**Comment by AdamElTablawy** [comment]
it's literally fucking broken roland

**Comment by MemedHams** [comment]
Adam, it has various small bugs but 3 am nightcode to delet gamemode won't fix that. Fix the minor cam bugs, the errors with tower spells, and the language issues with Starlight Herald and Tower created cultists and we've got a mostly functional gamemode, which is generally the standard of our other gamemodes and antags.

**Comment by Sparrowbird611** [comment]
Eh, deity has issues, but I don't agree with disabling it, except for the starlight herald. Nar nar and the tower need tweaks currently, and should stay. I wouldn't object to disabling starlight though, as it's gamebreakingly broken with the god form rn, among other issues.

**Comment by AdamElTablawy** [comment]
@MemedHams 

'various small bugs'

No, the entire gamemode is broken.

One of the cults literally does not work. Like, almost all of it. Only the talismans in starlight herald function correctly-the rest literally don't work properly. The deity is 'godmoded' but feels pain, and godmode doesn't pay attention to broken bones, dismemberment, etc, so it can still be fucking decapitated outright. Almost none of its abilities function. 

A fair portion of the spells of the starlight herald and the tower need wizard robes to work, which they don't spawn with.

Blueforged literally just die instantly when doing anything.

For the nar'sie cult, most of its abilities are functional, barely, but it's so hilariously underpowered it'll take ages just to fix its issues before it can be implemented.

Likewise, for The Tower, it hits endgame the moment the round starts-you can build altars literally anywhere, including on another fucking planet, and since altars are all that cap's the deities' power, it gets infinitely strong, incredibly quickly, which is a major balancing concern.

The god cannot see in the dark, see its cultists properly, and none of its abilities have visible cooldowns and most do not have feedback for use. The god cannot mass-message its own cultists. It can't even tell if it converted someone or not-there are no HUD icons. It can't tell where a new structure was built, or jump to them when destroyed. It cannot see if someone's dead or not. 

And every time it uses a fucking ability or gives its cultists one, admins get a log. Give a cultist a spell? Log. Use an ability? Log. Given that shit like the tower involves giving your cultists 20 fucking spells, this drives admins nuts.

Oh, and sometimes the abilities just straight up all stop working. The Tower is the least bugged of all of them, and 5 of its spells literally do not fucking function.

And that's not even getting into the balance of it in detail.

Everything about this fucking mode is broken, and what's not broken is only barely functional, and what's not barely functional is unbalanced, and what's not unbalanced is just fucking unfinished.

There isn't even a real endgame or goal for anything aside from the Starlight Herald, and about 80% of the Herald is fucking broken. Its custom species are broken. Its spells are broken. The endgame is broken.

Everything else just kind of meanders along and about thirty minutes in the deity has too much passive power gain and regen to do anything about and destroying its altars doesn't even do anything at that stage.

So yes. Disable it. It does not function. It is an UNFINISHED gamemode. It was like putting Hand of God into the rotation on TG. It needs to be fixed before it can even be put in, because at this time, the current gamemode literally stops working if an admin isn't online to fix the bugs as they occur and spawn cultists wizard robes, etc etc.

**Comment by Jaraci** [comment]
Adam is right. Speaking from a staff point of view, deity (and to a lesser extent, cult) usually devolves into ticket hell if the deity doesn't pick Tower. So many things are broken with the other two gods that it's not even funny.

**Comment by BurgerLUA** [comment]
I put a poll up for this. If it's very close then I won't be merging this PR.

**Comment by ProbablyCarl** [comment]
Already done server side.

**Pull request closed without merging**
