### PR TITLE
Horrible Atomization, the PR.

### PR DESCRIPTION
**Pull request by ProbablyCarl**
- - -
Map:
 - Examination room provided to Medical.
 - Psych's room downsized quite a bit.
 - Cremation room moved from Medical to Chapel.
 - Radio Host's studio returned. See below.
- - -
New Toys:
 - Landmines reintroduced. Rejoice. These are available for traitors via the uplink, primarily. Watch where you walk.
 - Sutures fully added, taking them directly from a PR of MJP's, with his permission. You use these to seal up wounds that have arterial bleeding, without surgery required. You can find these in advanced first aid kits, combat kits and surgical kits. This permits the Combat Medic to do in field wound closing.
- - -
Other:
 - Radio host reintroduced. More-or-less a carbon copy of the previous PR, with a new studio to accompany it. See map diffs. I don't think I need to explain this role too heavily.
 - Retaliate version of giant spiders added, for the sake of events and admin fuckery. Additionally, one has been provided to the Radio Host as a pet. This is a horrible idea.
 - Renames Sol Federal Agent to Sol Agent, for the sake of differentiating it from the Federal Agent.
- - -

### CODE REVIEW

**Comment by N8-Toe** [comment]
I think arterial bleeds should still require surgery to fix. And any tools given to field medics should just slow them. Injured crew needing to leave a fight is a feature

**Comment by ProbablyCarl** [comment]
Man. Now it won't run the checks at all. Wacky.

**Comment by Cupax3** [comment]
This is failing a power net check, do not ignore CI.

**Comment by anconfuzedrock** [comment]
There is already a way to heal arterial bleeds without surgery, a bicard overdose. That has a lot of downsides, though. I think adding another one that's even easier is going to upset some things. Turning arterial bleeds from a major threat into a 5 second fix is fucking massive.

**Comment by Yurek1** [comment]
> There is already a way to heal arterial bleeds without surgery, a bicard overdose. That has a lot of downsides, though. I think adding another one that's even easier is going to upset some things. Turning arterial bleeds from a major threat into a 5 second fix is fucking massive.

bicard OD is not 100%, in fact i've found it works almost none of the time

**Comment by ProbablyCarl** [comment]
Going to put this on hold for a hot minute. Might abandon it. Other stuff is being worked on locally.

**Pull request closed without merging**
