### PR TITLE
Ascent Seedship Consistency

### PR DESCRIPTION
**Pull request by miniusAreas**
## About The Pull Request
A variety of mostly cosmetic changes to the Seedship. Replaces some floors with the tiling and catwalk the rest of the ship has, removed the blue Tiled decal (due to said decals reserved for Tiled floors) from the Carbon Medbay, and added labels to the doors that were missing them (mostly all).

Changes the normal station lights in the Tiro quarters and Carbon Medbay to Mantid lights (like the rest of the ship.

moves the Nutrient Dispenser to the feeding chamber (because why would you eat where you shit, so to speak.)

Adds additional doors to the area the Torpedo system is in, and splits the front airlock turret into two (because who walks out of their hightech supership into a fuckin TURRET. Seriously? Come on.)

Images of effected areas.
image
^ Carbon Treatment Chamber
image
^ Tiro Quarters
image
^ Extra doors separating the Throne Room from the Torpedo Bay
image
^ New Turret Layout (for the front door)
## Why It's Good For The Game
consistancy makes my brain go brrr, and it's good to have. Even more so when you're the best species in the galaxy (supposively)
## Did You Test It?
made with fastDMM2. Tested on local branch, no issues.
## Authorship
entirely made by @miniusAreas, with love and care <3
## Changelog

:cl: miniusAreas
tweak: fixes various inconsistencies around the Ascent Seedship, such as lights, flooring, and door names. Moves the food dispensers to the Feeding Chamber.
/:cl:
## Authors Notes
Whoever did the Tiro edits is clearly a novice, but better than most. Bravo to you. Just cleaning up your small mistakes, and well done! You've impressed me with how little I had to fix. <3

############################

### CODE REVIEW

**Comment by ShadeAware** [comment]
The tiro lights were not ascent for a reason; the constant blue is a fucking pain. Please change them back.

**Comment by ShadeAware** [comment]
Additionally, removing the table and food dispenser and putting beds... why? What? Why are there beds? The Tiros have a cryo chamber to sleep in, they don't get beds; you've made changes to random things for little to no reason, and the end result has become worse for it.

**Comment by Anton-Kr** [comment]
Make areas coherent, readd food dispenser. Don’t really care about rest of above because mostly flavor.

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
Readd food, fix ci

**Comment by miniusAreas** [comment]
> 

Food is in the feeding area. Unsure what you mean by re-add.

**Comment by githubuser4141** [comment]
> The tiro lights were not ascent for a reason; the constant blue is a fucking pain. Please change them back.

Agree, the blue lights are horrendous and should be removed entirely. Flavour is nice but shouldn't make it physically uncomfortable to look at especially when they're in 99% of the ship and you can't even replace them IIRC.

**Comment by miniusAreas** [comment]
> > The tiro lights were not ascent for a reason; the constant blue is a fucking pain. Please change them back.
> 
> Agree, the blue lights are horrendous and should be removed entirely. Flavour is nice but shouldn't make it physically uncomfortable to look at especially when they're in 99% of the ship and you can't even replace them IIRC.

If the lights hurt peoples eyes, than that is for a different PR. Might do that in a hot second. However, that has to do with the lights themselves, and not the mapped-in objects specifically for this map.

**Comment by miniusAreas** [comment]
> Readd food, fix ci

Food exsists, CI is now green. We're golden to await merge.

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
