### PR TITLE
Adds tilt (lean)

### PR DESCRIPTION
**Pull request by ghost**
Courtesy of Baystation's @gy1ta23 and @JoeyNosegay.
# Why it's good for the game
Lean.

### CODE REVIEW

**Comment by gilvian** [comment]
no, please

**Comment by ghost** [comment]
> no, please

<details><summary>It's happening.</summary>

image
</details>

**Comment by gy1ta23** [comment]
its tilt bitch not "Lean."

**Comment by ghost** [comment]
> its tilt bitch not "Lean."

Lean manufacturing (also known as lean production, just-in-time manufacturing and just-in-time production, or JIT) is a production method aimed primarily at reducing times within the production system as well as response times from suppliers and to customers.

It is derived from Toyota)'s 1930 operating model "The Toyota Way" (Toyota Production System) The term "Lean" was coined in 1988 by John Krafcik, and defined in 1996 by James Womack and Daniel Jones to consist of five key principles: "Precisely specify value by specific product, identify the value stream for each product, make value flow without interruptions, let customer pull value from the producer, and pursue perfection."

Companies employ the strategy to increase efficiency. By receiving goods only as they need them for the production process, it reduces inventory costs and wastage, and increases productivity and profit. The downside is that it requires producers to forecast demand accurately as the benefits can be nullified by minor delays in the supply chain. It may also impact negatively on workers due to added stress and inflexible conditions. A successful operation depends on a company having regular outputs, high-quality processes, and reliable suppliers.

**Comment by Anton-Kr** [comment]
tilt yourself some bitches

**Review by N8-Toe — APPROVED** [review]
Code looks good

**Pull request merged**
