### PR TITLE
New Shoal Scavenger ship 

### PR DESCRIPTION
**Pull request by CrackParrot11**
This is a port of the Baystation pr. https://github.com/Baystation12/Baystation12/pull/28082
I have done some minor tweaks to allow  Armalis spawns to be apart of the Shoal crew. I also tweaked the spawn numbers from originally 12+ 2 Armalis down to 8+2 Armalis spawns. The Shoal asteroid is now a giant spaceship with its own built in medical bay, chemistry, Atmospherics, Engineering department and Botany zone. With this, hopefully Vox should not be so dependent on admin intervention to get too places, as the Shoal ship has its own docking area with a Shoal shuttle attached. All Shoal crew can now have different job titles with a Quill as the leader of the group. The job titles are Shoal scavenger, Shoal biotechnician, Shoal technician, Quill and Shoal Armalis.

### CODE REVIEW

**Comment by CrackParrot11** [comment]
This port has been tested locally with no run time issues however, a test merge is still needed.

**Comment by Roland410** [comment]
Not sure if an away site with 10 slots total is a good idea or not. Seems like too many people, especially voxes.

**Comment by CrackParrot11** [comment]
The original spawn slots were 12. I can lower it to 6.

**Comment by Roland410** [comment]
That seems like a good amount. To be fair my worries mostly come from them deciding to raid the Dagon or such, as even mercs only have 6 people iirc.

**Comment by CrackParrot11** [comment]
My original goal was to get them to be in a better position were they can raid the dagon if they felt like they could do it. Not many people play vox. Because of the really poorly designed map we have for them now.

**Comment by Roland410** [comment]
I don't really feel like that'd be a good idea that can spawn somewhat frequently.
4 vox and 2 armalis raiding the Dagon as provocateurs will result in bloodshed. If this were to be a gamemode, I'd be totally on board, but as a thing that can occur normally, not a fan.

**Comment by CrackParrot11** [comment]
The away site spawn chance was unchanged from its original spawn chance. But this away site has more than just raiding equipment it also has mining equipment and lots of empty space for construction and its own shuttle. Raiding parties are only a single option on what they can do. I might also add in a little room with a destructive analyzer and a protolathe and circuit board printer so Shoal techs can reverse engineer human and alien tech.

**Comment by Roland410** [comment]
Current Vox away site spawns often enough, that's what I'm saying. Also idk about adding a protolathe. It would mean they have access to very powerful stuff including stealth tech for rigs, AEGs etc.

**Comment by Armyguy** [comment]
Yea i don't think the R&D is needed as the new ship gives them a LOT more to do now if it gets added. but @CrackParrot11 you may want to look at replaceing the burn room walls with the super walls that can't melt

**Comment by Armyguy** [comment]
@BurgerLUA and i don't think them droping to 6 is needed giveing that the rock bugs have 9 slots for them and they are a off map, i think 8 or 9 for vox can work too.

**Comment by Sparrowbird611** [comment]
8 seems like the optimal number. One armalis, the quill captain with the option of being either form of vox, and then the rest primalis.

**Comment by Sparrowbird611** [comment]
Just my opinion, but I would buff their gear numbers a little bit. One pair of thermals, two NKV goggles, and three mesons seems like a fair number. As it stands, vox have eight pair of thermals currently. This is a pretty hard nerf to that number.

**Comment by BurgerLUA** [comment]
Good PR, would be good for a test merge when you're happy with the state of it. Just tell us when.

**Comment by CrackParrot11** [comment]
Map preview https://imgur.com/a/rzL5804

**Comment by MarinaGryphon** [comment]
so apparently you deleted the actual file and committed the backup file, FUCK

**Comment by CrackParrot11** [comment]
Making a cleaner pr for this.

**Pull request closed without merging**
