### PR TITLE
cryo office made public I hope I merged it this time

### PR DESCRIPTION
**Pull request by YuiY1997**
About The Pull Request

Changed access of the Vacant Cryo Office to be crewmembers instead of heads. Added a few chairs. Made access to fax machine in the office public. Renamed it to Public Office
Why It's Good For The Game

The space might actually get used now and the public fax machine gives players more chances to use the clerical kit traitor item
Did You Test It?

Yes
Authorship

Ckey YuiY1997
Changelog

🆑

    maptweak
    Changed access of the Vacant Cryo Office to be crewmembers instead of heads. Added a few chairs. Made access to fax machine in the office public. Renamed airlock to Public Office and fax machine department to Public Office
    /🆑

### CODE REVIEW

**Comment by YuiY1997** [comment]
I still have no idea what I'm doing right now

**Comment by YuiY1997** [comment]
holy shit I have no idea what the errors mean

**Comment by YuiY1997** [comment]
image
what the fuck does this mean

**Comment by YuiY1997** [comment]
I think it should work without breaking shit now

**Review by N8-Toe — APPROVED** [review]
looks good

**Pull request merged**
