### PR TITLE
Return of the Resomii

### PR DESCRIPTION
**Pull request by Konater**
Now we can finally punt Cloud into the microwave and hold that wedding.

Whitelisted like gyne and armalis to satisfy Carl.

tesh_WO_anime2

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
I see no downsides.

After all, who else would I put in the chemical grinder?

**Comment by SpessFloof** [comment]
Yee, the station needs avali. Although they shouldnt be whitelisted.

**Comment by AdamElTablawy** [comment]
No.

**Comment by BurgerLUA** [comment]
Was this ever at all discussed with staff before a PR was made?

**Comment by Konater** [comment]
> 
> 
> Was this ever at all discussed with staff before a PR was made?

haha no

**Comment by CrackParrot11** [comment]
No more fucking races reee

**Comment by Jaraci** [comment]
I don't know what these are but I heard a lot of controversy about them

I feel kind of like I missed out because of this and so I see it as follows:

if they are bad I get to join in on complaining about them with all the other cool kids
if they are good, they are good and there is no problem

**Comment by Jaraci** [comment]
also if we got plasmamen surely we can get these

**Comment by chaoko99** [comment]
Absolutely not.

**Comment by Don2137** [comment]
I'm on board with omi.

**Comment by ariever** [comment]
no no no
no no
no
no no
no no no
please
please no
no more
don't do this

**Comment by MarinaGryphon** [comment]
> > Was this ever at all discussed with staff before a PR was made?
> 
> haha no

It was! I said not to make it and that it was a waste of time.

**Comment by ariever** [comment]
for those that don't know, resomi are short fragile raptor-bird things 
people who play this usually play them as annoying as possible, often times metaganging together as they do so which is why they have a bad rep sheet
as an admin i DO NOT want to have to police the usual people along with more baby-talking alien races that wanted to metagang on someone because he told one to fuck off

**Comment by Andromeda-K22** [comment]
I actually vetoed Resomi back when I was maintainer.

If I was still staff, I'd veto it now.

NO.

**Comment by MarinaGryphon** [comment]
`## UNIT_TEST ##: [UNIQUENESS: Languages Shall Have No or Unique Keys]: Language Keys - v - The following entries have the same value: /datum/language/corticalborer and /datum/language/resomi
## UNIT_TEST ##: !!! FAILURE !!! [UNIQUENESS: Languages Shall Have No or Unique Keys]: 1 issue with language datums found.`

`## UNIT_TEST ##: !!! FAILURE !!! [MOB: Resomi damage check template]: Damage taken: 5.4 out of 4 || expected: to take standard damage [Overall Health:50 (Initial: 100]`

`## UNIT_TEST ##: /datum/gear/suit/resomi - : Did not find the icon state '' in the icon ''.
## UNIT_TEST ##: /datum/gear/uniform/resomi/science - /obj/item/clothing/under/resomi/science: Did not find the icon state 'resomi_science' in the icon 'icons/obj/clothing/species/resomi/uniform.dmi'.
## UNIT_TEST ##: /datum/gear/uniform/resomi/dress - /obj/item/clothing/under/resomi/dress: Did not find the icon state 'resomi_dress_cap' in the icon 'icons/obj/clothing/species/resomi/uniform.dmi'.
## UNIT_TEST ##: /datum/gear/uniform/resomi/uniform - /obj/item/clothing/under/resomi/uniform: Did not find the icon state 'resomi_captain' in the icon 'icons/obj/clothing/species/resomi/uniform.dmi'.
## UNIT_TEST ##: /datum/gear/uniform/resomi/formal - /obj/item/clothing/under/resomi/formal: Did not find the icon state 'resomi_captain_formal' in the icon 'icons/obj/clothing/species/resomi/uniform.dmi'.
## UNIT_TEST ##: !!! FAILURE !!! [LOADOUT: Entries shall have valid icon states]: One or more /datum/gear definitions had paths with invalid icon states.
## UNIT_TEST ##: /datum/gear/suit/resomi: Missing display name.
## UNIT_TEST ##: !!! FAILURE !!! [LOADOUT: Entries shall have name, cost, and path definitions]: One or more /datum/gear definitions had invalid display names, costs, or path definitions`

`## UNIT_TEST ##: [CULTURE - All Species Cultural Values Shall Be Of Valid Types And Length]: Default cultural value '???' for Resomi tag 'faction' does not match culture datum category (home_system must equal faction).
## UNIT_TEST ##: !!! FAILURE !!! [CULTURE - All Species Cultural Values Shall Be Of Valid Types And Length]: 1 invalid cultural value(s)`

**Comment by BurgerLUA** [comment]
just going to add all the labels because this PR is a big fucking what

**Comment by peeesh** [comment]
but burger, m-muh cute birds

**Comment by bearrrrrrrr** [comment]
no longer an admin but i will join staff team again just so i can leave staff team if this gets merged

**Comment by Tename** [comment]
I think this is a horrible idea, but could you upload pictures of the species sprites, the Iconbot one is really hard to see.

**Comment by ProbablyCarl** [comment]
You have them whitelisted, which is great. I remember stating I'd allow introduction, if they were whitelisted. For obvious reasons, given the cliques they create.
They're intended to be angry spearchuckers of low intelligence. Not cute shitbirbs. If they're merged, we'll be creating them into such.
This was also discussed months ago, so anyone around now wouldn't have been aware of such a stance.

**Comment by SilvernKell** [comment]
Whitelist me bro
why do they have to be dumb tho

**Comment by Andromeda-K22** [comment]
because 'uwu cutebirb bullshit' as i put it many months ago is fucking
annoying to police and they're retarded birds anyway

they're not getting merged anyway because of overwhelmingly negative
community feedback

**Comment by SilvernKell** [comment]
I don't really understand, because low intelligence generally makes them more "uwu cutebirb" and less capable in jobs.

**Comment by ariever** [comment]
dumb isn't cute

**Comment by ProbablyCarl** [comment]
We'll put this on ice for now. I'll not close it, but we'll return to it at a later date. 
Currently, a very large number of individuals don't want it, due to the cliques and mentality it creates.

**Comment by chaoko99** [comment]
I don't think I want to see the return of the borderline self-antagging that Resomi did on bay either.

**Pull request closed without merging**
