### PR TITLE
adds xenophages back

### PR DESCRIPTION
**Pull request by anconfuzedrock**
FAQ:
**"Did you test this?"**
uhh, it compiled.
**"Why didn't you test this?"**
Look man, it's a gamemode for multiplayer primarily, how about you just testmerge it?
**"Any... other reasons?"**
Yeah, I don't have any fucking clue what a xenophage is, I think it's resprited, scary aliens? and I want it to surprise me. But also mostly yes because i know nothing I wouldn't know what to test!
**"Why does this pr add fewer lines than Loaf's pr removed?"**
No fucking clue- actually I remember one thing loaf's pr removed was just 3 paragraphs of commented out old code.
I didn't readd that  because it was unnecessary.

If this pr gets merge conflicts I may do something bad.

### CODE REVIEW

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
Resolve warnings.

**Comment by anconfuzedrock** [comment]
omg im sorry this is going to SUCK to squash but I forgot how to squash and it's really fucked me up in the past so NOW IS NOT THE PR to FIND IT OUT

**Comment by anconfuzedrock** [comment]
finally!

**Comment by Anton-Kr** [comment]
>uhh, it compiled.

based

**Comment by ProbablyCarl** [comment]
We'll be test merging this remotely, to test it as a gamemode for a round.

**Pull request merged**
