### PR TITLE
Reduces TC on ID, voice changer and compressed matter implant

### PR DESCRIPTION
**Pull request by Jackofashepard**
:cl:Jackofashepard
tweak: Compressed Matter Implant 32 ->22 TC
tweak: Agent ID 12 -> 8 TC
tweak: Voice changer 20 ->10 TC and description edited to reflect that it DOES NOT function as a gas mask
/:cl:

### CODE REVIEW

**Comment by Jackofashepard** [comment]
While the ID and voice changer are fun for "Haha i am the captain and i xxx" or being real cool and calling yourself Agent 47 it doesnt really serve much purpose aside from cosmetics. As for the compressed matter implant it simply wasnt worth the TC for its gimmick, hopefully now it'll see more use.

**Comment by Sparrowbird611** [comment]
Agent's ID might need to be raised ever so slightly, up to 8, but otherwise seems fine to me.

**Comment by Jackofashepard** [comment]
Raised to 8

**Comment by BurgerLUA** [comment]
Travis errors

**Comment by Jackofashepard** [comment]
No idea why this is erroring, compiles fine on my end

**Pull request merged**
