### PR TITLE
Officer sword update

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
https://streamable.com/ro390z
image

Officer sword rework.

image <- swords

Swords are now bulky, require a sheath to be put anywhere (Though most sources of swords will give you a sheath in the first place)
Cuts out 2 of the blades, we don't need 4 blades running around. There's no real need for a difference between officer and NCO swords in the short term, I can readd them later.
Updates the slashing sounds to be less awful.
New unsheating sounds for swords.
New sprites for swords. Thanks to Dongwaiver for the pallete, and thanks to Dongwaiver for the sheath!
Swords deal a bit more damage inexchange for the size increase.

## Why It's Good For The Game
Swords feel a bit more unique overall now, and have a downside for their huge huge damage bonus compared to most other weapons. I might rerework them later to be a bit more unique but this is a good first step.
## Changelog
:cl:
add: Sword sheaths and new sword sprites (pallete by dongwaiver, sprites by me.)
del: the old sword sprites.
balance: Swords are now bulky and require sheaths. They deal a bit more damage.
/:cl:

### CODE REVIEW

**Comment by Anton-Kr** [comment]
The sprite, at least the Fleet one isn't that good tbh

**Comment by Kaksisilma** [comment]
Capture

**Comment by Pariah919** [comment]
Fixed the unit test thing

**Comment by Kekakaka** [comment]
That force divisor is a bit overtuned there bud.

**Pull request merged**
