### PR TITLE
Getting relaced comes with drawbacks 

### PR DESCRIPTION
**Pull request by Jackofashepard**
🆑 Jackofashepard
tweak: upon relace your eyes are blurry and you are slowed for 5 minutes
/🆑

### CODE REVIEW

**Comment by Dark1Star3s** [comment]
30 minutes? GOD PLEASE NO. I already know what that is like, and it's not fun. At all. 5 minutes at best if I am being honest. Being slowed is just... not fun.

**Comment by Jackofashepard** [comment]
Changing to 5 minutes

**Comment by Jackofashepard** [comment]
It ended like it arrived, a dumpster fire

**Comment by JohnBigless** [comment]
We did it, boys.
Shoelace nerf is no more.

**Pull request closed without merging**
