### PR TITLE
Customization cleanup and addition

### PR DESCRIPTION
**Pull request by SilvernKell**
🆑3l3ctr1c5h33p
:tweak:Vox sprite is colourable now, with scales marking available. Fix your chars!
:tweak:Adds Veteris Cobra hood marking, Eastern dragon tail, some wing things. Removed unused tesh bits.
/🆑

DELETES:
-Teshari markings + accessories + basepart + Hairs + ears from dmi's
-references to them in the code
Reason: They only work on teshari sprites anyway. We don't use them.
-Sergal ears, oni horns, demon horns
Reason: Redundant + serve no purpose. There are identical tintable versions.

ADDS:
-Adds vox scales as a marking for use on top of vox sprite for the original dual-colour look
-Moth neck fluff as a "wing" accessory (It is not wings, but then again neither is goat legs. It will stay on top of clothes), "Neck fur"
-"Harpywings, alt archeopteryx" Softer armwing sprite w/ claws
https://gyazo.com/24bbc9dff467174dbd32e37fb9bf2e9f
-"Harpywings, bat" it a bat. Colourable inner
https://gyazo.com/59f8be47865fbfbc9fe16417924656f8
-Reinstate the 2 veteris hairstyles I can find, as markings, clean that up by moving them to marking folder (Cobra hood and double horns) Plus cobra hood is the best anyway :weary:

TWEAKS:
-Vox sprite is now greyscale. Colourable. Markings layer can achieve previous looks if desired.
-Sergal markings now usable by all, not just sergal race (Genemodder cheeseheads can use it now)

Update:
Fixed Travis ((He likes empty lines on the end of files that worked fine without them before???? What a guy))

-Edits to Mithra module to save 3rd marking slot colours
-Tertiary marking overlays work now for tails, Secondary and tertiary work for wings now

- Added Eastern Dragon tail (animated) to replace similar teshari tail on request 
It is an edit of citadel/tg's Bat tail 

https://gyazo.com/2135af5082923bcb621efd40ad9072ff

### CODE REVIEW

**Comment by CrackParrot11** [comment]
Good work, although i am very hesitant to see a neon-colored sparkle bird in the near future.

**Comment by Roland410** [comment]
Make vox be able to pick colors like adherents do, we don't need neon parrots.
And I'm always going to go with a no on any more wings, especially as most people still don't realize that you can't use it outside of passenger, service, supply and maybe research.
You also have Travis errors, which indicate that you did not test this at all, as the server can't even start.

**Comment by SilvernKell** [comment]
I did make colours to pick.
But have you ever uploaded a species sprite with all the body parts?
It's cancer
Atleast this way people can be any tone. There is already a rule against neon stuff, and it's possible to make neon stuff with any race sprite. Player issue tbh, and vox don't even have solid lore yet, so we don't really know why they'd have to be x colour or y colour yet
Hopesfully sane people can use it to make decent palettes, dark reds browns greens dark blue would all be good ones and I generally trust people to be sane considering there are so many things on character creation to already be crazy with
For the wings those are quite decent job choices tbh and I just wanted to add variations for other people
Also doesn't travis usually fail on everything currently? :eyes: Maybe I missed tesh references or something but I only removed markings hmm 🔍 I didn't know travis was fixed.

**Comment by Roland410** [comment]
No, it's a proper Travis fail, and even if Travis fails on an unrelated thing, it's always best to double check.
By the way, I'm fairly sure Adherents use a greyscale base and use set hex colors for the choices.

**Comment by SilvernKell** [comment]
I have amended it, but run into an alternate issue I want to fix so it can be completed properly with the dual colour stuff, will update when done. Still good to keep for the concept feedback in the meantime

**Comment by SilvernKell** [comment]
!! How do I convert to draft? This is not ready, absolutely don't merge yet

**Comment by SilvernKell** [comment]
Right, thank you burger. Sorry for the trouble. I found that wings don't allow colour overlays so the delay is in making sure that's all working for the future.

**Comment by Roland410** [comment]
Yeah, you can't make a PR a draft, only the other way which is a bit strange ngl.

**Comment by SilvernKell** [comment]
This has been fixed + updated
It plays with the files so tails can have a 3rd marking if you want
and wings can have a 2nd or a 3rd marking and couldnt before

It tests fine but if you wanna make sure that is okay, I don't think it will mess any saves up or anything as it only adds data

**Pull request merged**
