### PR TITLE
changes surgery cyborgs failing at surgery and crisis borgs failing at chemistry

### PR DESCRIPTION
**Pull request by AdamElTablawy**
two line change made in the web editor because i'm tired of making errors during surgery as a surgery cyborg because i am a master surgeon but somehow don't fucking understand what a liver is, mechanically

also the crisis borg meant to do chemistry can now actually do chemistry
🆑 God
tweak: Surgical cyborgs will no longer fail at surgery steps due to not having sufficient anatomy skills, and crisis borgs can actually do chemistry properly now.
/ 🆑

### CODE REVIEW

**Comment by BurgerLUA** [comment]
uhhhhhhhhhhhh please don't put bugfix in your title if it's not a bugfix. It's a balance change.

**Comment by AdamElTablawy** [comment]
sorry are surgery cyborgs supposed to fail at surgery? was that intentional?

**Comment by BurgerLUA** [comment]
> sorry are surgery cyborgs supposed to fail at surgery? was that intentional?

It could be a feature, yes considering station bounds do not have the agility of hands much like a humanoid or a more expensive IPC would.

**Comment by BurgerLUA** [comment]
failing travis, currently

**Comment by AdamElTablawy** [comment]
there is no reason it would fail atm

**Comment by SilvernKell** [comment]
https://github.com/BoHBranch/BoH-Bay/pull/770
https://github.com/BoHBranch/BoH-Bay/pull/764

These PRs are all linked

**Comment by AdamElTablawy** [comment]
merge it for the love of fuck

**Comment by BurgerLUA** [comment]
Well for some reason I can't merge it because we apparently need 2 reviews now to merge things, which I was not aware of.

**Pull request merged**
