### PR TITLE
roony chat

### PR DESCRIPTION
**Pull request by Vizoplez**
this is a bad idea.

### CODE REVIEW

**Comment by Kaksisilma** [comment]
- [x] Can people NOT see the whisper popups if they're away?
- [x] Can people NOT see the radio talk popups if they're away?
- [ ] Can people NOT see word pop-ups when they're in space?
- [x] Can people NOT understand words in a different language?
- [ ] Can people NOT see AUDIBLE emotes in vacuum?


-From Yawet.

This only does say verbs, not emotes. Emotes are still chatbox only because they break shit.

Also, space popups are intentional, side-effect from radio code.

**Comment by Vizoplez** [comment]
Failure to compile is due to an unknown CI issue.

Compiles fine locally, somehow its not finding a beyond internal proc.

**Comment by ProbablyCarl** [comment]
Test merging.

**Comment by ProbablyCarl** [comment]
Still test merged. Reduce text size slightly at the bare minimum before we fully merge it.

**Comment by Vizoplez** [comment]
Will need to fix other errors @ProbablyCarl 
This shouldn't be fullmerged until I give the go-ahead as it has server-breaking lag issues involving runtimes in a few, edge-case scenarios

**Comment by ShadeAware** [comment]
Looking forward to this

**Comment by ProbablyCarl** [comment]
@Yawet330
Needs attention.

**Comment by Vizoplez** [comment]
> @Yawet330 Needs attention.

I'm working on stuff. It's just slow-going as I'm having to track down misc runtimes with it.

**Comment by Vizoplez** [comment]
Dead in the water, does not perform well enough to justify a merge at this time, and any improvements are going to have to be on the back-end.

Leaving the branch this is on active.

**Pull request closed without merging**
