### PR TITLE
Genemodder background truly customizeable, tested locally, works

### PR DESCRIPTION
**Pull request by EldritchSigma**
"Fine.. I'll do it myself." -Bane Buddy standing 8'2'' blue boi.

This hopefully makes it so genemodders can select ANYTHING ELSE than just human backgrounds for a background. Since they are supposed to be genetic modifications of existing species and being a skrell thats strong but weak to drugs being forced to take human only backgrounds is kind of silly.

Might not work. Dont understand byond code to its fullest. Dont understand baycode quite. Reverse engineered this crap on an energy drink and two citaloprams that supposed to deal with crap.

Hint it did not work. Most likely like this PR.

### CODE REVIEW

**Comment by EldritchSigma** [comment]
Heavily WIP, hope I dont need to fucking add new calls and shit to make this work.

**Comment by EldritchSigma** [comment]
The "Weh" patch made it actually compile. Nice.

**Comment by EldritchSigma** [comment]
Works, tested it locally, all backgrounds show up.

**Comment by MarinaGryphon** [comment]
https://github.com/BoHBranch/BoH-Bay/blob/dev/code/__defines/culture.dm
This is the file with every culture name in it. I'll check to see if you've missed any but I don't think you have. This should, probably, work.
Also not high risk. Only touches one thing, doesn't touch the DB, etc.

**Comment by EldritchSigma** [comment]
Anything I need to fix on this?

**Comment by Andromeda-K22** [comment]
Appears fine. Merging.

**Pull request merged**
