### PR TITLE
Ascent Turret Update

### PR DESCRIPTION
**Pull request by SilverCelestine**
## About The Pull Request
Contains the new Ascent Anti-Boarding turrets complete with turret controller, and a variety of fixes for the vessel ranging from MAKING IT WHERE SHUTTLES ACTUALLY HAVE FLOOR TILES UNDER THEM WHEN THEY DEPART SO THEY DON'T DEPRESSURIZE ROOMS BELOW THEM... Fixes a variety of mapping issues with new Tiro rooms and cleans up the Ascent vessel a bit overall.
## Why It's Good For The Game
Adds Anti-Boarding capability to the Ascent ship (They're still pretty inaccurate and easily avoidable).
Fixes a mapping oversights of the Tiro rooms including missing ceiling tiles and air alarms.
Finally makes it where shuttles leave tiles under them when they depart the mains hip.

## Did You Test It?
#worksonmymachine
## Authorship
Me, Myself, and I.
## Changelog
Adds turrets
Adds turret control panel
Fixes missing tiles
Adds missing air alarms
Makes shuttles spawn with floors under them so the ship doesn't depressurize
:cl:
/:cl:

### CODE REVIEW

**Comment by SilverCelestine** [comment]
I spent three days of my life combing through the Ascent ship for any issues that might arise and cause the check to fail. I am **NOT** going through the entirety of the Dagon/Torch looking for issues for this. This PR changes NOTHING aboard the Dagon/Torch map file.

**Comment by Armyguy** [comment]
Good news!, that CI error is https://github.com/BoHBranch/BoH-Bay/pull/1549 's fault. So your good to go

**Comment by SilverCelestine** [comment]
Thank Carl...

**Comment by Shirumic** [comment]
Now all the ascent seedship needs are navpoints for other shuttles to land near it for the boarding turrets to actually be used!

**Comment by SilverCelestine** [comment]
> Now all the ascent seedship needs are navpoints for other shuttles to land near it for the boarding turrets to actually be used!

I mean.. I guess I could look into how to make those..

**Comment by Anton-Kr** [comment]
Since the CI issue prevents away_map_testing from running, kindly update this from master so that the map changes can be tested.

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
pull from master to run CI

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
UNIT_TEST : [AREA: Areas shall be coherent]: The Ascent Seedship - Command Chamber (/area/ship/ascent/bridge) ([0x4000024]) (86,81,10) is incoherent. Expected 16 subareas, fill gave 14. Origin turfs:

Change number to 14

**Comment by SilverCelestine** [comment]
> UNIT_TEST : [AREA: Areas shall be coherent]: The Ascent Seedship - Command Chamber (/area/ship/ascent/bridge) ([0x4000024]) (86,81,10) is incoherent. Expected 16 subareas, fill gave 14. Origin turfs:
> 
> Change number to 14

Already done, waiting for it to rerun.

**YOU'RE TOO SLOW OLD MAN**

**Comment by Anton-Kr** [comment]
brb insta closing

**Review by Anton-Kr — APPROVED** [review]

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
