### PR TITLE
Changes gamemode vote visibility to be a config option.

### PR DESCRIPTION
**Pull request by MarinaGryphon**
By popular demand.

### CODE REVIEW

**Comment by Roland410** [comment]
I think you got two things confused by the way. People wanted to see what people are voting for, not the end result, although obviously this will make it visible, but you could already see that in the gamemode section in the lobby screen etc.
By the way, I may be wrong, but the code that obfuscates the gamemode after voting, I'm fairly sure was implemented here, as I don't remember it being a Bay thing.

**Comment by MarinaGryphon** [comment]
> but you could already see that in the gamemode section in the lobby screen etc.

That was broken and commonly showed incorrect results, like Extended when Extended didn't win, Merc before the vote has even started, etc.

**Comment by BurgerLUA** [comment]
Travis is failing due to bad map edits. Update to upstream/dev and push the changes.

```
## UNIT_TEST ##: [MAP: Closet Containment Test Player Z levels]: The solar pack crate (/obj/structure/closet/crate/solar) ([0x200927c]) (the plating) (52,119,5) (/turf/simulated/floor/plating) no longer contains the following atoms: [The remains (/obj/item/remains/mouse) ([0x201a680]) (the plating) (52,119,5) (/turf/simulated/floor/plating)]
## UNIT_TEST ##: ---  DEBUG  --- [MAP: Closet Containment Test Player Z levels]: The crate (/obj/structure/closet/crate) ([0x200a126]) (the plating) (93,95,6) (/turf/simulated/floor/plating) now contains the following atoms: [The boombox (/obj/item/device/boombox) ([0x20027a1]) (the plating) (93,95,6) (/turf/simulated/floor/plating)]
## UNIT_TEST ##: !!! FAILURE !!! [MAP: Closet Containment Test Player Z levels]: 1 closet with inconsistent pre/post-open contents found.
```

**Comment by BurgerLUA** [comment]
We now need 2 approvals to merge things.

**Pull request merged**
