### PR TITLE
Bearcat away map rework

### PR DESCRIPTION
**Pull request by CrackParrot11**
This adds many Quality of life map improvements to the Bearcat away site. Including a functional docking shuttle for access to other Overmap sites, as well as some mining equipment and other minor improvements.

### CODE REVIEW

**Comment by Roland410** [comment]
Got pics? Also what are "other minor improvements"? I'd also make that shuttle a tiny bit bigger and give it an SMES to be in-line with other ones (and to not be fucking awful tbf).

**Comment by CrackParrot11** [comment]
> Got pics? Also what are "other minor improvements"? I'd also make that shuttle a tiny bit bigger and give it an SMES to be in-line with other ones (and to not be fucking awful tbf).

The minor improvements besides the shuttle are actual mining equipment, an Ore processor and a suit cycler for non human crew members. Other than that the Bearcat map itself was already mostly finished.

**Comment by CrackParrot11** [comment]
Map preview. https://imgur.com/a/Pg0qT22

**Comment by Roland410** [comment]
You forgot to mapmerge the -1 map, and that shuttle is atrocious. In my opinion make it like the GUP/Garuda is. You also use oxygen for the thrusters? Seems strange but should work technically. It seems you also have an air/gas injector in the corner for ???
For future reference there is an in-game verb called Set View Range or something to make one pic of the map, or you can do the same through the map editor, just change the view from there.

**Comment by CrackParrot11** [comment]
Redoing this pr to fix the map merge issue

**Pull request closed without merging**
