### PR TITLE
Nerfs the E-Swords Damage a tiny bit.

### PR DESCRIPTION
**Pull request by Dark1Star3s**
Not entirely sure how much this will effect the sword, but it's a tiny nerf. Hopefully I won't have to do another one. >_>

* Changed: Damage from 45 to 30.

### CODE REVIEW

**Comment by TheOrleans** [comment]
No to salt prs.

**Comment by Sparrowbird611** [comment]
*breathes in*

~~SALT PR REEEEE~~

Just kidding.

Jokes aside however, I'd like to point out two things. First off, I'd suggest testing sheep's new changes to traitor item prices, including stim packs and e sword. Secondly, if you are intent on this, I would not advise keeping it at the current 58 TC price. 36-42 would seem more appropriate.

**Comment by Roland410** [comment]
I'm downvoting as well because you've provided no proof this changes anything about it in real situations (or even in testing), so in short, test it at the very least, and adjust it then. What Sparrow said as well, because if it does less damage, it should not cost as much either.

**Comment by BurgerLUA** [comment]
Needs more feedback.

**Comment by BurgerLUA** [comment]
Probably needs a poll.

**Pull request merged**
