### PR TITLE
Clothing Updates

### PR DESCRIPTION
**Pull request by AMcilraith**
## About The Pull Request
Updates fleet clothing to be fleet only, removes NTEF/SC clothes
## Why It's Good For The Game
More consistency in loadout menu
## Did You Test It?
Not yet, NO.
## Authorship
Dr. Farson
## Changelog

:cl: AMcIlraith
tweak: updates uniforms to be fleet
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
If this is removing the SC uniforms (which would be extremely cringe) You're going to have to add unathi sprites for all the other fleet uniforms. they're missing as of now, and it'll go from a big issue to a BEEEEG issue if you do this.

**Review by BurpleBineapple — CHANGES_REQUESTED** [review]
The only code problem with this PR is that you did not account for warrant officer ranks.

Warrant officers are between rank 11 and rank 15. Because of the way you have currently set officers to 11, O-1 and O-2 will receive Senior Officer uniforms and all others will receive Flag Officer uniforms. This is a bug I previously fixed.

To correct this, set your Commissioned Officer min_rank to 16. Set your Senior Commissioned Officer rank to 20. Set your Flag Officer rank to 22.

**Comment by BurpleBineapple** [comment]
And, as Rock also said, if you remove the EC uniforms, you will have to sprite replacements for Unathi in all Fleet uniforms. There are no existing unathi sprites currently and this will cause sprite issues.

**Comment by AMcilraith** [comment]
> And, as Rock also said, if you remove the EC uniforms, you will have to sprite replacements for Unathi in all Fleet uniforms. There are no existing unathi sprites currently and this will cause sprite issues.

Aye, will do so.

**Comment by anconfuzedrock** [comment]
It'd be cool see an actual reason for removing the SC uniforms instead of it being brushed aside like a side-effect of the PR. A lot of people actually use them.

**Comment by BurpleBineapple** [comment]
Listing as do not merge until sprites are added.

**Comment by Anton-Kr** [comment]
Honestly pretty iffy on removing EC sprites. I get the want for consistency, but that kind of went out of the window with the amount of uniform variations we have currently. I'll see how other maintainers feel about this.

**Pull request closed without merging**
