### PR TITLE
Plasma Rifle

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
Adds a burst fire projectile energy weapon - Plasma Rifle. Pair can be ordered for 105 credits in supply on code blue. Added into raider pool and uplink too.

## Why It's Good For The Game
Basically all energy weapons are pure hitscan so having one that isn't seems like a good bridge between laser carbine and x-ray carbine.

## Did You Test It?
Yes

## Authorship
Me

## Changelog

:cl:
rscadd: Plasma Rifle
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
This bad boy go through windows?

**Comment by Lamasmaster** [comment]
No, it is a projectile so it will behave more like a bullet except it can't penetrate walls or doors.

**Comment by Dark1Star3s** [comment]
A Phased Plasma Rifle in the Fourty Watt Range?

**Comment by Jeff-jefferson-jeffery** [comment]
Just what you see here, buddy.

**Comment by Anton-Kr** [comment]
Seems interesting

**Comment by Cupax3** [comment]
Hello, can you re-push your branch? GitHub Actions had a hiccup 4 hours ago, your workflow run got swallowed in it.

**Comment by Cupax3** [comment]
thank ye, works now

**Comment by Lamasmaster** [comment]
I hate firemode code so much

**Comment by SilverCelestine** [comment]
Jesus christ, how horrifying. The wounds caused by this thing would be a nightmare, I approve.

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
