### PR TITLE
Language changes part 2: super duper talking time

### PR DESCRIPTION
**Pull request by Jaraci**
- Adds Neo-Cossack, a new lore-friendly hybrid pidgin of ZAC and Pan-Slavic. It was going to be called Gaian, but that is apparently being reworked by the lore people, so this is the current working name. It has high mutual intelligibility with both ZAC and Pan-Slavic, as you might imagine.
- Removes Legalese. Goodnight, not-so-sweet prince.
- Adds a maximum intelligibility to all languages for non-speakers, mostly capped at the default value of 95% comprehensibility. If you don't specifically speak it, you can no longer fully understand it by capping out on other languages' contribution to your understanding (see: understanding 100% of Selenian because you know ZAC and Spacer).
- Alien languages are capped at a much lower intelligibility.
- Spacer now looks all metal, kind of like Gutter, because it is an ugly bastard pidgin and not a real language. This is in preparation for a planned Gutter rework coming further down the line.

Feedback welcome. This is kind of a slight deviation from my plans for more **d i a l e c t s** of ZAC like Selenian, but hey, it's lore-friendly. I think I'm actually starting to figure out this Git bullshit as well.

🆑Omicega
rscadd: Adds Neo-Cossack, a new lore-friendly hybrid pidgin of ZAC and Pan-Slavic.
rscdel: Removes Legalese.
tweak: Adds a maximum intelligibility to all languages for non-speakers, mostly capped at the 
default value of 95% comprehensibility.
tweak: Alien languages are capped at a much lower intelligibility.
tweak: Spacer has a new, gritty font, just like Gutter.
tweak: Iberian now actually has partial understanding values with other languages.
/🆑

### CODE REVIEW

**Comment by Roland410** [comment]
Please keep Legalese, as that's a rare one and you need actual skill points invested.
Other than that, not a fan of even more language bloat (and removing legalese does not mean it's not), but this one sounds alright.

**Comment by Roland410** [comment]
By the way, probably should squash when able/ready.

**Comment by Glitterhoof** [comment]
I like the changes however please for the love of all things holy keep legalese

**Comment by Jaraci** [comment]
Legalese is a literal meme. Look at the syllable list for it when you have the time -- it's literally just disjointed Latin phrases, some/all of which might be real legal terms? It's a joke language and is about as HRP as caveman speak would be. I'm really not a fan of it, well-liked though it might be.

I don't know what squashing is because I am doing all this Git stuff on a wing and a prayer.

**Comment by MarinaGryphon** [comment]
Squashing is done by whoever merges it. Will do once it's merge-ready.

**Comment by Jaraci** [comment]
- Actually makes Neo-Cossack's partial intelligibility two-way because I totally forgot to do that in the first place
- Tweaks partial understanding of alien languages because 1/10 was definitely way too high in hindsight
- Adds Iberian PU while I'm at it because for some reason it had almost no interaction with other languages except ZAC

**Comment by Sparrowbird611** [comment]
Reworking gutter eh? What kind of rework.

Also, keep legalese or bust.

**Comment by Jaraci** [comment]
This is actually ready to go -- any vaguely placeholder lore can be updated with the actual loredev lore when it's finalised. It works from a code perspective, though.

@Sparrowbird611 The current plan is to change it into a generalist Plutonian/Belter dialect of ZAC (think Selenian but for poor people) instead of having it be a "galaxy-wide criminal language" in IC terms, which makes no sense whatsoever.

**Comment by Sparrowbird611** [comment]
…..…..Ngl, I liked having it as the common criminal tongue.

**Comment by Roland410** [comment]
If you open a new PR, you get a link to the automated changelog info, but most people seem to ignore it.

**Comment by Andromeda-K22** [comment]
Removal of legalese is a little wonky, but, overall good.

**Comment by MistakeNot4892** [comment]
```
## UNIT_TEST ##: [UNIQUENESS: Languages Shall Have No or Unique Keys]: Language Keys - c - The following entries have the same value: /datum/language/alium and /datum/language/human/gaian
## UNIT_TEST ##: !!! FAILURE !!! [UNIQUENESS: Languages Shall Have No or Unique Keys]: 1 issue with language datums found.
```

**Pull request merged**
