### PR TITLE
Saferoom Atmos Safety

### PR DESCRIPTION
**Pull request by Rafflesia7793**
## About The Pull Request
During times of excessive heat: 
image
there is a tendency for pipes to be broken, and when pipes are broken gas can escape from them, but also enter them. This results in large amounts of burning plasma entering the supply and disposals networks, and creating massive fireballs in random rooms. This is based.

However sometimes the random rooms happen to be saferooms: 
image
This is less based. 

So fleet engineers decided that the best way to fix this would be to isolate the saferoom piping from the grid altogether:
image
They also decided to add decontamination showers. These are good ways to remove contamination from yourself, also, 20C H2O has a tendency to keep the room it is in at 20C.

## Why It's Good For The Game
Make saferooms slightly safer during massive fires.
## Did You Test It?
Yes.
## Authorship
Rafflesia
## Changelog

### CODE REVIEW

**Comment by Rafflesia7793** [comment]
Conflicts with: https://github.com/BoHBranch/BoH-Bay/pull/1718

**Comment by Rafflesia7793** [comment]
Finally all fucking green checkmarks. I hate scrubbers, I hate scrubbers, I hate scrubbers.

**Comment by Rafflesia7793** [comment]
Conflicts with: https://github.com/BoHBranch/BoH-Bay/pull/1661

**Comment by Rafflesia7793** [comment]
Also conflicts with: https://github.com/BoHBranch/BoH-Bay/pull/1725

**Comment by Rafflesia7793** [comment]
~~Conflicts with https://github.com/BoHBranch/BoH-Bay/pull/1659~~

**Review by BurpleBineapple — APPROVED** [review]
After checking through, seems fine mapwise. I also think it's a sound idea to have saferooms proofed for critical atmospheric failure.

Approved from me.

**Review by SilverCelestine — APPROVED** [review]
Looks good to me as far as I'm aware.

**Pull request merged**
