### PR TITLE
deck 1 changes, adding pills to medical, adding autolathe to medical a-la tg medilathe

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
i beg you, please. do not fucking do this. do not make it so that i change 1000 things. pleas.e just be a normal fucking push for oncee. holy hgood

**what this does**

i finally made the fucking pillbottles spawn in medical. i also changed it so the walls near the lil tumors sticking off the side of the ship aren';t dummy thin sicne it didn't really make sense aesthetically or balance-wise since them bitches vented in like .3 seconds compared to the rest of the ship. 

**why it's good**

makes it so emt'z aren't completely reliant on chemists, makes it so that chemists don't have themost tedious job in the agme, makes it so that medical tator-tots can potentially do some sneaky shit AND makes it so that normal medical peoople can like, build an extra beaker if something goes wrong

**why you should kill me**

i beg you

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
hha
HAHA
HAHAHAHAH IT DID IT
IT PU,LLED RIFGHT
IT MEKRBGIUJ9EIDU IN MRIEIRK,GKMREINMJDFJDN

HEHEHEHEHEHEHEHEHEEEEEEEEEEEEEEEEE

**Comment by bearrrrrrrr** [comment]
I AM THE JESTER ON GITHUB, DANCING FOR THE WORLD TO SEE. MY TRAGEDY IS ONLY HALTED BY THE LAUGHS OF SCHADENFREUDE I BRING. ART I NOT ENTERTAINING?

hEHEHEHEH

**Comment by Sparrowbird611** [comment]
Bear, you're drunk, go home.

**Comment by N8-Toe** [comment]
do you have any screen shots of the map changes? and where is the auto lathe added. 

and pill bottles already spawn in the chemist locker, are you saying you added already filled pill bottles? and if so bottles of what. the actual implementation of these changes is unclear

**Comment by Sparrowbird611** [comment]
Bear is losing it. Some one call the coder police, we have an issue.

**Comment by bearrrrrrrr** [comment]
@N8-Toe U CAN CHEGK MAP DIF RENDERRRR, C WHERE B

MIII MAKE GARENTEE PILL BOTTLE SPAWN OF ADVANCE MEDICINE (DEXA+, KELODERM, ETC) PILL IN MEDIKAL STORAG. AS OPPO 2 RNG BOTTL OF MEDIKINE

HGIIIII HIEEEEE

**Comment by Roland410** [comment]
You didn't mapmerge this, also you should be using a proper commit name. Medical doesn't need an autolathe either. By the way the mapdiffbot is broken, so yeah, you should post pics for map changes.

**Comment by bearrrrrrrr** [comment]
did it

I wanna die lol

bye

**Comment by MarinaGryphon** [comment]
This doesn't add an autolathe.
Also, I'm not sure about spawning with one of all these pills. These are like... dead simple to make.

**Comment by bearrrrrrrr** [comment]
@MarinaGryphon it adds an autolathe in medical storage unless i somehow fantastically and cataSTROphically cocked something up

also yes, that's the intention. it makes it so that EMT's aren't absolutey boned by having no access to incredibly simple medication, *and* so that chemists can kind of bypass the easier-to-make chems and save just a bit of time. the most consistently awful part of doing medical on baycode is chemistry imho

**Pull request merged**
