### PR TITLE
Revert "Added a borer symbiote job definition."

### PR DESCRIPTION
**Pull request by MarinaGryphon**
Reverts BoHBranch/BoH-Bay#712

No one in staff wants this, and it is unironically just a bad idea.

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
Oof, feelsbadman.

**Comment by AdamElTablawy** [comment]
thankk god

**Comment by MarinaGryphon** [comment]
> Oof, feelsbadman.

They are literally not mapped in anyway. We just don't want them, they're memey and a bad idea in general.

**Comment by MistakeNot4892** [comment]
I opened it because it was asked for, there's absolutely no need to be so rude about it.

**Comment by Tename** [comment]
It's had less than a day for the bugs to be worked out, I personally really enjoy the idea, it has a lot of potential, and this is very unprofessional and just fucking rude.

**Comment by MistakeNot4892** [comment]
I will not be following up the original PR after this was discussed on Discord, so reversion is probably the best approach.

**Comment by Keekenox** [comment]
I'm going to chime in on this one. So there's a whole lot about this symbiote thing that is just not in line with the server as well as the fact that it's incredibly buggy. Borers have basically always been a massive pile of bugs.

**Comment by Roland410** [comment]
I mean, if no staff wants it, how was it merged? :thinking:
Anyways, all problems witb borers could be fixed in a day probably, but I guess it'll be another piece of abandoned code then.

**Comment by AdamElTablawy** [comment]
@Roland410 There are no possible fixes for a brainslug that has no purpose to exist. Why would head-invading slugs even be allowed to exist? It's a biological pAI that can heal you and creeps people out.

Let them stay dead.

**Comment by Tename** [comment]
> 
> 
> @Roland410 There are no possible fixes for a brainslug that has no purpose to exist. Why would head-invading slugs even be allowed to exist? It's a biological pAI that can heal you and creeps people out.
> 
> Let them stay dead.

There are multiple IC reasons for a headslug to exists, medical reasons, the fact that two minds can be more powerful than one, depressed people, and just the fact that it is a sentient race and politically banning them could be seen as negative and immoral. The Tokra in the Stargate universe and Trill in startrek are good examples, I believe there is also a race in Stargate that enslaved them for medical reasons as well if I remember correctly. Mechanic wise they could be limited to a more passive healing element for balance and become more a fluff thing for RP purposes, the only thing that is really like even really that powerful is hyperzine.

**Comment by AdamElTablawy** [comment]
@Tename 

If they stay, they're objectively not going to have any sort of healing or chem synthesizing ability whatsoever.

They'll be biological pAIs.

**Comment by Tename** [comment]
> 
> 
> @Tename
> 
> If they stay, they're objectively not going to have any sort of healing or chem synthesizing ability whatsoever.
> 
> They'll be biological pAIs.

Uh huh?

**Comment by AdamElTablawy** [comment]
@Tename 

yeah, so says carl, check #development-discussion

**Comment by SilvernKell** [comment]
I honestly love the idea because I always thought of many examples in scifi media that made it seem interesting and like a really fun thing to try out.
But it did kinda come out of nowhere and it does give mechanical advantages with no downsides (from the purely mechanical perspective)
Just outright removing them is a bummer though. 
The best thing imo would be to have a race that actually relies on them to actively offset weaknesses,
But I can also guarantee that it'd be a flavour of the moment thing and that in a month if people picked that race it'd be like trying to get a pai and you'd never get one unless you had a friend for it.
Overall I'm not really sure how it actually is supposed to fit into the server's dynamic.
But as a heavy roleplay server, should we not be trying harder to allow things that can be interesting storywise, and care less about perfect balance that cannot be achieved?
We don't really choose to go to a heavy roleplay ss13 server for epic fights without story elements.
So maybe we should try to be more understanding about allowing ideas to evolve and grow for the sake of roleplay fun.
So much of the time on discord and development it's talks about x thing not corresponding to y lore from some other place, or x thing bad because there's the possible idea that someone somewhere might be incrementally stronger then someone else despite it being a flavourful RP tool that in the hands of responsible players is a very interesting and flavourful addition. Do we really want to stagnate like that and disallow ideas that can grow stories ingame? Wasn't the purpose of the server to bring a community together from other areas so it can become it's own thing and community without issues of stagnant restraint and toxic constant negativity behaviour?

A point that I see, is that in order to play test things as time goes on, we ARE going to see a lack of balance, we ARE going to have people saying X round sucked! People are already aware with that with the voting experiments to try and find the kind of events people enjoy ingame in lieua of constant extended.
So why can't we have a little leeway and change our focus towards that for developers as well?

We should try and work together and try and treat it as a worldbuilding process to improve concepts instead of kneejerk removing things immediately because they aren't too well balanced without playtesting. Not specifically for this, but I can see it as a growing problem as a whole for the community, especially recently. I don't personally want us to go the way of just removing everything that takes effort and positivity to work on together, only so we can we insult each other all the time and go back to genemodder bad! Sec man bad! consistently. Everyone could benefit with a little patience with one another and less stress of the current realworld dictating us not just taking a step back and a breather from the fact that a little unbalance is worth a lot more fun, and it doesn't have to be a big problem to us.

Anyway, this is my current feeling with trying to make the community more positive, I hope we can work this idea into the game in a fitting way over time.

**Comment by ProbablyCarl** [comment]
This code won't be maintained, and it's pretty buggy with how holdtypes are and such. Or so I've been told. Given that, we'll have to remove it for now, unless someone wants to upkeep it in the future.

**Comment by bearrrrrrrr** [comment]
> I honestly love the idea because I always thought of many examples in scifi media that made it seem interesting and like a really fun thing to try out.
> But it did kinda come out of nowhere and it does give mechanical advantages with no downsides (from the purely mechanical perspective)
> Just outright removing them is a bummer though.
> The best thing imo would be to have a race that actually relies on them to actively offset weaknesses,
> But I can also guarantee that it'd be a flavour of the moment thing and that in a month if people picked that race it'd be like trying to get a pai and you'd never get one unless you had a friend for it.
> Overall I'm not really sure how it actually is supposed to fit into the server's dynamic.
> But as a heavy roleplay server, should we not be trying harder to allow things that can be interesting storywise, and care less about perfect balance that cannot be achieved?
> We don't really choose to go to a heavy roleplay ss13 server for epic fights without story elements.
> So maybe we should try to be more understanding about allowing ideas to evolve and grow for the sake of roleplay fun.
> So much of the time on discord and development it's talks about x thing not corresponding to y lore from some other place, or x thing bad because there's the possible idea that someone somewhere might be incrementally stronger then someone else despite it being a flavourful RP tool that in the hands of responsible players is a very interesting and flavourful addition. Do we really want to stagnate like that and disallow ideas that can grow stories ingame? Wasn't the purpose of the server to bring a community together from other areas so it can become it's own thing and community without issues of stagnant restraint and toxic constant negativity behaviour?
> 
> A point that I see, is that in order to play test things as time goes on, we ARE going to see a lack of balance, we ARE going to have people saying X round sucked! People are already aware with that with the voting experiments to try and find the kind of events people enjoy ingame in lieua of constant extended.
> So why can't we have a little leeway and change our focus towards that for developers as well?
> 
> We should try and work together and try and treat it as a worldbuilding process to improve concepts instead of kneejerk removing things immediately because they aren't too well balanced without playtesting. Not specifically for this, but I can see it as a growing problem as a whole for the community, especially recently. I don't personally want us to go the way of just removing everything that takes effort and positivity to work on together, only so we can we insult each other all the time and go back to genemodder bad! Sec man bad! consistently. Everyone could benefit with a little patience with one another and less stress of the current realworld dictating us not just taking a step back and a breather from the fact that a little unbalance is worth a lot more fun, and it doesn't have to be a big problem to us.
> 
> Anyway, this is my current feeling with trying to make the community more positive, I hope we can work this idea into the game in a fitting way over time.



ok cool, it'll get readded when you code it and fix all of the bugs and fix all of the balancing and make it actually fun

hmu when you do that

**Comment by AdamElTablawy** [comment]
>Do we really want to stagnate like that and disallow ideas that can grow stories ingame? 

if the ideas and stories are shit yes

**Comment by ProbablyCarl** [comment]
Not required any longer.

**Pull request closed without merging**
