### PR TITLE
Slav content and loadout additions

### PR DESCRIPTION
**Pull request by Jackofashepard**
- Slavic track jacket to loadout 
- UCG ushanka to loadout 
- Boombox  to loadout 
- Ancient uniform  to loadout 
- One new song for the playlist

### CODE REVIEW

**Comment by Jackofashepard** [comment]
Travis, why are you like this 
image

**Comment by gilvian** [comment]
fuck

**Comment by Jackofashepard** [comment]
Travis is having a emotional breakdown, its simply too slav

**Comment by BurgerLUA** [comment]
Going to see whats wrong with travis.

**Comment by Tristan63** [comment]
lets be real, we have ICCG mugs and ushankas already, just rename those bruh?

**Comment by Jackofashepard** [comment]
Travis finally approves

**Comment by Superhats** [comment]
Closing this, as it's been veto'd by our loremaster. We'd like to cut down on the cheeki breeki memes, and this isn't helping.

**Pull request closed without merging**
