### PR TITLE
Limits the amount of implants per type you can implant in an external limb to 1.

### PR DESCRIPTION
**Pull request by BurgerLUA**
Basically prevents duplicate implants in the same limb. I mean, sure you can implant 8 microbomb implants, one in each limb, but at least it isn't 50.

### CODE REVIEW

**Comment by MemedHams** [comment]
okay, so: Why not simply hardcap the number of microbombs that can be implanted in a single body to 8? This also nerfs implants in general, and I'd be willing to have that conversation, but that requires it's own PR, and maybe a vote if we do those.

**Comment by Chaznoodles** [comment]
This would impact traitor counselors/mentalists/psionics in general who want to up their psionic levels but can only have one amp. Set a hard limit to 5 or 8 or something.

Anyone dedicated enough to blow all their points on micros deserves some payoff.

**Comment by BurgerLUA** [comment]
> okay, so: Why not simply hardcap the number of microbombs that can be implanted in a single body to 8? This also nerfs implants in general, and I'd be willing to have that conversation, but that requires it's own PR, and maybe a vote if we do those.

That doesn't make much sense code wise and realism wise. It's much saner to make it so that each limb has a limit of implants so you don't become a god.

**Comment by Sparrowbird611** [comment]
Ok so, I rarely use implants so correct me if I'm wrong on my logic when I suggest this, but I think you should probably be able to have like three head implants. Otherwise, you may just have people implanting the death alarm, tracking implant, or literally anything else to prevent mindslaving.

**Pull request closed without merging**
