### PR TITLE
Fixes Vox ship vent bug.

### PR DESCRIPTION
**Pull request by Torque4607**
Here's how it is. I was ghosting and noticed the Dagon's supermatter core vent blast doors would randomly open and close. It was confounding for the whole round until I jumped to the Vox ship and saw... them toggling the blast doors to vent their engine room. I checked the id_tag variable, and sure enough... the Dagon supermatter core vent and the Vox ship engine room vent had the exact same id_tag = "EngineVent". So I went ahead and changed it so I don't have to keep deleting that button.

### CODE REVIEW

**Comment by Torque4607** [comment]
Nope, apparently even using mapmerge has a stupidly fucking huge diff. I give up, it's good enough for the girls I go out with.

**Comment by Roland410** [comment]
That face when your PR conflicts with your PR basically.

**Comment by BurgerLUA** [comment]
Conflicting files + Travis errors.

**Comment by BurgerLUA** [comment]
Still conflicting files.

**Comment by BurgerLUA** [comment]
Failing travis and conflicting files.

**Pull request closed without merging**
