### PR TITLE
[Ready for Testmerge] Medical Remap

### PR DESCRIPTION
**Pull request by Tename**
**Original PR: https://github.com/BoHBranch/BoH-Bay/pull/879**

This is a remap of the center areas of medbay(Treatment Center, Morgue, Recovery, Resleeving, Autopsy, OR rooms, and more.) the main goal is to make medbay easier to organize during overflow times. Another goal I had was also to make the morgue and autopsy lab fully stocked to remove laces and prep corpses for resleeving, this should reduce the load on the other two OR rooms if managed properly. 

Feedback welcomed, while I am done drafting I still am willing to consider major changes based on feedback. Pictures can be viewed by clicking checks and then Mapdiffbot.

## Changelog
:cl:
add: Surgical Spray bottle 50/50 mix of sterilizer and space cleaner
add: Weak Medical Lollipop box
Fix: Missing camera in the bridge from my last PR
del: Escape pod 9
tweak: Medical Wardrobe spawns with nurse hats and dresses
tweak: Plastic an aluminum now spawns next to the medical auto lathe
tweak: Treatment center renamed to Trauma Center
imageadd: Triage Sprites
imageadd: Reversed loading decal (Not used)
map: Back areas of medical completely rebuilt
map: Aux Medical Storage moved next to OR rooms
map: Old Aux Medical Storage replaced with a medical EVA room.
map: New Triage drop-off room
map:  Extra recovery room
map: Morgue is now fully stocked to remove laces and process bodies
map: Morgue spawns with a shipping closet to send items back to their departments.
map: Escape pod 8 moved behind Briefing room
map: Medical equipment area mostly untouched, say for a new uniform vendor
map: Slightly less morgue trays than the old design, but more space to move
map: Many maint changes around medical
map: Treatment center reworked for better organization during overflow times
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Testmerging this.

**Comment by Tename** [comment]
> 
> 
> Testmerging this.

Alright

**Comment by Tename** [comment]
Can I get an update on what's going on with this? I believe this still hasn't been in the live server.

**Comment by BurgerLUA** [comment]
There are conflicting files. I cannot testmerge it if it's conflicting with upstream.

**Comment by Tename** [comment]
Conflicts were from something recently merged... Remaking the PR... Again

**Comment by Tename** [comment]
Well I just accidentally deleted the sprites for the map and I am actually done remaking this ever month so I am fucking out.

**Pull request closed without merging**
