### PR TITLE
Various QoL Changes / More

### PR DESCRIPTION
**Pull request by ProbablyCarl**
- - -
Bugfix:
 - Ascent drones can now actually speak ZAC, as was intended.
 - Vox TEG fix. This corrected the pipe issue, and now allows for players to actually have an active, working TEG.
 - Pathfinder given basic Research access. Because it didn't have it, for some reason, despite working alongside the Science department.
- - -
Additions:
 - Ascent Gyne given a mind batterer, to enable easier taking of captives. This affects everyone, and while the cooldown isn't absurd, having no IFF will provide hilarious results for bald Gynes.
 - Basic Ascent shield for individual use added, though not mapped in.
 - Ascent can now produce premade medications, in the same manner as the Skrell. This was intended, but never actually mapped in.
 - Ascent now have gloves for surgical procedures.
 - The Vox now have a bioreactor, which is quite literally just a reskinned Ascent reactor but garbage, until we get an actual bioreactor to replace it. It produces a measly fifteen kilowatts when active, and is primarily for show at the moment.
- - -
Balance:
 - Vox slugs are now much, much more deadly. They're an actual threat, rather than a minor annoyance, as they now inject VB, rather than CB.
 - Psyker for Command now spawns with initial equipment, rather than it sitting in their office. It slightly differs flavour wise depending on the alt title.
 - Jerraman removed from map, as it made no sense within the current lore. It remains in the files for future use, if required admin-wise/event-wise.
 - Vox ship given PDs for their exposed ship areas. They won't actually do much in a full storm, but they're good for random events. If ever. The remainder of the vessel retains its asteroid hull lining.
- - -
Re-additions:
 - Psykers are now once again present within Medical, with four different alt titles.
 - Command Psyker re-opened, though this may change, pending lore dev input.
- - -
Map:
 - Vox vessel given a touch up so it's now lore compliant. No longer are they mouth breathing rejects. Mostly. This change was made to reflect that they're an outer group, scavenging for the Arks and not necessarily pirates or raiders with lack of care for their crew.

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
I like a lot of this, but if I'm reading this correctly, the psi advisor guy is now A: supposed to valid hunt psionic people now and B: had an anti psyker pistol. That doesn't seem like a good idea.

**Comment by ProbablyCarl** [comment]
> I like a lot of this, but if I'm reading this correctly, the psi advisor guy is now A: supposed to valid hunt psionic people now and B: has an anti psyker pistol now. That doesn't seem like a good idea, if I'm understanding correctly.

I believe the intention originally was to give them the revolver. I can remove it if it's an issue.
As for them valid hunting - no. It was a rewording of the description from prior. Though I could've worded it better, I admit.

**Comment by ProbablyCarl** [comment]
> Also not entirely sure why you got rid of jerraman. The purpose of that substance was so that being latent actually meant something, not "oh boy, I have secret psionic powers that I'll never awaken unless I do illegal stuff."

Jerraman was removed at the request of multiple individuals on staff. They'll probably weigh in here on that. They didn't believe it to fit - I'd have kept it myself otherwise.

**Comment by Sparrowbird611** [comment]
> I like a lot of this, but if I'm reading this correctly, the psi advisor guy is now A: supposed to valid hunt psionic people now and B: has an anti psyker pistol now. That doesn't seem like a good idea, if I'm understanding correctly.
> 
> I believe the intention originally was to give them the revolver. I can remove it if it's an issue.
> As for them valid hunting - no. It was a rewording of the description from prior. Though I could've worded it better, I admit.

Yeah, I would suggest removing the pistol or at least changing the ammo, and changing the desc. Between having a pistol specifically designed to cuck psykers, and that description, or more or less sounds like the guy is supposed to go bum rush people with pistols.



> Also not entirely sure why you got rid of jerraman. The purpose of that substance was so that being latent actually meant something, not "oh boy, I have secret psionic powers that I'll never awaken unless I do illegal stuff."
> 
> Jerraman was removed at the request of multiple individuals on staff. They'll probably weigh in here on that. They didn't believe it to fit - I'd have kept it myself otherwise.

Alright. I'll be interested to hear what they say if they show up.

**Comment by ProbablyCarl** [comment]
> Yeah, I would suggest removing the pistol or at least changing the ammo, and changing the desc. Between having a pistol specifically designed to cuck psykers, and that description, or more or less sounds like the guy is supposed to go bum rush people with pistols.

The Psi Advisor is the only one with nullglass bullets. Without the revolver, Psykers could easily deflect other material thrown at them. Which is why they have the revolver, in theory. In practice, it'll probably be abused. If it is, we'll remove it. I don't think it'll be too much of an issue, given you already have to have a decent player age (not new) to play it.

The description I'll touch up on though.

**Comment by EldritchSigma** [comment]
Jerraman would allow awakening without any risks. In lore that isnt a thing as far as I am concerned, awakening always has a risk as it basicly rewires your brain and the way you think. In other words it makes you special in the head. The flavortext is being reworked so it isnt the "evil epsilon army copypasta that the foundation originally was".

**Comment by EldritchSigma** [comment]
I love it but hey I am biased because I play somebody whos special in the head.

**Comment by Sparrowbird611** [comment]
That's a fair reason, though I think there should still be some legal way to awaken, even if it comes with risks.

On another note, why exactly was the psyker man given a point buff? 20 is a fair number of points, 30 seems excessive, especially given his innate powers.

**Comment by Roland410** [comment]
If this is what's going to happen to the FADV, please revert it entirely, as it is totally different from what I had in mind.

**Comment by EldritchSigma** [comment]
Lets see: You need atleast trained athletics to not suffer from the epic rng heart attack. Better Master.

Trained weapons so you dont make yourself a fool by missing PB shots (yes I know you arent supposed to go into combat but lets face it, it happens eventually and RNG on guns is shit), then background shit for character skills and you are pretty much done. Used to be 26 or 28 afaik, should be fine with either of those, but twenty is not enough considering athletics is kind of a must pick together with firearms since fuck missing point blank shots.

**Comment by Roland410** [comment]
It doesn't matter, if Carl doesn't do it, I'm reverting the whole FADV stuff tomorrow when I get home. By the way, any points set for a job, unless you disable points from age, means they get +8 points, so technically it has 28 currently.

**Comment by EldritchSigma** [comment]
Ah 20 points are fine then if the skill buff (+8 points) applies, wasnt aware that would be a thing.

Anyhow. Mind elaborating on why you think this isnt in the spirit of the advisor?

Foundation lore got changed a while back, they arent Yuri from RA2 anymore. There is nothing in lore regarding the Free Psi drug you made. It was literally just that. That and people kind of dont want to play mentalist without the psi gimmick because that was the only thing they got for doing since alot of people wont even use the psychologist/mentalist.

**Comment by Roland410** [comment]
The whole role got changed, simple as that, and since I am the copyright owner of the changes, I have decided to revert it.
Everyone can have their shitty psionic interrogator mentalist back as well, since the revert will put it back to that state.

**Comment by MarinaGryphon** [comment]
> The whole role got changed, simple as that, and since I am the copyright owner of the changes, I have decided to revert it.

No. Your changes were released under the AGPLv3 when you made the modification and it was committed. You're trying to spit in the face of copyright law because you don't like a perfectly legal modification to the code. You have no ownership of it now that it's been committed to the repo.

**Comment by Pacmandevil** [comment]
cringe

**Comment by Rayfod** [comment]
I do not understand why you are currently feel angry @Roland410 ?

**Comment by ike709** [comment]
> and since I am the copyright owner of the changes

Actually, you agreed to the terms of the AGPLv3 license on any code you've committed to the repo. You can't force them to remove it on the basis of copyright.

**Comment by EldritchSigma** [comment]
I dont understand where the problem lies in having both mentalist and advisor, they both cover completely different fields.

**Comment by SilvernKell** [comment]
It didn't really feel like it fit and I like the removal of it, just to provide some context for other people, here are my thoughts playing advisor the first time it was in the game :
- Do I have to keep faxing the Cuchulain about this kind of thing? Psions should be noted down, permission should be asked, guidelines should be very specific, waivers should be signed for drugging people, etc etc
- Do I have to ask the captain?
- This isn't safe, why the heck would I do this? (As I awaken an insanely strong mule 5 minutes later)
- If I'm supposed to teach psions to control it, it seems lore breaking, and overall confusing because they just instantly have powers. And if they don't, then it has no bearing or impact on the round and is just me being selfish by making them sit and "learn" them ic
- Three eye is super illegal and Jerraman is super three eye
- My job is MOSTLY to keep people safe right? So I don't think I'd want to just give up these secrets for nothing, and if someone was being awoken it'd make more sense that they'd have to GO to the institute to do that, both to ensure training from multiple people and that I'm not abusing a secret little cabal, and because Cuchulain wants to be the head honcho and recruit psionics as researchers, teachers and advisors like myself. Gotta build up loyalty and persuade them over somehow.
- It's going to literally kill most people that use it and it'll be such a meme.

**Comment by EldritchSigma** [comment]
@SilvernKell Free Psi/Super Three-Eye is removed.

New psions are contested by various organization (NT Psychic Corps and Foundation mostly) from what I can tell. 

Foundation are the "good guys" they want to train them and help them understand, kind of like an overprotective parent figure. NT Psychic Corps are the bad guys so to say. Think of Red Alert 2 Epsilon Army (Yuri). Forced awakening is always dangerous. Basicly the Advisor is to introduce new psychics to what their powers are and what will happen, teach them etc. But forcing an awakening shouldnt be a thing, as hunting down psykers just because they are psykers.

Lots of the flavortext regarding the role has changed, its now more a supporting role instead of some grimdark G-Man.

**Comment by SilvernKell** [comment]
It would honestly be pretty cool if you could have the darker side, especially it being an NT ship, and pick NT psionic corps advisor.
Also kind of a bummer they can't be IPC >_>
But yeah, with it being an NT ship it sorta feels like they'd more want to recruit into that faction, then, and not vie for control with Cuchulain

**Comment by EldritchSigma** [comment]
Yeah you get to choose between foundation psychic advisor or NT psychic advisor from what I can tell.

**Pull request merged**
