### PR TITLE
some exoplanet ruin about bluespace :)

### PR DESCRIPTION
**Pull request by gilvian**
death, death to all who touches the blue liquid

## About The Pull Request
Adds a new exoplanet ruin, this time it might be deadly judging by the intelligence of some of our players always being on harm and pushing people around :)
<details>
  <summary>Here's how it looks for those who don't want to be spoilered</summary>
    
image

    </details>

## Why It's Good For The Game

new exploration content

## Did You Test It?

yes :)

## Authorship

Myself for creating it
StrongDMM for being a mapping tool

## Changelog

:cl:
* rscadd - New Exoplanet structure about bluespace liquid
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
Is that the bluespace river tiles?

**Comment by gilvian** [comment]
> Is that the bluespace river tiles?

yes, using the simulated atmos-less version so nothing should break, only thing that can happen is explorer is getting pushed in. 
Did the simular ruin on Vesta and nobody fell into them since they were more careful

**Comment by Cupax3** [comment]
> > Is that the bluespace river tiles?
> 
> yes, using the simulated atmos-less version so nothing should break, only thing that can happen is explorer is getting pushed in. Did the simular ruin on Vesta and nobody fell into them since they were more careful

Iirc, the bluespace river tiles have a custom proc on step on that instagibs. Just want to make sure that it is an intentional choice for the ruin.

**Review by Kaksisilma — APPROVED** [review]
Everything looks OK. This can be merged unless another maintainer objects.

**Pull request merged**
