### PR TITLE
Disables fluids.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
Requested by @Andromeda-K22 due to apparent lag issues. I have left the code commented in despite being in source control as this should be temporary and it would be a shame for it to be forgotten when the underlying source of the lag is found.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
I have compiled this but I haven't tested it, I make no promises.

**Comment by MistakeNot4892** [comment]
I don't think deleting the code is wise in this case because it will lead to the feature being left disabled permanently by pure inertia.

**Comment by MistakeNot4892** [comment]
Tested, it's fine locally.

**Comment by BurgerLUA** [comment]
Conflicts need to be resolved and I will merge.

**Pull request merged**
