### PR TITLE
renames thalers to something less (more) dumb

### PR DESCRIPTION
**Pull request by chaoko99**
🆑 chaoko99
rscadd: Resprited thalers.
rscadd: renamed thalers to Brouzouf
🆑 
"Brouzouf" is TEMPORARY. I don't have a good name yet.

### CODE REVIEW

**Comment by chaoko99** [comment]
I know it's stupid but I consulted nobody for a name. It was GONNA simply be "dosh" at the inception of this.

**Comment by MemedHams** [comment]
Ok- I understand that you went to the trouble of making this PR, but Thalers is a believable and satisfying name for money. Why change it?

**Comment by chaoko99** [comment]
Thaler always felt unnatural to me in some way.   Someone in the discord put it well, calling it "hipster lore".

It's an ancient standard, https://en.wikipedia.org/wiki/Thaler, it's like making a new currency called "Drachmas"

**Comment by chaoko99** [comment]
For that matter, they're not exactly weird colored dollars anymore, so they might as well get a name to match

**Comment by Roland410** [comment]
Not a fan of the rename or the sprite (which looks like a crossbreed between an egg and a soda can).

From a code perspective, you have removed the 1000 sprite, but modified the 500, while removing both from code.

**Comment by chaoko99** [comment]
I ran out of good color combos, so I reduced the maximum amount from the list. The 500... I didn't like, but at least felt obligated to put in the code.

**Comment by MemedHams** [comment]
Just some advice: The name of a type of money should be short, two syllables at best, and should not have any significant emphasis that will make it difficult to say. Dollar(Do-lar) is probably the golden standard for this. It's extremely simple and literal to pronounce, being even shorter then it's written form, and has no complex noises that would make it difficult to translate over barriers of linguistic type, knowlege, and age. Brouzouf(Brouh-Zhoof) is not... well, great, for two reasons: It's pronunciation is long and emphasized, and it contains at least one complex noise(The guttural "Brouh"). It seems like a simple thing but the name and attributes of a monetary system have a pretty significant, if subtle effect on worldbuilding, and it can be difficult to find one that has good roll-off-the-tongue attributes.

**Comment by chaoko99** [comment]
Reminder: The current name is BIG TEMPORARY until someone comes in with something better that isn't just the old timey name for dollar.

But not credit. Credit is boring.

**Comment by MemedHams** [comment]
I didn't realize how interested I was in this sort of thing until you posted this. Scuse me while I go look up the names of money systems in history and popular fantasy.

**Comment by chaoko99** [comment]
honestly actually I'd be totally down with calling them Drachmas

**Comment by Sparrowbird611** [comment]
I preferred the other sprite tbh, but it's not terrible.

But what in GODS NAME is that name. Really man, leave it as thaler until you get a good one, don't literally name it "broseph."

**Pull request closed without merging**
