### PR TITLE
Adjusts the costs of "loud" traitor items

### PR DESCRIPTION
**Pull request by OolongCow**
Rather than nerf good weapons, the costs of several have been increased to come more in line with equally as powerful weapons. Additionally, the costs of several weapons that see next to no use has been decreased to encourage traitors already taking "core" items (emags, parapens, etc.) to pick them up with their spare TC.

Replica Pistol: 16TC
To give a lot of context to the later changes, let me start this off by saying that while I have not changed the Mk58's TC cost at all, it's still very important. It's one of the few traitor items in this category that is fairly and intelligently-priced, and a lot of the changes I made to cheaper guns has to do with their power relative to it. This is the "baseline" gun.

Zip Gun: 4TC -> 1TC
I don't expect anyone will take this even now, but this leaves it more available for gimmicks or using up the very last telecrystal you have.

Small Energy Gun: 16TC -> 8TC
It's never used and is pitifully weak for what it is. Hopefully now it will find its way into the hands of traitors with a few TC left over.

Dart Gun: 20TC -> 12TC
An alternative to the syringe gun. Seeing as the syringe gun is easily stolen by anybody who's likely to be making chemicals anyway, reducing its price should free up more TCs for non-medical traitors to buy chems that they can load into it.

Energy Crossbow: 20TC -> 32TC
An incredibly cheap, ammo-less, self-recharging weapon should not be near-silently and instantly downing anybody it's shot into. Touching its TC cost is an alternative to simply removing the stun, which would make it worthless.

Energy Sword: 32TC -> 54TC
Let's be honest, here. The energy sword has become the weapon of choice for traitors who just want to click spacemen on par with the assault rifle. At its current cost, which is lower than a machine pistol with a single magazine, it totally crowds out all other options at its price point, and is pitifully easy to buy along with anything else a traitor could want. Inversely to the decreases in prices in this PR, which are meant to ALLOW traitors to take weaker weapons with spare TC, it's very apparent that when you pick the energy sword, you should be committing a lot of your TC to it, as is rightfully the case with the AR. Someone who buys the energy sword should be very dangerous, but not have as much wiggle room as they currently have to buy any and every thing they could ever want from the uplink. The energy sword should be the main event, not something literally every traitor buys because it's dirt cheap and stronger than everything else in the price range.

Small Silenced Pistol: 32TC -> 20TC
Considering the weak power of its caliber, the questionable use of silencing gunshots when so many other, better silent options exist, and the general lack of people using it, it's clear this weapon is a "flavor" gun. Anybody using it is likely doing so because of a gimmick or for style points, and a price decrease should allow those brave and robust souls to grab a few extra small items, or fit this into another gimmick.

Energy Gun: 32TC -> 24TC
Just a remnant of Bay's "guns bad" mentality. It's a smartgun without an ID lock. It shouldn't be the same price as the old energy sword, and giving traitors more viable energy weapons and stuns in general should help keep security on its toes.

Ion Pistol: 20TC -> 32TC
Rather than nerfing ions' actual effect, making them a situational pick that requires more commitment from traitors should prevent them from just being picked up with spare TC to remove a synthetic from the round in a single magazine.

Magnum Revolver: 56TC -> 52TC
Big iron can stand to be a little bigger. Should (usually) be enough for an extra speedloader for what will generally be the big ticket item for most traitors.

Standard Machine Pistol: 37TC -> 30TC
Lowering the price should (hopefully) let traitors grab some extra items. The machine pistol should be a high-tier sidearm, not a dumpster-tier main weapon.

Sawn-off Shotgun: 34TC -> 26TC
Similar to the machine pistol, the sawn-off should be a good sidearm, not a bad primary. The ammo is hard to handle in the middle of combat, and with only two shots, this thing shouldn't be anywhere near its current price.

Standard Military Pistol: 40TC -> 20TC
It's almost identical to the Replica Pistol in terms of stats. All it has going is no jams (pointless if you have master firearms, which all traitors buying guns do) and 1 more accuracy. It should not be more expensive than the current esword.

Small Revolver: 24TC -> 12TC
A cheap sidearm for those who are just short of enough to buy the Replica Pistol.

Energy Shield: 22TC -> 28TC
Alone, the energy shield isn't terribly threatening, but when paired with the energy sword, anyone with even a remotely threatening set of armor becomes a killing machine, 1v6ing security while high on stims. With a combined cost of 72TC (the same as an AR), this change means that traitors who opt to go this route can't simply load up on both items AND grab everything else they need to go to town immediately. Traitors who go esword + eshield will be hurting for telecrystals, and have to resort to stealing from the ship what they need in order to go on a proper rampage, meaning more interaction with the ship, and more chances to be busted. This change comes as an alternative to simply gutting the esword and shield altogether, and should hopefully prevent the eternal blood-red hardsuit man from walking out of maintenance unannounced and killing half of the security team during code green.

:cl: OolongCow
balance: Adjusts "loud" traitor item costs
/:cl:

### CODE REVIEW

**Comment by Roland410** [comment]
Esword should be between 40-50.
Ion pistol is incredibly niche and not as powerful as the ion rifle, I wouldn't touch the price.
Eshield should be like 40-45 as well.

**Comment by OolongCow** [comment]
How does this even fail Travis.

Why God.

**Comment by OolongCow** [comment]
Found the issue. Fixed. Should pass Travis now.

**Comment by OolongCow** [comment]
Additional explanation on the Energy Sword and Energy Shield specifically:

Master CQC's stats, plus the flat 50% parry chance of the energy sword, plus the deflect chance of the energy shield, on top of high-tier armor, makes an antag practically invincible. Coupled with stims and zerk, an antag playing to win currently cannot lose to anything but the most meta, powergamey and robust security players the server has, sweating as hard as humanly possible and landing a lucky shot that also hits an organ. And that's if the antag is even biological.

And this can currently be done, from roundstart, with only the TC you start with.

The point of making these two items in particular so apparently expensive is so that the iconic antag loadout is not forever dead due to direct nerfs to its effectiveness, but made more difficult to achieve. Either requiring traitor cooperation (which secondarily tends to prevent such a powerful strategy from showing up on lowpop), or requiring theft from the ship itself.  I'd like, in the future, to add more melee antag options, so that the energy sword isn't either good or bad, dragging up or down several other items with it.

Chainsaw, anybody?

**Comment by OolongCow** [comment]
Okay, it's now failing Travis on the Atoms subsystem.

`## UNIT_TEST ##: [SUBSYSTEM - ATOMS: All atoms shall be initialized.]: Uninitialized atom: The lattice (/obj/structure/lattice) ([0x2024b94]) (NULL) (0,0,0) (NULL)
## UNIT_TEST ##: [SUBSYSTEM - ATOMS: All atoms shall be initialized.]: Uninitialized atom: The lattice (/obj/structure/lattice) ([0x2024b97]) (NULL) (0,0,0) (NULL)
## UNIT_TEST ##: [SUBSYSTEM - ATOMS: All atoms shall be initialized.]: Uninitialized atom: The lattice (/obj/structure/lattice) ([0x2024c37]) (NULL) (0,0,0) (NULL)
## UNIT_TEST ##: !!! FAILURE !!! [SUBSYSTEM - ATOMS: All atoms shall be initialized.]: There were uninitialized atoms.
## UNIT_TEST ##: *** SUCCESS *** [SUBSYSTEM - INIT: Subsystems shall be initalized]: All susbsystems have initialized properly
## UNIT_TEST ##: [SUBSYSTEM - ATOMS: Shall have no bad init calls]: Path : /obj/structure/lattice 
- Qdel'd in New()
## UNIT_TEST ##: !!! FAILURE !!! [SUBSYSTEM - ATOMS: Shall have no bad init calls]: Atoms had bad initialization calls.`

I'll try to figure out why exactly this is happening in the morning.

**Comment by Roland410** [comment]
The atom fail is unrelated.

**Comment by Jackofashepard** [comment]
This PR is good overall but the price on the e-sword and shield are far too high. You need to keep in mind that for any race other than meme dionas and prommies its barely worth taking the shield and sword as a single bullet passing the shield means death for you. Also the sword alone is seriously not worth the TC, if not used in combo with the shield its literally asking security "hey shoot me once so i can lose my organs and die please"

**Comment by OolongCow** [comment]
Readjusted cost of Energy sword and shield following discussion on the discord and crunching what antags can buy after grabbing/reserving TC for both. Energy Sword (64TC -> 54TC) and Energy Shield (56TC -> 30TC)

**Comment by OolongCow** [comment]
Reduced the cost of the Magnum Revolver by 4TC after crunching the numbers and comparing it to other weapons near its level of power.

**Comment by Sparrowbird611** [comment]
E shield price is acceptable, E sword is far too high. 38-48 would be acceptable.

I'd also reconsider the machine pistol a little bit though. It's essentially an SMG you can combo with the e shield, and it's one of the first good combos I've seen used with an energy shield.

Everything else seems good.

**Comment by Sparrowbird611** [comment]
Also, I'd consider lowering the ion gun slightly. A little known gamer tip is that the traitor PDA sells 1 TC haywire slugs, AKA ion bolts for shotguns. Combined with your change to the zip gun, (If you use a zipgun to fire anything other than haywire slugs you're doing it wrong) it's even more outclassed than it previously was, since it had the disadvantages of being an energy weapon (Blast out your own battery time) amongst other things that made it less viable.

**Comment by OolongCow** [comment]
> E shield price is acceptable, E sword is far too high. 38-46 would be acceptable.

It will not be allowed to survive in its current state at that price. Not after the hordes of FBP and promethean antags loading up on them both and soloing security. It either needs a significant price increase, or someone coming behind me will gut it until it's useless, which is a real shame for the only real melee traitor item.

**Comment by Sparrowbird611** [comment]
If you got crushed by an FBP, that's on you guys, given sec has ion weaponry in the armory.

Proms are broken, which is a known fact, and they're being disallowed from antagonists because of it.

Still, I see your point. Lets see how it goes for now.

**Comment by Roland410** [comment]
I mean, this is the last time I'll say it, as I think most people just ignore it. Prommies will be reworked when I have time.

**Comment by OolongCow** [comment]
> If you guys got crushed by an FBP, that's on you guys, given sec has ion weaponry in the armory that literally can AoE cuck it.
Not when they break into the armories and throw all your ions into space on medium-low pop without an AI on.

**Pull request merged**
