### PR TITLE
Foundation Advisor job, psionic changes, minor fun stuff

### PR DESCRIPTION
**Pull request by Roland410**
🆑Roland410
rscadd:Foundation Advisor (FADV from here on) role has been added, their job is to oversee psions, more info below.
rscdel:Counselor/Mentalist no longer has psionic powers, and the Mentalist alt-title was removed as such.
maptweak:Repurposed the VIP room for the FADV.
tweak:Crewmembers/offsites now have a 10% chance to be LATENT psionics (need to awaken with Three Eye, Jerraman, or near braindeath), from a whopping 1% chance.
tweak:Moved the Tinker psi ability to operant level, and gave it a multitool option.
rscadd:Added a new chem, called Jerraman, the FADV starts with 20 vials of this in his secure vial carrier, 4 units each. It's used to safely awaken a person, but you don't want to OD on it. OD limit is 5 units for reference.
rscadd:Added a fax destination called The Foundation, for faxing them about psionic issues etc. or if a badmin is online, maybe even getting some Foundation agents sent, if the situation is dire.
maptweak:Removed psi dampeners from the armory, moved it to the FADV's closet, two boxes.
maptweak:Removed the psi meter (assayer) from the counselor's office, as they don't need it anymore.
tweak:Crewmembers/offsite spawns now have 2 latent faculties instead of just 1.
tweak:To compensate, mules are guaranteed to get 3 latencies.
tweak:Traitor psi amp (crown) can now boost 2 faculties to master instead of 1.
tweak:Generally reduced cooldown (but not psi use) on psi powers.
tweak:The psi monitor (used for psi dampener implants) can only be used by the FADV, CO and XO now, unless you emag it.
tweak:Changed the Three Eye recipe to be easier to make, but you get less now.
bugfix:Psi dampener implants can now properly be overloaded to break them with psionic powers instead of just EMP vulnerability.
maptweak:Changed the bridge to only have one long-range holopad, as it was kind of redundant to have two.
tweak:Increased the chance to awaken from Three Eye OD and near-braindeath to 50%.
tweak:Psi dampener implants start on the logging option, but the implanters in the box can be used to change that before implanting.
/🆑

Picture of the FADV office:
image

So yeah, this is kind of a big PR, which should make psionics be more commonly seen, while keeping them rare enough to not be there every round, while it also makes the counselor actually be a mental health professional again instead of a psionic interrogator that most people did.

The Foundation Advisor's main job is to oversee psions, including their awakening (tools provided for it), and voluntary or involuntary suppression of a psion's powers. To be clear, they are NOT a psion hunter, but more of a representative/advisor/diplomat guy. Rogue psions still fall under security's jurisdiction, but the FADV is allowed to help with the control part, especially considering only they have the psi dampener implants now.

### CODE REVIEW

**Comment by SilvernKell** [comment]
I love~ 
It's out of date with main branch RN though.
Advisor is a psion, yes? They have the powers counselor used to have?

**Comment by EldritchSigma** [comment]
Yes. 

...Yes...

...The signal.. the signal... the signal...



New replacement job for my fucking lizard at last so I can just be sitting in the bridge and do jackall...

**Comment by Roland410** [comment]
The FADV has operant level psionics in all four trees, forgot to clarify.

**Comment by EldritchSigma** [comment]
Hehe add Telepathy for the memes..

Also they are contractor correct?

**Comment by Tename** [comment]
Mentalist is already extremely boring, while I like the changes that make psionics more common this removes like 60% of the mentalists job. These changes should just be added as an additional job of the mentalist themselves or just remove mentalist all together. No one sets their records, few set mental health issues in their records, and those that do usually don't even RP them out and forget about it. Psionics is about the only thing that gives them a decent amount of interaction.

Also, the bridge two bridge holopads is so someone can call in while the bridge is calling out since it is the highest called holopad on the server please don't remove it. Second, is there supposed to be a bookshelf blocking the door into maints I have never entered the VIP room.

**Comment by SilvernKell** [comment]
This sounds absolutely fucking mint, Roland. Well done and good job honestly on making this much cleaner.

I would however suggest for later removing mentalist from the counselor titles and adding like, therapist or psychologist or whatevers.

Anyway this was a really great Idea and I can't look forward to use it as half of why I'd had enough with bay was their disallowance of certain races using psionic mentalist, plus this is just gucci

**Comment by Roland410** [comment]
> Hehe add Telepathy for the memes..
> 
> Also they are contractor correct?
No, they're their own "faction", civilian though.

**Comment by EldritchSigma** [comment]
Alright they get 20 skillpoints, thats less than what civis get. Civis get 26.

All other advisor rolls get 32, its fair because the guy has psi. Though atleast up it to 24 so its on par with mentalist and science stuff. Guy is in an advisor position and should have some ya know.. skills so they have some background thing to play with. Athletics is kind of a must have skill atleast at trained because its such a meme.

**Comment by EldritchSigma** [comment]
Seriously though I LOVE this.

**Comment by Roland410** [comment]
000

> Mentalist is already extremely boring, while I like the changes that make psionics more common this removes like 60% of the mentalists job. These changes should just be added as an additional job of the mentalist themselves or just remove mentalist all together. No one sets their records, few set mental health issues in their records, and those that do usually don't even RP them out and forget about it. Psionics is about the only thing that gives them a decent amount of interaction.
> 
> Also, the bridge two bridge holopads is so someone can call in while the bridge is calling out since it is the highest called holopad on the server please don't remove it. Second, is there supposed to be a bookshelf blocking the door into maints I have never entered the VIP room.

Mentalist alt-title was removed, gonna put it in the PR's description in a second.

**Comment by ProbablyCarl** [comment]
TRAVIS AAAAAAAAAAAAAAAAAAAAAA

**Comment by Rayfod** [comment]
There is a few things that I could see become a problem, one of them is the
```/datum/reagent/jerraman
	name = "Jerraman"
	taste_description = "liquid starlight"
	description = "A rare and expensive drug used legally by professionals to awaken psionic latencies in those who possess them, dangerous in higher doses."
	reagent_state = LIQUID
	color = "#d0ff00"
	metabolism = 1
	overdose = 5
```
To overdose at 6u instead
And
```
/datum/reagent/toxin/carpotoxin = 1
```
Is usually what is the hardest to find as a chemist, which is what stops most people from wanting to make it.

**Comment by Roland410** [comment]
> Alright they get 20 skillpoints, thats less than what civis get. Civis get 26.
> 
> All other advisor rolls get 32, its fair because the guy has psi. Though atleast up it to 24 so its on par with mentalist and science stuff. Guy is in an advisor position and should have some ya know.. skills so they have some background thing to play with. Athletics is kind of a must have skill atleast at trained because its such a meme.

This is a bit outdated pic, but with 20 points, this is an easily doable skillset, since it adds 8 points from age:
image

**Comment by Roland410** [comment]
> There is a few things that I could see become a problem, one of them is the
> 
> ```
> 	name = "Jerraman"
> 	taste_description = "liquid starlight"
> 	description = "A rare and expensive drug used legally by professionals to awaken psionic latencies in those who possess them, dangerous in higher doses."
> 	reagent_state = LIQUID
> 	color = "#d0ff00"
> 	metabolism = 1
> 	overdose = 5
> ```
> 
> To overdose at 6u instead
> And
> 
> ```
> /datum/reagent/toxin/carpotoxin = 1
> ```
> 
> Is usually what is the hardest to find as a chemist, which is what stops most people from wanting to make it.

OD is intentionally 5 units, so you can't just easy-mode it with a syringe, but to be fair, the OD stuff is more RP than mechanics.
I've made it easier to make Three Eye, not going to make it super-easy. In a separate PR Three Eye is being added to the uplink.

**Comment by Rayfod** [comment]
I mean, they get a syringe in the
```/obj/item/weapon/storage/secure/briefcase/jerraman
	name = "secure vial carrier"
	icon = 'icons/obj/storage.dmi'
	icon_state = "fbriefcase"
	item_state = "fbriefcase"
	desc = "A large briefcase designed to carry vials of chemicals, with a digital locking system."
	startswith = list(/obj/item/weapon/reagent_containers/glass/beaker/vial/jerraman = 20, /obj/item/weapon/storage/box/syringes = 1)
```
Which is why I'm a little confused on the OD.
And they do need at least fundamental weapon expertise IMO, as they are a command staff.

**Comment by Tename** [comment]
> 
> 
> > Mentalist is already extremely boring, while I like the changes that make psionics more common this removes like 60% of the mentalists job. These changes should just be added as an additional job of the mentalist themselves or just remove mentalist all together. No one sets their records, few set mental health issues in their records, and those that do usually don't even RP them out and forget about it. Psionics is about the only thing that gives them a decent amount of interaction.
> > Also, the bridge two bridge holopads is so someone can call in while the bridge is calling out since it is the highest called holopad on the server please don't remove it. Second, is there supposed to be a bookshelf blocking the door into maints I have never entered the VIP room.
> 
> Mentalist alt-title was removed, gonna put it in the PR's description in a second.

I am not talking about the title itself, more the entire job, it has little to no content and this strips its already bare content.

**Comment by EldritchSigma** [comment]
I know the skillset is set so low so no gamer decides to pick master CQC and uses the damage buff to psiblade the antags (Yes, thats a thing). Still 20 seems really really low even for a psyker. 24 from mentalist would be just a bit less strict on what they can do.

**Comment by Roland410** [comment]
> I mean, they get a syringe in the
> 
> ```
> 	name = "secure vial carrier"
> 	icon = 'icons/obj/storage.dmi'
> 	icon_state = "fbriefcase"
> 	item_state = "fbriefcase"
> 	desc = "A large briefcase designed to carry vials of chemicals, with a digital locking system."
> 	startswith = list(/obj/item/weapon/reagent_containers/glass/beaker/vial/jerraman = 20, /obj/item/weapon/storage/box/syringes = 1)
> ```
> 
> Which is why I'm a little confused on the OD.
> And they do need at least fundamental weapon expertise IMO, as they are a command staff.

The vials all have 4 units of Jerraman, so you can't OD them by default, and they are as much command staff as the SCGR or CL. You have the option as you can see in the pic above to take both CQC or WT skills, it's not restricted.

**Comment by Roland410** [comment]
> > > Mentalist is already extremely boring, while I like the changes that make psionics more common this removes like 60% of the mentalists job. These changes should just be added as an additional job of the mentalist themselves or just remove mentalist all together. No one sets their records, few set mental health issues in their records, and those that do usually don't even RP them out and forget about it. Psionics is about the only thing that gives them a decent amount of interaction.
> > > Also, the bridge two bridge holopads is so someone can call in while the bridge is calling out since it is the highest called holopad on the server please don't remove it. Second, is there supposed to be a bookshelf blocking the door into maints I have never entered the VIP room.
> > 
> > 
> > Mentalist alt-title was removed, gonna put it in the PR's description in a second.
> 
> I am not talking about the title itself, more the entire job, it has little to no content and this strips its already bare content.

Out of the scope of this PR honestly. It's an RP role that people can play. We have the SCGR and CL which are both as useful as the counselor mechanically, and we have those as well.

**Comment by ProbablyCarl** [comment]
@Tename 
Mentalist/Psychiatrist already had issues. While this removes a thing from it, making it even more devoid of content, it pretty much only had psionics as filler content.
Given it's an RP heavy role.

**Comment by Roland410** [comment]
> I know the skillset is set so low so no gamer decides to pick master CQC and uses the damage buff to psiblade the antags (Yes, thats a thing). Still 20 seems really really low even for a psyker. 24 from mentalist would be just a bit less strict on what they can do.

Mentalist has a reason to invest in medical skill etc. unlike the FADV.

**Comment by Tename** [comment]
> 
> 
> > > > Mentalist is already extremely boring, while I like the changes that make psionics more common this removes like 60% of the mentalists job. These changes should just be added as an additional job of the mentalist themselves or just remove mentalist all together. No one sets their records, few set mental health issues in their records, and those that do usually don't even RP them out and forget about it. Psionics is about the only thing that gives them a decent amount of interaction.
> > > > Also, the bridge two bridge holopads is so someone can call in while the bridge is calling out since it is the highest called holopad on the server please don't remove it. Second, is there supposed to be a bookshelf blocking the door into maints I have never entered the VIP room.
> > > 
> > > 
> > > Mentalist alt-title was removed, gonna put it in the PR's description in a second.
> > 
> > 
> > I am not talking about the title itself, more the entire job, it has little to no content and this strips its already bare content.
> 
> Out of the scope of this PR honestly. It's an RP role that people can play. We have the SCGR and CL which are both as useful as the counselor mechanically, and we have those as well.

Its an RP role that barely gets any interaction because it is only used for a few very specific events. This is just going to make Counselor like Counselor in every other server where antags just take it for the nothing to do and free medbay access. As I have said, no one really does that sort of RP, so if you are going to remove Psionics from it, you might as well just make it a role title for some other job and remove it altogether.

**Comment by Roland410** [comment]
> > > > > Mentalist is already extremely boring, while I like the changes that make psionics more common this removes like 60% of the mentalists job. These changes should just be added as an additional job of the mentalist themselves or just remove mentalist all together. No one sets their records, few set mental health issues in their records, and those that do usually don't even RP them out and forget about it. Psionics is about the only thing that gives them a decent amount of interaction.
> > > > > Also, the bridge two bridge holopads is so someone can call in while the bridge is calling out since it is the highest called holopad on the server please don't remove it. Second, is there supposed to be a bookshelf blocking the door into maints I have never entered the VIP room.
> > > > 
> > > > 
> > > > Mentalist alt-title was removed, gonna put it in the PR's description in a second.
> > > 
> > > 
> > > I am not talking about the title itself, more the entire job, it has little to no content and this strips its already bare content.
> > 
> > 
> > Out of the scope of this PR honestly. It's an RP role that people can play. We have the SCGR and CL which are both as useful as the counselor mechanically, and we have those as well.
> 
> Its an RP role that barely gets any interaction because it is only used for a few very specific events. This is just going to make Counselor like Counselor in every other server where antags just take it for the nothing to do and free medbay access. As I have said, no one really does that sort of RP, so if you are going to remove Psionics from it, you might as well just make it a role title for some other job and remove it altogether.

What a lot of people actually forget, is that the CMO and the Counselor have the right to label people mentally unable to do their job, so they can technically relieve the CO of their duties as well etc.

**Comment by SilvernKell** [comment]
Out of the scope of the PR


Anyway, why not give them atleast same skillpoints as a passenger but cap out their fighting skills on trained max or etc etc

**Comment by Tename** [comment]
> 
> 
> > > > > >  ~~Snip~~~
> 
> What a lot of people actually forget, is that the CMO and the Counselor have the right to label people mentally unable to do their job, so they can technically relieve the CO of their duties as well etc.

It's never been used because no one really decides to RP out being mentally unfit for their job because the only thing they will get from it is being unable to do anything the entire round. And if someone is just doing crazy and dumb stuff, like the CO, the counselor is not really in a spot to know any of that, and there are several other people better fit with the same ability to knock the CO out of duty.

**Comment by SilvernKell** [comment]
Tename,
Your conversation is out of the scope of the PR.
Not to be rude but beyond taking the most unused of footnotes from mentalist/counselor it doesn't really do a lot, you'd be better off PR'ing changes to them yourself or someplace else.

I have played as mentalist on bay quite a lot. I was very busy. And everything I did was not psionic. People just wanted to talk to me because I actually did my job properly. In all honesty the one use I had for it (brain cleanse) I used on an amnesiac and they were so low rp they just went "ok"

Psionics doesn't need to be a thing for mentalist for you to get work if you put in some work, gho around and tape flyers up, advertise, find people that seem upset around the ship, you will eventually have people lining up to visit their doc often.

**Comment by SilvernKell** [comment]
@Roland410 The Travis check is probably just cause a couple of files changed don't have empty lines on the end, you can easily see which ones on Github 'files changed'.
I am not certain why personally, but Travis is quite fussy about that. 
I found that files that previously didn't have an additional line seemed to need one after changing. . 
I'm not very experienced (not experienced at all*) but easy fix.

**Comment by Roland410** [comment]
> @Roland410 The Travis check is probably just cause a couple of files changed don't have empty lines on the end, you can easily see which ones on Github 'files changed'.
> I am not certain why personally, but Travis is quite fussy about that.
> I found that files that previously didn't have an additional line seemed to need one after changing. .
> I'm not very experienced (not experienced at all*) but easy fix.

It's totally unrelated to my PR actually, but since Carl is fixing the repo, I'm fixing it.

**Comment by ProbablyCarl** [comment]
Local travis worked get smacked pr travis god

I'll be merging this, as I've seen and signed off on everything.

**Comment by bearrrrrrrr** [comment]
great googly moogly it's all gone to shit

**Pull request merged**
