### PR TITLE
Removal of Collars - Sec Rebalance

### PR DESCRIPTION
**Pull request by ProbablyCarl**
- - -
Tweaks:
 - Removal of collars. These were merged by a now removed individual, despite wishes for such a thing to not come to pass. It's fetish content, and it has no reason to be here.
-
Edit:
- - -
Additions:
 - THE CUBE
 - Security now receives pepperball rounds by default for their weapons, rather than rubber.
 - Rubber mags moved to the Hard Armoury, in place of the lethal mags, and pepperball mags moved to replace old rubber mag spot.
 - Vending for armour has been moved into the Hard Armoury, and made armoury access only.
 - Security Cadet added. This replaces two of the slots Security had received, and act as heavily gimped / new player introductory roles for Security.
- - -
Tweaks:
 - Triage replaced with the CUBE.
 - Old vending machine area for armour pieces filled with a trauma specific medical crate.
 - Beanbag shotgun projectile damage lowered.
 - Job times revised.
 - Arm and leg attachments for armour have been removed from loadout.

### CODE REVIEW

**Comment by ShadeAware** [comment]
I don't really see how it's that big of an issue tbh. These have the potential to be used for more anyway, like being able to put them on simplemobs and pets.

**Comment by Chaznoodles** [comment]
@ShadeAware You already know that's not what they're used for, don't lie to yourself.

**Comment by MarinaGryphon** [comment]
As someone who likes the premise of having collars as accessories/clothing/whatever:
Don't. Wear. Them. To. Work.
Please.
Even if you're a contractor/civilian/whatever. Or even just a passenger. DON'T. You have to spend however long, like, at least several months, with these people. And they've seen you wearing kink gear in public. Imagine how fucking _miserable_ that would be.
Please God remove them.

**Comment by MarinaGryphon** [comment]
At the very least replace them with chokers so that they're not obvious kinkwear. At best, remove them.

**Comment by ProbablyCarl** [comment]
This is why it wasn't speed merged.
Some people want them. Some don't.
This'll remain up, and probably won't be merged if it comes to it.

**Comment by ShadeAware** [comment]
A better way to go about it would probably be allowing people to set custom item names and descriptions to the holocollar, like the ring in the loadout. This let's people make it essentially whatever they want, and allows us to remove all the other bloat collars.

**Comment by ShadeAware** [comment]
Also, EMP action on the holocollar that changes the display name to "Degenerate" and asphixiates the wearer :^)

**Pull request merged**
