### PR TITLE
Changes SM Sprite to something nicer.

### PR DESCRIPTION
**Pull request by AMcilraith**
## About The Pull Request
image
I think this speaks for itself
## Why It's Good For The Game
It adds a more aesthetic sprite
## Did You Test It?
Yes it works
## Authorship
Dr. Farson (I ported it)
Azlan (Made the sprite, Original here - https://github.com/Baystation12/Baystation12/pull/30803)
## Changelog

:cl: Dr. Farson
imageadd Updates supermatter sprite
/:cl:

### CODE REVIEW

**Comment by gilvian** [comment]
alalte yellow sm cock

**Comment by ShadeAware** [comment]
Beautiful

**Comment by Kaksisilma** [comment]
But the old one is iconic 🥺

**Review by Anton-Kr — APPROVED** [review]

**Comment by Cupax3** [comment]
These sprites are from Azlan, I believe. Please add attribution.

**Comment by Cupax3** [comment]
https://github.com/Baystation12/Baystation12/pull/30803 This PR in particular.

**Comment by AMcilraith** [comment]
> 

Done. Attribution added.

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
