### PR TITLE
Replaces the MK59s in the bridge storage with the Sec compact smartgun that doesn't recharge.

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Title. Everything else in it is unchanged.

It had, 3 holsters, 3 MK59s, and 1 handgun ammo box.

3 MK59s became 3 smartguns.
## Why It's Good For The Game
I feel like this makes more sense, considering the bridge could use a energy LTL or bad laser gun considering the massive amount of windows in there, and they don't recharge at all. So I feel like this is fine overall.
## Did You Test It?
image

## Authorship
MJP#4043, Dudeman100-Ckey. 
## Changelog

:cl:
tweak: MK59s in bridge storage replaced with non-recharging compact smartguns.
/:cl:

### CODE REVIEW

**Comment by Jul-Jul** [comment]
I rather not the emergency 'if the bridge is attacked' armory is not nerfed into complete uselessness.

**Comment by Lamasmaster** [comment]
The emergency "if bridge is attacked" armory is tactical armory which should be the one that is relied on, you have escape tunnel on bridge for a reason.

**Comment by Pariah919** [comment]
>I rather not the emergency 'if the bridge is attacked' armory is not nerfed into complete uselessness.
>
Bridge already get ballistics from personal sidearms (BO/SEA/etc) or gun boxes (CO/XO) though, I think this isn't even any kind of nerf.

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
Make an actual locker. Mapping in individual items stinks.

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
