### PR TITLE
Fix Merchant Shuttle + Removing Infantry Armory from D5(Inactive and being looted)

### PR DESCRIPTION
**Pull request by therealslimpeek**
-deletes infantry on torch_areas
-deletes infantry armory on D5(Empty space, mappers can do something cool there)
https://media.discordapp.net/attachments/529565613123829780/723482112296091658/unknown.png?width=696&height=391
+Fix Merchant Shuttle bug
+Give Merchant access to his own windoors(into z1_admin, wheres at the Merchant Vessel is mapped)

**Merchant bug cause**: Deck 5, Infantry Room were expanded over 60, 120, which was colliding with Merchant Waypoint Out, blocking the shuttle to dock or even move out from the Merchant Station, because the console calls the proc can_leave, or something like this.
**Fix**: Deleted Infantry Armoury, since it was not being used. Reshaped outer hull preserving NTSS Dagon original shape.

### CODE REVIEW

**Comment by Superhats** [comment]
Please speedmerge

**Comment by therealslimpeek** [comment]
Oh, Jesus. Some last CI fixing. Just a few things.
Sorry for spamming PR. Sending a CI friendly soon.

**Comment by therealslimpeek** [comment]
Done, thanks god

**Comment by therealslimpeek** [comment]
The final .dmm part gets as aaaaaaaaaaaaaaaaaa, instead of aa \n aa \n aa.
I've tried Sublime, Notepad++, Notepad, Wordpad, uploading the whole file. Can't get over it.
How you guys keep the original formatting?

**Comment by Roland410** [comment]
You need to mapmerge it. It's in the tools folder, but you can probably ask someone on Discord to help you (I'm busy when writing this, but I'd help otherwise).

**Comment by BurgerLUA** [comment]
I almost speedmerged this until I looked at the files changed. Please fix this.

**Comment by therealslimpeek** [comment]
I was getting some sleep, working into this mapmerge now. Thanks for explaining to me. Finalized version coming out soon

**Pull request merged**
