### PR TITLE
Removes cloaking device from research.

### PR DESCRIPTION
**Pull request by Sparrowbird611**
*Breathes in*

~SPEEEEEEEEEEED MEEEEEERGE~

Ok but jokes aside, this thing probably shouldn't be in RnD in it's current state. Total invisibility without a way to be seen through would be fine if it was the rare cloaking suit, or ninja, but being able to print this thing is a step too far.

### CODE REVIEW

**Comment by JohnBigless** [comment]
**SPEEEEEEED MEEEEEEEERGE**

**Comment by Roland410** [comment]
Can we for one day not remove everything from research that is remotely fun or useful? They can only use this themselves with the shitty zero rig anyways from robotics and even that means you need a roboticist. The module also doesn't make sounds silent, and afaik it decloaks you if you try to attack. I honestly don't see any reason for its removal.

**Comment by OolongCow** [comment]
> Can we for one day not remove everything from research that is remotely fun or useful? They can only use this themselves with the shitty zero rig anyways from robotics and even that means you need a roboticist. The module also doesn't make sounds silent, and afaik it decloaks you if you try to attack. I honestly don't see any reason for its removal.

Paralytic pens don't count as attacks for the purpose of decloaking.

**Comment by Roland410** [comment]
I mean, true, but to parapen someone like that, you already need a rig, research to do their job (unless antag scientist), and it won't even let you into areas you couldn't access unless you sneak in, but you essentially block your way out then.
I'd say using this to parapen someone is pretty extreme and should not be grounds to removing it.

**Comment by Dark1Star3s** [comment]
> I mean, true, but to parapen someone like that, you already need a rig, research to do their job (unless antag scientist), and it won't even let you into areas you couldn't access unless you sneak in, but you essentially block your way out then.
> I'd say using this to parapen someone is pretty extreme and should not be grounds to removing it.

In my honest opinion, it should be kept, but make it so they cannot activate the cloaking module unless the RIG is fully deployed, because as it stands, people just use it as a module holder, while they then put actual armor over it and then go invisible. EG: The many times Richard has got his hands on one.

**Comment by Sparrowbird611** [comment]
>can we not remove fun things?

Look who you're talking to.

Jokes aside, I've never seen any of this specific behavior on the cloaking module. As far as I know, you can attach it to any rig, and it will not decloak you as far as I know when firing, though I do recall gun sprites being visible when held and invisible so, I suppose that's the same thing, though rig mounted weaponry can bypass that somewhat if I recall correctly.

I'm perfectly fine with the way it works currently, including the armor memes, but it seems rather strong to be in research with the way RnD works now.

**Comment by Sparrowbird611** [comment]
I'm willing to reconsider this PR, but cloaking in general is an incredibly powerful ability, even in the hands of the unrobust, let alone gamers like plexiant. An Ion rifle is a potential counter to it, but given the fact that soon only one of the guns with have an AoE, and that one is in the EARM, I hear potential issues.

~~I also have nightmares of the day security some how manages to get fully stealth kitted soldiers.~~

**Comment by Sparrowbird611** [comment]
Yeah uh, if burger or any one comes by and looks at this, don't merge this please. Looking into alternative solutions for now.

**Comment by OolongCow** [comment]
> In my honest opinion, it should be kept, but make it so they cannot activate the cloaking module unless the RIG is fully deployed, because as it stands, people just use it as a module holder, while they then put actual armor over it and then go invisible.

This, pretty much.

**Comment by Sparrowbird611** [comment]
I'm going to close this for the time being. There's been another suggestion I'm pursuing. If that fails, I'll reopen this PR.

**Pull request closed without merging**
