### PR TITLE
Removes slipping from soaps and banana peels

### PR DESCRIPTION
**Pull request by Roland410**
🆑Roland410
rscdel:Removes slipping from soaps and banana peels.
/🆑
Comedy gold, but too much of a meme. Lube and water still slips.

### CODE REVIEW

**Comment by Roland410** [comment]
Travis fail is unrelated.

**Comment by Tename** [comment]
But why?

**Comment by Roland410** [comment]
Because I woke up today and decided that they don't need to be able to slip people as it's a shitty meme.

**Comment by BurgerLUA** [comment]
Slipping feels unironically a part of ss13 and I am not really comfortable about having it removed. This will def need a poll.

**Comment by ProbablyCarl** [comment]
It's literally a core combat mechanic

y i k e s

**Comment by Roland410** [comment]
These are two out of the four last slipping methods (outside of space slipping) that I'm aware of. For an HRP server it's a pretty meh meme.
It's quite ridiculous that you can slip on a bar of soap or a banana peel.

**Comment by SouthyOsmanli** [comment]
If you're not slipping all of security and yourself while battling in the CO's bathroom you aren't doing it right.

**Comment by Sparrowbird611** [comment]
No comment tbh. It's funny, and it has uses, but we could do without it and be fine.

**Comment by AdamElTablawy** [comment]
Unnecessary clown nerf.

**Comment by AdamElTablawy** [comment]
@Roland410 Try running as fast as you can and step on a bar of soap.

**Comment by Roland410** [comment]
That'd only be relevant if it respected running like water slips do.

**Comment by BurgerLUA** [comment]
THe poll says that these mechanics are fine. Will close this PR unless someone has a really good argument as to why this should be merged.

**Comment by Roland410** [comment]
Going to close this as the feedback is pretty negative.

**Pull request closed without merging**
