### PR TITLE
Adds a new phoron suit choice.

### PR DESCRIPTION
**Pull request by Rafflesia7793**
## About The Pull Request
Adds Mister Mann's new Security (Alt) sprite to the phoron people's suit customizer.
## Why It's Good For The Game
Adds cool new Security (Alt) sprite to the game.
Doesn't conflict with: https://github.com/BoHBranch/BoH-Bay/pull/1675
Conflicts with: https://github.com/BoHBranch/BoH-Bay/pull/1660 making ShadeAware do more work is good.
## Did You Test It?
image
image
image
## Authorship
Mister Mann, Rafflesia
## Changelog

### CODE REVIEW

**Comment by SilverCelestine** [comment]
Would be nice if there were some colour variations, but overall, I like it.

**Comment by Anton-Kr** [comment]
Any chance you'd be willing to recolor this to something more red to indicate sec? It's alright if not.

**Comment by Rafflesia7793** [comment]
Will forward this feedback to Mister Mann.

**Comment by Plaguewalker** [comment]
> Would be nice if there were some colour variations, but overall, I like it.



> Any chance you'd be willing to recolor this to something more red to indicate sec? It's alright if not.

Unfortunately, it cannot be resprited as then it would ruin the aesthetic of the suit itself.  Also, I thought I mentioned this sprite was a port when Raffe fixed up a simple spelling mistake with it.

**Comment by Rafflesia7793** [comment]
Plaguewalker is Mister Mann, if this was not clear. It would seem they would prefer to go ahead without recoloring it, so it's either merge or do not merge at this point.

**Comment by Anton-Kr** [comment]
Ok why not. Ill review this tomorrow hopefully

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
