### PR TITLE
Suture port

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Ports sutures. ~~Badly~~.

Need new sounds.

## Why It's Good For The Game
Sutures good. Makes medical less of a pain in the ass of waiting your ass to heal.

## Changelog
:cl:
add: Sutures, also not in the game. Thanks to Matttroks101 and the holy Scrungus for their help.
/:cl:

### CODE REVIEW

**Comment by Technobug14** [comment]
Trauma packs already exist. Sutures are wholly unnecessary. Bicaridine + trauma packs will heal you fast, so I don't see the need for TG sutures. This sounds like a skill issue.

**Comment by miniusAreas** [comment]
...What's the point of this? You allready clear up some damage with trauma kits / gauze. From there you need chems to heal - part of medicals gameplay loop.

Unless Sutures fill some purpose and arn't a 1:1 port from TG, then these break the loop completely. Going to say no to this one chief - Medical has it extremely easy as it is.

**Comment by Pariah919** [comment]
>...What's the point of this? You allready clear up some damage with trauma kits / gauze. From there you need chems to heal - part of medicals gameplay loop.

>Unless Sutures fill some purpose and arn't a 1:1 port from TG, then these break the loop completely. Going to say no to this one chief - Medical has it extremely easy as it is.

Don't heal from gauze. It has.. 1 brute heal.
Also have you even read the code? This isn't a TG suture.

**Comment by Squigger** [comment]
To note, these aren't TG sutures. These are IS12 sutures.

**Comment by ProbablyCarl** [comment]
Going to close this for now. Please, if you make any changes to this in the future, toss me a DM. Or an argument. Either-or.
They don't fill a dynamic that is currently present, and would be bloat.

**Pull request closed without merging**
