### PR TITLE
X-Ray Love

### PR DESCRIPTION
**Pull request by Higgin**
Gives the x-ray carbine and energy sniper a bit more to look forward to in the morning with additional AP.

### CODE REVIEW

**Comment by Roland410** [comment]
Ah yes, well atomized PR.

**Comment by Sparrowbird611** [comment]
I get that the marksman's laser needed AP and I agree on that, but I gotta ask.

Is there literally anything the X-ray laser couldn't penetrate with 50 AP? I assume this change may make it pierce ablatives, but that's all I can think of.

**Comment by Higgin** [comment]
Not really, but giving it a bit of extra AP allows it to carry more of its already-lessened damage over.

**Comment by bearrrrrrrr** [comment]
not sure if i'm a fan of arterials not stunning

agree with the rifle though

**Comment by ProbablyCarl** [comment]
Arterial change I'm also not a fan of. Remove it and it'll be golden.

**Comment by Higgin** [comment]
Arterial stun readded.

**Comment by Roland410** [comment]
May want to rename the PR and description to reflect the changes.

**Pull request merged**
