### PR TITLE
Mess/Kitchen/Hydro Remap

### PR DESCRIPTION
**Pull request by Aurelien3189**
Another unnecessarily long work invested into a remap of the mess hall to poorly replicate restaurant style layouts/booths while making hydro less painful to grow plants in.
(Note, images and pictures may not be up to date, such as floor tiles CURRENTLY having their original colours)
image
CURRENT:
image

https://streamable.com/isj46m

In a nutshell:

Kitchen
- Moves mess prep behind kitchen/bar
- Adds monkey cubes and maint shutters (for whatever reason) to the freezer
- Adds trash bag to kitchen
- destroys original remapper's creativity
image

Hydro

- adds 4 more hydro trays, just look at it
image

Mess hall

- Re-adds food vendors, moves jukebox for lack of a better place with this crappy layout
- More chairs and a table setup friendly to restaurant goers and hellish to socially inadept hermits like myself
image

### CODE REVIEW

**Comment by ProbablyCarl** [comment]
Looks great as of current.

We'll be test merging this and #856

**Comment by Roland410** [comment]
I liked the one you posted on Discord more tbh, but this one is fine as well, except a few nitpicks.
Jukebox should be moved to a more central location as it works with vision (unless it properly covers the whole place, not too clear from SS).
Remove the 3 hydro trays on the left or at least the top one as it's pretty odd.
The recharger should be moved to the chess table or the other one, or removed (idk why it exists).
I think you forgot to put the drying rack in hydro and only one botanist locker is there.
The fitness vendor should be moved to the other ones.
The minilathe is not centered for some reason.
Also, this is really nitpicking but wtf is that piping? That's an engineering nightmare.

Overall dig the thing tho.

**Comment by Roland410** [comment]
Oh also, botany has no sink for some reason either, unless I didn't see it.

**Comment by Aurelien3189** [comment]
The _bearcat_, are you shittin' me?
image

**Comment by Roland410** [comment]
Truly the best errors come out on your PRs. Big F.

**Comment by ProbablyCarl** [comment]
Had been test merged. Works just fine.

**Comment by ProbablyCarl** [comment]
I'll be merging this if no one objects.

**Pull request merged**
