### PR TITLE
Ups Colony and SDTF spawn rate

### PR DESCRIPTION
**Pull request by Rav-Nunya**
So, this PR changes the cost of the skrell ship and colony to .2, this was done for, A. i have gotten feedback that people enjoy colony so i think we should try it more often, and B. i play SDTF a fair bit and want to do it more, this can be said to be selfish as i havent heard word from others about it.

### CODE REVIEW

**Comment by Roland410** [comment]
The SDTF spawns often enough in my experience, and what limits the colony the most is the planet type that gets spawned. Not all planets can spawn the colony.
If you tested this and think the colony spawns more often with it, good, but I'd keep the SDTF spawn as-is, or it'll be an almost guaranteed spawn like the Vox are currently.

**Comment by TheOrleans** [comment]
I agree with Roland here, colony spawns quite often I would say. Do you know if increasing the colony spawn rate reduces the spawn rate of others (is there a limit in how many "away sites" and "special sites" can be spawned per round?)

**Comment by Roland410** [comment]
> I agree with Roland here, colony spawns quite often I would say. Do you know if increasing the colony spawn rate reduces the spawn rate of others (is there a limit in how many "away sites" and "special sites" can be spawned per round?)

Technically as there is a budget, increasing the chance (lowering their cost) to spawn means it is more likely to spawn compared to other ruins.

**Comment by Tename** [comment]
Colony upping is good but the SDTF ship is boring and already spawns enough

**Comment by Roland410** [comment]
The thing is, as I said above, the colony spawn is restricted not just by the cost, but by the planet type, it's why you're not seeing it as often as you would want it.

**Comment by BurgerLUA** [comment]
Needs more feedback.

**Comment by BurgerLUA** [comment]
People don't seem to like this PR. Find more people that like it or adjust the PR so that people are happy.

**Comment by BurgerLUA** [comment]
Might close this PR if there isn't a convincing argument as to why this is needed.

**Comment by Roland410** [comment]
Going to close this. If you want it reopened ask a maintainer, but as I said above, it won't solve the spawn rates.

**Pull request closed without merging**
