### PR TITLE
Ascent Ship Turrets

### PR DESCRIPTION
**Pull request by SilverCelestine**
*Adds a variety of Ascent Anti-Boarding turrets to the Seedship and its shuttles. nothing overly excessive.

*The Ascent Ship lacked Anti-Boarding turrets to prevent lazy boarding, also makes boarding shuttles a tiny bit harder.

#Worksonmymachine

### CODE REVIEW

**Comment by Cupax3** [comment]
Hello, please follow the PR template.

**Comment by Kaksisilma** [comment]
Capture4

CI is having a fit over areas. You have an area 'tile' sticking out of the main blob.

**Comment by Armyguy** [comment]
More so, unless they do the same thing as the Vox and Skrell ships, there's no way a turret controller is going to work.

**Comment by SilverCelestine** [comment]
I'm going to close this PR until I can figure out what exactly the issue is. I've combed through all of my changes and redid them, and so far I'm still getting the same issue. I think it may be an issue persisting the ship itself, so I'll start going over it from top to bottom.

**Pull request closed without merging**
