### PR TITLE
Updates SSV

### PR DESCRIPTION
**Pull request by Teragenic**
## About The Pull Request
Updates the SSV. Namely removes the Ascent tools and stuff. Readds proper full toolbelts like before, reverts the removal of a MFC cell. Fixes some areas not being correct due to missile changes. Adds two more frontal turrets with the permission of Anton. Fixes a wall in the observation post not being properly mapped in. Readds the mushrooms for skrell since removal didn't add other food for them.
## Why It's Good For The Game
Fixes things.
## Did You Test It?
Yes.
## Authorship
Teragen#4390
## Changelog

:cl:
* maptweak
/:cl:

SSV Capture2

### CODE REVIEW

**Comment by N8-Toe** [comment]
All PR's should be tested locally, and did you use map merge?

**Comment by Teragenic** [comment]
Map merge? And I tested it now. It's fine. I'm unsure why a test is not working. Because I didn't even touch that area.

**Comment by Teragenic** [comment]
OH I KNOW WHY IT'S FAILING. ITS BECAUSE OF THE TURRETS. yeah, it was always like that. I just copied what Kak did, it works fine ICly. Wondered what it was.

But yeah, everything should be good and tested.

**Review by Anton-Kr — DISMISSED** [review]
In skrellscoutship.dm line 16 change /area/ship/skrellscoutship/command/brig = 10 to 12.

**Review by Teragenic — COMMENTED** [review]
Fixed and done.

**Review by Kaksisilma — APPROVED** [review]
Good to merge.

**Pull request merged**
