### PR TITLE
Rigsuit/Voidsuit fix for Sergal Species

### PR DESCRIPTION
**Pull request by Armyguy**
fixs and adds more races to the list for Vsuits and Rigs

### CODE REVIEW

**Comment by Armyguy** [comment]
Let Stellar get this one

**Comment by ProbablyCarl** [comment]
This serves no purpose.
Why would you add additional spacing?

**Comment by Snownbloodyflowers** [comment]
Actually bother to write changelogs please. This one line doesn't help us at all.

**Comment by StellarTheAwoo** [comment]
PR was heavily changed up. Requested a new look over by the appropriate reviewers.

**Comment by Armyguy** [comment]
Yea and do let me know before its merged if you do want to merge it and note.
The conflict with torch_ranks.dm is do to a hot fix i gave to carl the the copy in the PR is newer but is "from" a older copy of the git so its just yelling about it.

**Comment by ProbablyCarl** [comment]
Temporarily closed until further discussion is had in the appropriate channels.

**Comment by ProbablyCarl** [comment]
Rank edits need to be slapped. We've had Marines added, and some of the content of this PR will likely cause conflicts, among other things. 
Additionally, the three species for the Voidsuits, main and subspecies, is a bit much. Clutter gang.

**Comment by ProbablyCarl** [comment]
Local lad requests material to be merged at specific time.
Gets slapped. More news at eleven.
_Sorry, Army. Had to do it to 'em._

**Pull request merged**
