### PR TITLE
Detethers most ghosttraps from a role pref so they actually work with our playerbase.

### PR DESCRIPTION
**Pull request by chaoko99**
also some sprites from old interspace0.1A that never got used.
🆑 chaoko99
rscadd: New cult sword sprites. Uses Open SS13 orientation style. Looks cool, I promise.
tweak: Decoupled most ghost roles from their role preference and deleted said preferences as nobody seems to have set up their roles.
tweak: Removed the dark void emitted by cultist constructs as they made them essentially impossible to click.
/ 🆑

### CODE REVIEW

**Comment by Roland410** [comment]
Put the stuff other than cult shit back, I don't need 20 notifications that SOMEONE WANTS A PAI or THEY WANT A POSIBRAIN when I'm ghosting, thanks.

**Comment by chaoko99** [comment]
I'm gonna request testmerge on this to see if that's *actually* going to be an issue. People don't often  bother with the posibrains because they never get filled.

**Comment by Roland410** [comment]
It's an issue to me, and I don't want to be put in a posibrain because someone decided to activate one.

**Comment by chaoko99** [comment]
restarting build.

**Comment by BurgerLUA** [comment]
We now need 2 approvals to merge things.

**Comment by chaoko99** [comment]
Note, it appears that this broke PAI's. I will be refactoring them in a separate PR.

**Comment by BurgerLUA** [comment]
> Note, it appears that this broke PAI's. I will be refactoring them in a separate PR.

Please have that PR merged before this one.

**Comment by chaoko99** [comment]
The refactor was too much of a pain. Just gonna revert what broke them.

**Comment by BurgerLUA** [comment]
uhh tell me when you want this PR to be merged

**Comment by chaoko99** [comment]
Now?

**Comment by chaoko99** [comment]
I suppose I wwas a little vague

**Comment by ProbablyCarl** [comment]
Supposedly causes issues with pAIs. Can't confirm as of current.

**Comment by chaoko99** [comment]
image
@ProbablyCarl

**Comment by BurgerLUA** [comment]
What is the status on this PR?

**Comment by chaoko99** [comment]
It's been completed for two and a half weeks.

**Pull request merged**
