### PR TITLE
MERCHANT SHUTTLE BUG FIX (Delete this)

### PR DESCRIPTION
**Pull request by therealslimpeek**
Cause: Deck 5, Infantry Room were expanded over 60, 120, which was colliding with Merchant Waypoint Out, blocking the shuttle to dock or even move out from the Merchant Station, because the console calls the proc can_leave, or something like this.

Fix: Reshaped the Infantry Prep room preserving NTSS Dagon original shape. Infantry Leader room was deleted and all of its contents were moved to Infantry Prep room.
https://i.imgur.com/cFRXlyV.png
**I'd recommend for head admins and head devs to evaluate the infantry continuation since it has not been used and people have just been looting around there.**

(It was mainly on Deck 5, but the secure windoor into the Merchant Vessel was asking for brig_acess, that's why the small changes on z1_admin on part II)

Working good.

### CODE REVIEW

**Comment by Roland410** [comment]
I'd love to believe this fixes it, but.. Deck 5 has nothing to do with the merchant shuttle? It docks on D4.
I don't know what's the plan with infantry, but it seems that it won't come back any time soon, although staff should comment on this, as I have no idea what they discuss(ed) in private.
Additionally, the secure windoors should be using the merchant access, so people can't get behind the counter if it doesn't already.

**Comment by therealslimpeek** [comment]
Not sure why the Travis CI didn't passed it.  I'll try to replace the files instead of deleting all the lines and update it.

**Comment by therealslimpeek** [comment]
@Roland410 yes, I've spent 2 days trying to find the cause on Deck 4, shuttle systems, etc.
Came out that it was the reason. Infantry went over 60, 120, which is the upper-level for the waypoint.
It was blocking the proc that checks if it is dockable. Download and check it out for yourself.

**Comment by Roland410** [comment]
You just need to read why it fails:
## UNIT_TEST ##: [MAP: Station wires shall be connected]: Disconnected wire: south - The power cable (/obj/structure/cable/cyan) ([0x2001810]) (the plating) (58,116,1) (/turf/simulated/floor/plating)
## UNIT_TEST ##: [MAP: Station wires shall be connected]: Disconnected wire: north - The power cable (/obj/structure/cable/cyan) ([0x2001822]) (the deck) (61,116,1) (/turf/simulated/floor/tiled/monotile)
## UNIT_TEST ##: !!! FAILURE !!! [MAP: Station wires shall be connected]: Found 2 cables without connections.

## UNIT_TEST ##: [MAP: Station pipes shall not leak]: Following pipe is leaking: Scrubbers pipe (/obj/machinery/atmospherics/pipe/simple/hidden/scrubbers) ([0x2001783]) (the deck) (59,115,1) (/turf/simulated/floor/tiled/steel_grid)
## UNIT_TEST ##: [MAP: Station pipes shall not leak]: Following pipe is leaking: Air supply pipe (/obj/machinery/atmospherics/pipe/simple/hidden/supply) ([0x2001784]) (the deck) (60,115,1) (/turf/simulated/floor/tiled/steel_grid)
## UNIT_TEST ##: [MAP: Station pipes shall not leak]: Following pipe is leaking: Air supply pipe (/obj/machinery/atmospherics/pipe/simple/hidden/supply) ([0x2001809]) (the plating) (57,116,1) (/turf/simulated/floor/plating)
## UNIT_TEST ##: [MAP: Station pipes shall not leak]: Following pipe is leaking: Air supply pipe (/obj/machinery/atmospherics/pipe/simple/hidden/supply) ([0x200180e]) (the plating) (58,116,1) (/turf/simulated/floor/plating)
## UNIT_TEST ##: !!! FAILURE !!! [MAP: Station pipes shall not leak]: 4 station pipes leak.

## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Infantry Hard Storage(/area/security/infantry/armory) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Infantry Hard Storage(/area/security/infantry/armory) lacks an air scrubber.
## UNIT_TEST ##: !!! FAILURE !!! [MAP: Area Test APC / Scrubbers / Vents]: [1/305]Some areas did not have the expected APC/vent/scrubber setup.

## UNIT_TEST ##: [AREA: Areas shall be coherent]: The Infantry Hard Storage (/area/security/infantry/armory) ([0x4000025]) (56,110,1) is incoherent. Expected 1 subarea, fill gave 4. Origin turfs:
## UNIT_TEST ##: [AREA: Areas shall be coherent]: The deck (/turf/simulated/floor/tiled/monotile) ([0x100555f]) (56,110,1) (/area/security/infantry/armory)
## UNIT_TEST ##: [AREA: Areas shall be coherent]: The plating (/turf/simulated/floor/plating) ([0x1005a10]) (57,116,1) (/area/security/infantry/armory)
## UNIT_TEST ##: [AREA: Areas shall be coherent]: The reinforced plasteel bulkhead (/turf/simulated/wall/r_wall/hull) ([0x1005add]) (62,117,1) (/area/security/infantry/armory)
## UNIT_TEST ##: [AREA: Areas shall be coherent]: The airless plating (/turf/simulated/floor/airless) ([0x1005b9e]) (55,118,1) (/area/security/infantry/armory)
## UNIT_TEST ##: !!! FAILURE !!! [AREA: Areas shall be coherent]: Found 1 incoherent area.

**Comment by therealslimpeek** [comment]
Oh, Jesus. Not really a mapper and theres two years that I don't code, but here I go, fixing this. But the Merchant Dock is golden.

**Comment by Roland410** [comment]
You need to fix the area, the pipes, and the wiring. Also you'll need to remove the armory area as it's not used now.

**Comment by therealslimpeek** [comment]
The whole infantry thing? That was my original idea since I've heard that it was about to be deleted, but I'm not in contact with dev people.

**Pull request closed without merging**
