### PR TITLE
Adds cigarette packets to the loadout

### PR DESCRIPTION
**Pull request by JohnBigless**
mm yum yes cancer stikk

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
Can already buy cigarettes in game. Don't wanna give everything in loadout.

**Comment by OolongCow** [comment]
> Can already buy cigarettes in game. Don't wanna give everything in loadout.

You can also already get deluxe cigars, an item that usually requires a coin, from the loadout menu. Let the people have their cigarettes.

**Comment by Sparrowbird611** [comment]
Where's my lung cancer

**Comment by bearrrrrrrr** [comment]
> > Can already buy cigarettes in game. Don't wanna give everything in loadout.
> 
> You can also already get deluxe cigars, an item that usually requires a coin, from the loadout menu. Let the people have their cigarettes.

You right.

**Pull request merged**
