### PR TITLE
Citizens & Feds

### PR DESCRIPTION
**Pull request by ProbablyCarl**
- - -
Additions:
 - Provides a new category to IDs and player characters. This is citizenship within SolGov. Your rank determines where exactly that sits, if anywhere at all. This is likely to need adjustments in the future, but it worked in testing.
- - -
Changes:
 - Detective required to be a Federal Agent now, as per the change above. They, the Captain and SolGov Rep are the only First Citizens aboard at round start.
- - -

### CODE REVIEW

**Comment by SilverCelestine** [comment]
Sounds good to me and it'll fit in well with an upcoming change to Dagon Regulations and the creation of Sol Federal Law.

**Comment by Jul-Jul** [comment]
Don't forget the SGR guard is a Federal Agent too.

**Comment by ProbablyCarl** [comment]
That's fair. It's set by rank, so it should be fine.

**Comment by Sgtwok** [comment]
Removing marine, contractor, and fleet detective? Why?

**Pull request merged**
