### PR TITLE
Adds droppods

### PR DESCRIPTION
**Pull request by Anton-Kr**
CREDITS TO HALOSTATION FOR DROPPOD SPRITES

IF YOU HAVE AN ISSUE WITH ME USING THESE SPRITES CONTACT ME AND I WILL REMOVE THEM

- Adds droppods to storage above OFD where Cabin 2 used to be
- Droppods are fired from OFD and can contain one or two people
- Unlike normal charges, these only have a 12 second cooldown
- Droppods create a small explosive effect where they land and end up landing randomly on a non space tile inside the structure hit. Tactically this spreads out the infantry squad and makes them a bit easier to deal with.
- If you miss - droppod ends up in space

Additionally
- Fixes coffin related runtimes
- Fixes supply drops not working, so you can now OFD supply crates if you so desire.

### CODE REVIEW

**Comment by Kaksisilma** [comment]
Please test this and ensure that neither the supply or the drop pods are hitting space tiles

Also add it to supply

**Comment by Anton-Kr** [comment]
Believe already handled in code somewhere. Let me dig up where.

**Comment by Anton-Kr** [comment]
Yep, handled in disperser_fire.dm:113

**Comment by Anton-Kr** [comment]
added supply pack too

**Comment by Vizoplez** [comment]
Ready 4 merge?

**Comment by Anton-Kr** [comment]
Ready on my end

**Comment by Vizoplez** [comment]
CBT, had to revert this literally instantly because of a map issue involving area/ODST

nvm ill just fix it myself lololol

**Pull request merged**
