### PR TITLE
Sidearms

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
Allows Security Company members and Solgov Employees to carry around sidearms like military roles.

## Why It's Good For The Game
**Security** Companies would probably be carrying around not to mention in security roles they already get less skill points as is compared to the other 2. Solgov employees is mostly so SFP personel can have it but not far fetched that if a doctor has a gun that a scientist could have one too

## Did You Test It?
Yes

## Authorship
Me

## Changelog

:cl:
tweak: Allow sidearms for more branches
/:cl:

### CODE REVIEW

**Comment by Jul-Jul** [comment]
Just ensure that normal contractors and civvies can't have it. Though I personally think the PR seems fine.

**Comment by ProbablyCarl** [comment]
Might restrict mil roles?

**Comment by Lamasmaster** [comment]
Only "Civilians" that can have it with this are goverment workers (scientists pretty sure is only role that has that and representative) which I can't really change with how the system is set up without making SFP agents their own branch.

**Comment by Anton-Kr** [comment]
Honestly would prefer if you set up the feds as their own branch so that scientists and SGR don’t get guns.

**Comment by Lamasmaster** [comment]
Made SFP their own branch so only them and PMCs get it

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
