### PR TITLE
Veteris background choices

### PR DESCRIPTION
**Pull request by Rayfod**
Make the Veteris able to get the faction, and religion that they had previously.
New culture added for people that wants to be a part of clan, and if they get married with a unathi, etc.

Skærmbillede 2022-02-25 185245

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
This isn't a fix, this was intended. You can talk about this if you want, but giving them the "clans" faction when the one tiny bit of lore that they always had was that they don't have clans shows how poobrained this PR is.

edit: Alright, I didn't see you gave them a faction they never had before, because you called this a "fix". I'm okay with this.

edit edit: I STILL SAW YOUR DOWNTHUMB DON'T THINK I DIDN'T

**Comment by Rayfod** [comment]
I will change the rest of the desc to have some substance when I get the time.

**Comment by anconfuzedrock** [comment]
ey if it's for other reasons we're all good but carl I am now ok with this PR's existence

**Comment by ProbablyCarl** [comment]
Got it. Just waiting on corrections for CI.

**Comment by ProbablyCarl** [comment]
Fives instances of incorrect indentation.

**Comment by anconfuzedrock** [comment]
yaay errors fixed yaaaay

**Pull request merged**
