### PR TITLE
Rebalances Skrell Scout Vessel

### PR DESCRIPTION
**Pull request by AMcilraith**
- adds hypo
- Adds analysis bays
- adds displays
- adds food dispensers
- Adds sensors shutters

### CODE REVIEW

**Comment by Kaksisilma** [comment]
Skrell Hypos are not fine, and I've told you why in discord. Syringes and the RIG autoinjectors work fine.

We already have sensor shutters on the SSV. Where did you add more shutters?

Food dispensers are fine. What did you mean by 'displays'?

Analysis bays look a bit too much like prison cells. Please rework them so that they do not include medical equipment.

Please remove the reinforced flooring inside engineering.

**Comment by AMcilraith** [comment]
> **Skrell Hypos are not fine, and I've told you why in discord. Syringes and the RIG autoinjectors work fine.**
Done
> **We already have sensor shutters on the SSV. Where did you add more shutters?**
I did not add more shutters, I was unaware there was glass inside, so my changes were, in fact, very useless. No mechanical change has occurred
> **Food dispensers are fine. What did you mean by 'displays'?**
Nav displays that allow you to see where the ship is.
> **Analysis bays look a bit too much like prison cells. Please rework them so that they do not include medical equipment.**
Aight, fair enough done
> **Please remove the reinforced flooring inside engineering.**
Done

**Comment by Kaksisilma** [comment]
> > **Skrell Hypos are not fine, and I've told you why in discord. Syringes and the RIG autoinjectors work fine.**
> > Done
> > **We already have sensor shutters on the SSV. Where did you add more shutters?**
> > I did not add more shutters, I was unaware there was glass inside, so my changes were, in fact, very useless. No mechanical change has occurred
> > **Food dispensers are fine. What did you mean by 'displays'?**
> > Nav displays that allow you to see where the ship is.
> > **Analysis bays look a bit too much like prison cells. Please rework them so that they do not include medical equipment.**
> > Aight, fair enough done
> > **Please remove the reinforced flooring inside engineering.**
> > Done

Another odd thing I noticed is the presence of the chemical dispenser inside surgery. Please keep it in chemistry, it makes no sense in their infirmary.

The Engineering room still has flooring. It needs to be plating, like the ones used in torch maintenance and the ones that were there before. (Not airless plating, mind you. Make sure to get the pressurized ones.) The cables NEED to be visible is the point I'm getting at.

I'm a bit eeeesh-ish with the tactical plate carriers but I'll allow them, though, do rename them to 'skrellian plate carrier.'

Big no to the Fax machine. They should be torch-only and we already have too many of those. The Vuxix does not need one. If you need to communicate with your superior, simply emote typing on a console while you ahelp.

There seems to be a white reinforced wall in the morgue???

I think that's it. Additions to surgery are OK, too.

Please document your changes better next time, this is a lot of stuff that should've been in the description, and adhere to the contributing format get when you open a PR. (Why is this good to the game, What does this do and ET-cetera.)

**Review by Kaksisilma — DISMISSED** [review]
why did you remove the burritos 😢 

ok to merge otherwise

**Review by Kaksisilma — APPROVED** [review]
Still looks OK.

**Pull request merged**
