### PR TITLE
Revert "Branch/rank tweaks for diona, adherent, and prometheans"

### PR DESCRIPTION
**Pull request by Roland410**
Reverts BoHBranch/BoH-Bay#900
This PR was heavily biased against dionaea, adherents and especially prometheans, and should not have been merged in my opinion at all.

### CODE REVIEW

**Comment by Superhats** [comment]
IMHO, it didn't make much sense how diona/adherents could be in command roles, or even part of the NTEF altogether, considering they both have a fundamentally different way of thinking (diona being extremely slow-thinking and adherents being servile by nature)

**Comment by reklaw9** [comment]
lets not lie, the PR really was agaisnt dionas and prometheans,the only thing that it did that was good was make adherents able to be surgeons again

**Comment by Superhats** [comment]
It wasn't "against dionas". It blocked them out of some branches/roles that didn't make sense. Yes, it's not a positive change, but that doesn't mean it's a **bad** change.

**Comment by BurgerLUA** [comment]
There was a poll for this and it passed. It's highly unlikely that this will be reverted but I guess I can do another poll after 1 month of the changes.

**Comment by Roland410** [comment]
I'll probably will be addressing this in another PR anyways, just forgot to close this.

**Pull request closed without merging**
