### PR TITLE
I made the cryo office nobody used a public office

### PR DESCRIPTION
**Pull request by YuiY1997**
## About The Pull Request
Changed access of the Vacant Cryo Office to be crewmembers instead of heads. Added a few chairs. Made access to fax machine in the office public. Renamed it to Public Office
## Why It's Good For The Game
The space might actually get used now and the public fax machine gives players more chances to use the clerical kit traitor item
## Did You Test It?
Yes
## Authorship
Ckey YuiY1997
## Changelog

:cl:
* maptweak
Changed access of the Vacant Cryo Office to be crewmembers instead of heads. Added a few chairs. Made access to fax machine in the office public. Renamed airlock to Public Office and fax machine department to Public Office
/:cl:

<!--

This is my first map edit so if I royally fucked something up I'm sorry

### CODE REVIEW

**Comment by gilvian** [comment]
mind showing a picture of the room beforehand?

**Comment by YuiY1997** [comment]
> mind showing a picture of the room beforehand?
jinkus pinkus

**Comment by YuiY1997** [comment]
I have no idea what I'm doing right now

**Comment by ProbablyCarl** [comment]
Jesus.
Map merge, my guy.

**Comment by N8-Toe** [comment]
what the carl man said. Do you need help using map merge?

**Comment by YuiY1997** [comment]
how the fuck do you map merge I don't know what the fuck to do this is my first map edit ever

**Pull request closed without merging**
