### PR TITLE
powercreeps the rawl more

### PR DESCRIPTION
**Pull request by anconfuzedrock**
-The War pick's blade now retracts when deactivated, turning it into a weaker blunt weapon as a less lethal option. It's also a bit smaller. new sprites for the retracted pick.
-the rawl's disposal unit is now in a more central location and it has a stove, since you need those to make a good steak. It also has handrails in the cockpit so the fourth guy doesn't *have* to get tossed around everywhere. 
-Buffs the pilot's ham radio

also changes skillpoint values from 18 - 14 - 16 to 20 - 16 - 18 after realizing that literally janitors have more skillpoints than the engineer, and you might need those skillpoints.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
upon realising that I wayy undertuned their skill points (the default skillpoints is 16, meaning the engineer literally had less than default) I powercreeped the numbers by 2.

**Comment by Anton-Kr** [comment]
Since I am a fucking idiot and forgot, please include Rawl in away_sites_testing.dm and fix CI issues that are presented. Let me know if you want to do this in this or a different PR.

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
CI the ship

**Comment by anconfuzedrock** [comment]
alright, shove it in, not sure I'll be able to tell which iissues (if any) are mine, but we'll see..

**Comment by anconfuzedrock** [comment]
okay, seems I've got at least one thing I know how to fix, let's do this...

**Comment by anconfuzedrock** [comment]
not totally sure what  I did  with "Merge branch 'dev' into morerawl" so that COULD be bad (but it doesn't look liek it is, It looks like I accidentally learned how to fix merge conflicts in the future), but i believe that missing disposals pipe was the only error it caused. (which is fixed)

**Comment by Anton-Kr** [comment]
conflicts in lefthand and righthand.dmi.

**Review by Anton-Kr — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by anconfuzedrock** [comment]
I think I got it?

**Review by Anton-Kr — APPROVED** [review]

**Pull request merged**
